/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-1.0.0-dev */

#include "ciot/proto/v2/wifi_multi.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(CIOT_WIFI_MULTI_ITEM_CFG, ciot_wifi_multi_item_cfg_t, AUTO)


PB_BIND(CIOT_WIFI_MULTI_CFG, ciot_wifi_multi_cfg_t, AUTO)


PB_BIND(CIOT_WIFI_MULTI_ITEM_STATUS, ciot_wifi_multi_item_status_t, AUTO)


PB_BIND(CIOT_WIFI_MULTI_STATUS, ciot_wifi_multi_status_t, AUTO)


PB_BIND(CIOT_WIFI_MULTI_INFO, ciot_wifi_multi_info_t, AUTO)


PB_BIND(CIOT_WIFI_MULTI_REQ_NEXT, ciot_wifi_multi_req_next_t, AUTO)


PB_BIND(CIOT_WIFI_MULTI_REQ_SET_INVALID, ciot_wifi_multi_req_set_invalid_t, AUTO)


PB_BIND(CIOT_WIFI_MULTI_REQ_MARK_ACTIVE_INVALID, ciot_wifi_multi_req_mark_active_invalid_t, AUTO)


PB_BIND(CIOT_WIFI_MULTI_REQ_RESET_INVALID, ciot_wifi_multi_req_reset_invalid_t, AUTO)


PB_BIND(CIOT_WIFI_MULTI_REQ_GET_ITEM, ciot_wifi_multi_req_get_item_t, AUTO)


PB_BIND(CIOT_WIFI_MULTI_REQ_SET_ITEM, ciot_wifi_multi_req_set_item_t, AUTO)


PB_BIND(CIOT_WIFI_MULTI_REQ, ciot_wifi_multi_req_t, AUTO)


PB_BIND(CIOT_WIFI_MULTI_STOP, ciot_wifi_multi_stop_t, AUTO)


PB_BIND(CIOT_WIFI_MULTI_DATA, ciot_wifi_multi_data_t, AUTO)



