/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-1.0.0-dev */

#include "sparkplug-b/proto/v1/sparkplug_b.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(SPARKPLUGB_PAYLOAD, sparkplugb_payload_t, 4)


PB_BIND(SPARKPLUGB_PAYLOAD_TEMPLATE, sparkplugb_payload_template_t, 4)


PB_BIND(SPARKPLUGB_PAYLOAD_TEMPLATE_PARAMETER, sparkplugb_payload_template_parameter_t, AUTO)


PB_BIND(SPARKPLUGB_PAYLOAD_TEMPLATE_PARAMETER_PARAMETER_VALUE_EXTENSION, sparkplugb_payload_template_parameter_parameter_value_extension_t, AUTO)


PB_BIND(SPARKPLUGB_PAYLOAD_DATA_SET, sparkplugb_payload_data_set_t, 2)


PB_BIND(SPARKPLUGB_PAYLOAD_DATA_SET_DATA_SET_VALUE, sparkplugb_payload_data_set_data_set_value_t, AUTO)


PB_BIND(SPARKPLUGB_PAYLOAD_DATA_SET_DATA_SET_VALUE_DATA_SET_VALUE_EXTENSION, sparkplugb_payload_data_set_data_set_value_data_set_value_extension_t, AUTO)


PB_BIND(SPARKPLUGB_PAYLOAD_DATA_SET_ROW, sparkplugb_payload_data_set_row_t, 2)


PB_BIND(SPARKPLUGB_PAYLOAD_PROPERTY_VALUE, sparkplugb_payload_property_value_t, AUTO)


PB_BIND(SPARKPLUGB_PAYLOAD_PROPERTY_VALUE_PROPERTY_VALUE_EXTENSION, sparkplugb_payload_property_value_property_value_extension_t, AUTO)


PB_BIND(SPARKPLUGB_PAYLOAD_PROPERTY_SET, sparkplugb_payload_property_set_t, 2)


PB_BIND(SPARKPLUGB_PAYLOAD_PROPERTY_SET_LIST, sparkplugb_payload_property_set_list_t, AUTO)


PB_BIND(SPARKPLUGB_PAYLOAD_META_DATA, sparkplugb_payload_meta_data_t, AUTO)


PB_BIND(SPARKPLUGB_PAYLOAD_METRIC, sparkplugb_payload_metric_t, 2)


PB_BIND(SPARKPLUGB_PAYLOAD_METRIC_METRIC_VALUE_EXTENSION, sparkplugb_payload_metric_metric_value_extension_t, AUTO)



#ifndef PB_CONVERT_DOUBLE_FLOAT
/* On some platforms (such as AVR), double is really float.
 * To be able to encode/decode double on these platforms, you need.
 * to define PB_CONVERT_DOUBLE_FLOAT in pb.h or compiler command line.
 */
PB_STATIC_ASSERT(sizeof(double) == 8, DOUBLE_MUST_BE_8_BYTES)
#endif

