/* Automatically generated nanopb header */
/* Generated by nanopb-1.0.0-dev */

#ifndef PB_COM_CIRRUSLINK_SPARKPLUG_PROTOBUF_SPARKPLUG_B_PROTO_V1_SPARKPLUG_B_PB_H_INCLUDED
#define PB_COM_CIRRUSLINK_SPARKPLUG_PROTOBUF_SPARKPLUG_B_PROTO_V1_SPARKPLUG_B_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct sparkplugb_payload_template_parameter_parameter_value_extension {
    pb_extension_t *extensions;
} sparkplugb_payload_template_parameter_parameter_value_extension_t;

typedef struct sparkplugb_payload_template_parameter {
    bool has_name;
    char name[32];
    bool has_type;
    uint32_t type;
    pb_size_t which_value;
    union {
        uint32_t int_value;
        uint64_t long_value;
        float float_value;
        double double_value;
        bool boolean_value;
        char string_value[32];
        sparkplugb_payload_template_parameter_parameter_value_extension_t extension_value;
    };
} sparkplugb_payload_template_parameter_t;

typedef struct sparkplugb_payload_data_set_data_set_value_data_set_value_extension {
    pb_extension_t *extensions;
} sparkplugb_payload_data_set_data_set_value_data_set_value_extension_t;

typedef struct sparkplugb_payload_data_set_data_set_value {
    pb_size_t which_value;
    union {
        uint32_t int_value;
        uint64_t long_value;
        float float_value;
        double double_value;
        bool boolean_value;
        char string_value[32];
        sparkplugb_payload_data_set_data_set_value_data_set_value_extension_t extension_value;
    };
} sparkplugb_payload_data_set_data_set_value_t;

typedef struct sparkplugb_payload_data_set_row {
    pb_size_t elements_count;
    sparkplugb_payload_data_set_data_set_value_t elements[8];
    pb_extension_t *extensions;
} sparkplugb_payload_data_set_row_t;

typedef struct sparkplugb_payload_data_set {
    bool has_num_of_columns;
    uint64_t num_of_columns;
    pb_size_t columns_count;
    char columns[8][32];
    pb_size_t types_count;
    uint32_t types[8];
    pb_size_t rows_count;
    sparkplugb_payload_data_set_row_t rows[8];
    pb_extension_t *extensions;
} sparkplugb_payload_data_set_t;

typedef struct sparkplugb_payload_property_value_property_value_extension {
    pb_extension_t *extensions;
} sparkplugb_payload_property_value_property_value_extension_t;

typedef struct sparkplugb_payload_property_set_list {
    pb_size_t propertyset_count;
    struct sparkplugb_payload_property_set *propertyset;
    pb_extension_t *extensions;
} sparkplugb_payload_property_set_list_t;

typedef struct sparkplugb_payload_property_value {
    bool has_type;
    uint32_t type;
    bool has_is_null;
    bool is_null;
    pb_size_t which_value;
    union {
        uint32_t int_value;
        uint64_t long_value;
        float float_value;
        double double_value;
        bool boolean_value;
        char string_value[32];
        /* PropertySet     propertyset_value       = 9; */
        sparkplugb_payload_property_set_list_t propertysets_value; /* List of Property Values */
        sparkplugb_payload_property_value_property_value_extension_t extension_value;
    };
} sparkplugb_payload_property_value_t;

typedef struct sparkplugb_payload_property_set {
    pb_size_t keys_count;
    char keys[4][32]; /* Names of the properties */
    pb_size_t values_count;
    sparkplugb_payload_property_value_t values[4];
    pb_extension_t *extensions;
} sparkplugb_payload_property_set_t;

typedef struct sparkplugb_payload_meta_data {
    /* Bytes specific metadata */
    bool has_is_multi_part;
    bool is_multi_part;
    /* General metadata */
    bool has_content_type;
    char content_type[32]; /* Content/Media type */
    bool has_size;
    uint64_t size; /* File size, String size, Multi-part size, etc */
    bool has_seq;
    uint64_t seq; /* Sequence number for multi-part messages */
    /* File metadata */
    bool has_file_name;
    char file_name[32]; /* File name */
    bool has_file_type;
    char file_type[16]; /* File type (i.e. xml, json, txt, cpp, etc) */
    bool has_md5;
    char md5[32]; /* md5 of data */
    /* Catchalls and future expansion */
    bool has_description;
    char description[64]; /* Could be anything such as json or xml of custom properties */
    pb_extension_t *extensions;
} sparkplugb_payload_meta_data_t;

typedef struct sparkplugb_payload_metric_metric_value_extension {
    pb_extension_t *extensions;
} sparkplugb_payload_metric_metric_value_extension_t;

typedef PB_BYTES_ARRAY_T(32) sparkplugb_payload_metric_bytes_value_t;
typedef struct sparkplugb_payload_metric {
    bool has_name;
    char name[32]; /* Metric name - should only be included on birth */
    bool has_alias;
    uint64_t alias; /* Metric alias - tied to name on birth and included in all later DATA messages */
    bool has_timestamp;
    uint64_t timestamp; /* Timestamp associated with data acquisition time */
    bool has_datatype;
    uint32_t datatype; /* DataType of the metric/tag value */
    bool has_is_historical;
    bool is_historical; /* If this is historical data and should not update real time tag */
    bool has_is_transient;
    bool is_transient; /* Tells consuming clients such as MQTT Engine to not store this as a tag */
    bool has_is_null;
    bool is_null; /* If this is null - explicitly say so rather than using -1, false, etc for some datatypes. */
    bool has_metadata;
    sparkplugb_payload_meta_data_t metadata; /* Metadata for the payload */
    bool has_properties;
    sparkplugb_payload_property_set_t properties;
    pb_size_t which_value;
    union {
        uint32_t int_value;
        uint64_t long_value;
        float float_value;
        double double_value;
        bool boolean_value;
        char string_value[32];
        sparkplugb_payload_metric_bytes_value_t bytes_value; /* Bytes, File */
        sparkplugb_payload_data_set_t dataset_value;
        /* Template template_value                 = 18; */
        sparkplugb_payload_metric_metric_value_extension_t extension_value;
    };
} sparkplugb_payload_metric_t;

typedef PB_BYTES_ARRAY_T(128) sparkplugb_payload_body_t;
typedef struct sparkplugb_payload { /* // Indexes of Data Types

// Unknown placeholder for future expansion.
Unknown         = 0;

// Basic Types
Int8            = 1;
Int16           = 2;
Int32           = 3;
Int64           = 4;
UInt8           = 5;
UInt16          = 6;
UInt32          = 7;
UInt64          = 8;
Float           = 9;
Double          = 10;
Boolean         = 11;
String          = 12;
DateTime        = 13;
Text            = 14;

// Additional Metric Types
UUID            = 15;
DataSet         = 16;
Bytes           = 17;
File            = 18;
Template        = 19;

// Additional PropertyValue Types
PropertySet     = 20;
PropertySetList = 21; */
    bool has_timestamp;
    uint64_t timestamp; /* Timestamp at message sending time */
    pb_size_t metrics_count;
    sparkplugb_payload_metric_t metrics[8]; /* Repeated forever - no limit in Google Protobufs */
    bool has_seq;
    uint64_t seq; /* Sequence number */
    bool has_uuid;
    char uuid[36]; /* UUID to track message type in terms of schema definitions */
    bool has_body;
    sparkplugb_payload_body_t body; /* To optionally bypass the whole definition above */
    pb_extension_t *extensions;
} sparkplugb_payload_t;

typedef struct sparkplugb_payload_template {
    bool has_version;
    char version[16]; /* The version of the Template to prevent mismatches */
    pb_size_t metrics_count;
    sparkplugb_payload_metric_t metrics[4]; /* Each metric is the name of the metric and the datatype of the member but does not contain a value */
    pb_size_t parameters_count;
    sparkplugb_payload_template_parameter_t parameters[4];
    bool has_template_ref;
    char template_ref[32]; /* Reference to a template if this is extending a Template or an instance - must exist if an instance */
    bool has_is_definition;
    bool is_definition;
    pb_extension_t *extensions;
} sparkplugb_payload_template_t;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define SPARKPLUGB_PAYLOAD_INIT_DEFAULT          {false, 0, 0, {SPARKPLUGB_PAYLOAD_METRIC_INIT_DEFAULT, SPARKPLUGB_PAYLOAD_METRIC_INIT_DEFAULT, SPARKPLUGB_PAYLOAD_METRIC_INIT_DEFAULT, SPARKPLUGB_PAYLOAD_METRIC_INIT_DEFAULT, SPARKPLUGB_PAYLOAD_METRIC_INIT_DEFAULT, SPARKPLUGB_PAYLOAD_METRIC_INIT_DEFAULT, SPARKPLUGB_PAYLOAD_METRIC_INIT_DEFAULT, SPARKPLUGB_PAYLOAD_METRIC_INIT_DEFAULT}, false, 0, false, "", false, {0, {0}}, NULL}
#define SPARKPLUGB_PAYLOAD_TEMPLATE_INIT_DEFAULT {false, "", 0, {SPARKPLUGB_PAYLOAD_METRIC_INIT_DEFAULT, SPARKPLUGB_PAYLOAD_METRIC_INIT_DEFAULT, SPARKPLUGB_PAYLOAD_METRIC_INIT_DEFAULT, SPARKPLUGB_PAYLOAD_METRIC_INIT_DEFAULT}, 0, {SPARKPLUGB_PAYLOAD_TEMPLATE_PARAMETER_INIT_DEFAULT, SPARKPLUGB_PAYLOAD_TEMPLATE_PARAMETER_INIT_DEFAULT, SPARKPLUGB_PAYLOAD_TEMPLATE_PARAMETER_INIT_DEFAULT, SPARKPLUGB_PAYLOAD_TEMPLATE_PARAMETER_INIT_DEFAULT}, false, "", false, 0, NULL}
#define SPARKPLUGB_PAYLOAD_TEMPLATE_PARAMETER_INIT_DEFAULT {false, "", false, 0, 0, {0}}
#define SPARKPLUGB_PAYLOAD_TEMPLATE_PARAMETER_PARAMETER_VALUE_EXTENSION_INIT_DEFAULT {NULL}
#define SPARKPLUGB_PAYLOAD_DATA_SET_INIT_DEFAULT {false, 0, 0, {"", "", "", "", "", "", "", ""}, 0, {0, 0, 0, 0, 0, 0, 0, 0}, 0, {SPARKPLUGB_PAYLOAD_DATA_SET_ROW_INIT_DEFAULT, SPARKPLUGB_PAYLOAD_DATA_SET_ROW_INIT_DEFAULT, SPARKPLUGB_PAYLOAD_DATA_SET_ROW_INIT_DEFAULT, SPARKPLUGB_PAYLOAD_DATA_SET_ROW_INIT_DEFAULT, SPARKPLUGB_PAYLOAD_DATA_SET_ROW_INIT_DEFAULT, SPARKPLUGB_PAYLOAD_DATA_SET_ROW_INIT_DEFAULT, SPARKPLUGB_PAYLOAD_DATA_SET_ROW_INIT_DEFAULT, SPARKPLUGB_PAYLOAD_DATA_SET_ROW_INIT_DEFAULT}, NULL}
#define SPARKPLUGB_PAYLOAD_DATA_SET_DATA_SET_VALUE_INIT_DEFAULT {0, {0}}
#define SPARKPLUGB_PAYLOAD_DATA_SET_DATA_SET_VALUE_DATA_SET_VALUE_EXTENSION_INIT_DEFAULT {NULL}
#define SPARKPLUGB_PAYLOAD_DATA_SET_ROW_INIT_DEFAULT {0, {SPARKPLUGB_PAYLOAD_DATA_SET_DATA_SET_VALUE_INIT_DEFAULT, SPARKPLUGB_PAYLOAD_DATA_SET_DATA_SET_VALUE_INIT_DEFAULT, SPARKPLUGB_PAYLOAD_DATA_SET_DATA_SET_VALUE_INIT_DEFAULT, SPARKPLUGB_PAYLOAD_DATA_SET_DATA_SET_VALUE_INIT_DEFAULT, SPARKPLUGB_PAYLOAD_DATA_SET_DATA_SET_VALUE_INIT_DEFAULT, SPARKPLUGB_PAYLOAD_DATA_SET_DATA_SET_VALUE_INIT_DEFAULT, SPARKPLUGB_PAYLOAD_DATA_SET_DATA_SET_VALUE_INIT_DEFAULT, SPARKPLUGB_PAYLOAD_DATA_SET_DATA_SET_VALUE_INIT_DEFAULT}, NULL}
#define SPARKPLUGB_PAYLOAD_PROPERTY_VALUE_INIT_DEFAULT {false, 0, false, 0, 0, {0}}
#define SPARKPLUGB_PAYLOAD_PROPERTY_VALUE_PROPERTY_VALUE_EXTENSION_INIT_DEFAULT {NULL}
#define SPARKPLUGB_PAYLOAD_PROPERTY_SET_INIT_DEFAULT {0, {"", "", "", ""}, 0, {SPARKPLUGB_PAYLOAD_PROPERTY_VALUE_INIT_DEFAULT, SPARKPLUGB_PAYLOAD_PROPERTY_VALUE_INIT_DEFAULT, SPARKPLUGB_PAYLOAD_PROPERTY_VALUE_INIT_DEFAULT, SPARKPLUGB_PAYLOAD_PROPERTY_VALUE_INIT_DEFAULT}, NULL}
#define SPARKPLUGB_PAYLOAD_PROPERTY_SET_LIST_INIT_DEFAULT {0, NULL, NULL}
#define SPARKPLUGB_PAYLOAD_META_DATA_INIT_DEFAULT {false, 0, false, "", false, 0, false, 0, false, "", false, "", false, "", false, "", NULL}
#define SPARKPLUGB_PAYLOAD_METRIC_INIT_DEFAULT   {false, "", false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, SPARKPLUGB_PAYLOAD_META_DATA_INIT_DEFAULT, false, SPARKPLUGB_PAYLOAD_PROPERTY_SET_INIT_DEFAULT, 0, {0}}
#define SPARKPLUGB_PAYLOAD_METRIC_METRIC_VALUE_EXTENSION_INIT_DEFAULT {NULL}
#define SPARKPLUGB_PAYLOAD_INIT_ZERO             {false, 0, 0, {SPARKPLUGB_PAYLOAD_METRIC_INIT_ZERO, SPARKPLUGB_PAYLOAD_METRIC_INIT_ZERO, SPARKPLUGB_PAYLOAD_METRIC_INIT_ZERO, SPARKPLUGB_PAYLOAD_METRIC_INIT_ZERO, SPARKPLUGB_PAYLOAD_METRIC_INIT_ZERO, SPARKPLUGB_PAYLOAD_METRIC_INIT_ZERO, SPARKPLUGB_PAYLOAD_METRIC_INIT_ZERO, SPARKPLUGB_PAYLOAD_METRIC_INIT_ZERO}, false, 0, false, "", false, {0, {0}}, NULL}
#define SPARKPLUGB_PAYLOAD_TEMPLATE_INIT_ZERO    {false, "", 0, {SPARKPLUGB_PAYLOAD_METRIC_INIT_ZERO, SPARKPLUGB_PAYLOAD_METRIC_INIT_ZERO, SPARKPLUGB_PAYLOAD_METRIC_INIT_ZERO, SPARKPLUGB_PAYLOAD_METRIC_INIT_ZERO}, 0, {SPARKPLUGB_PAYLOAD_TEMPLATE_PARAMETER_INIT_ZERO, SPARKPLUGB_PAYLOAD_TEMPLATE_PARAMETER_INIT_ZERO, SPARKPLUGB_PAYLOAD_TEMPLATE_PARAMETER_INIT_ZERO, SPARKPLUGB_PAYLOAD_TEMPLATE_PARAMETER_INIT_ZERO}, false, "", false, 0, NULL}
#define SPARKPLUGB_PAYLOAD_TEMPLATE_PARAMETER_INIT_ZERO {false, "", false, 0, 0, {0}}
#define SPARKPLUGB_PAYLOAD_TEMPLATE_PARAMETER_PARAMETER_VALUE_EXTENSION_INIT_ZERO {NULL}
#define SPARKPLUGB_PAYLOAD_DATA_SET_INIT_ZERO    {false, 0, 0, {"", "", "", "", "", "", "", ""}, 0, {0, 0, 0, 0, 0, 0, 0, 0}, 0, {SPARKPLUGB_PAYLOAD_DATA_SET_ROW_INIT_ZERO, SPARKPLUGB_PAYLOAD_DATA_SET_ROW_INIT_ZERO, SPARKPLUGB_PAYLOAD_DATA_SET_ROW_INIT_ZERO, SPARKPLUGB_PAYLOAD_DATA_SET_ROW_INIT_ZERO, SPARKPLUGB_PAYLOAD_DATA_SET_ROW_INIT_ZERO, SPARKPLUGB_PAYLOAD_DATA_SET_ROW_INIT_ZERO, SPARKPLUGB_PAYLOAD_DATA_SET_ROW_INIT_ZERO, SPARKPLUGB_PAYLOAD_DATA_SET_ROW_INIT_ZERO}, NULL}
#define SPARKPLUGB_PAYLOAD_DATA_SET_DATA_SET_VALUE_INIT_ZERO {0, {0}}
#define SPARKPLUGB_PAYLOAD_DATA_SET_DATA_SET_VALUE_DATA_SET_VALUE_EXTENSION_INIT_ZERO {NULL}
#define SPARKPLUGB_PAYLOAD_DATA_SET_ROW_INIT_ZERO {0, {SPARKPLUGB_PAYLOAD_DATA_SET_DATA_SET_VALUE_INIT_ZERO, SPARKPLUGB_PAYLOAD_DATA_SET_DATA_SET_VALUE_INIT_ZERO, SPARKPLUGB_PAYLOAD_DATA_SET_DATA_SET_VALUE_INIT_ZERO, SPARKPLUGB_PAYLOAD_DATA_SET_DATA_SET_VALUE_INIT_ZERO, SPARKPLUGB_PAYLOAD_DATA_SET_DATA_SET_VALUE_INIT_ZERO, SPARKPLUGB_PAYLOAD_DATA_SET_DATA_SET_VALUE_INIT_ZERO, SPARKPLUGB_PAYLOAD_DATA_SET_DATA_SET_VALUE_INIT_ZERO, SPARKPLUGB_PAYLOAD_DATA_SET_DATA_SET_VALUE_INIT_ZERO}, NULL}
#define SPARKPLUGB_PAYLOAD_PROPERTY_VALUE_INIT_ZERO {false, 0, false, 0, 0, {0}}
#define SPARKPLUGB_PAYLOAD_PROPERTY_VALUE_PROPERTY_VALUE_EXTENSION_INIT_ZERO {NULL}
#define SPARKPLUGB_PAYLOAD_PROPERTY_SET_INIT_ZERO {0, {"", "", "", ""}, 0, {SPARKPLUGB_PAYLOAD_PROPERTY_VALUE_INIT_ZERO, SPARKPLUGB_PAYLOAD_PROPERTY_VALUE_INIT_ZERO, SPARKPLUGB_PAYLOAD_PROPERTY_VALUE_INIT_ZERO, SPARKPLUGB_PAYLOAD_PROPERTY_VALUE_INIT_ZERO}, NULL}
#define SPARKPLUGB_PAYLOAD_PROPERTY_SET_LIST_INIT_ZERO {0, NULL, NULL}
#define SPARKPLUGB_PAYLOAD_META_DATA_INIT_ZERO   {false, 0, false, "", false, 0, false, 0, false, "", false, "", false, "", false, "", NULL}
#define SPARKPLUGB_PAYLOAD_METRIC_INIT_ZERO      {false, "", false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, SPARKPLUGB_PAYLOAD_META_DATA_INIT_ZERO, false, SPARKPLUGB_PAYLOAD_PROPERTY_SET_INIT_ZERO, 0, {0}}
#define SPARKPLUGB_PAYLOAD_METRIC_METRIC_VALUE_EXTENSION_INIT_ZERO {NULL}

/* Field tags (for use in manual encoding/decoding) */
#define SPARKPLUGB_PAYLOAD_TEMPLATE_PARAMETER_NAME_TAG 1
#define SPARKPLUGB_PAYLOAD_TEMPLATE_PARAMETER_TYPE_TAG 2
#define SPARKPLUGB_PAYLOAD_TEMPLATE_PARAMETER_INT_VALUE_TAG 3
#define SPARKPLUGB_PAYLOAD_TEMPLATE_PARAMETER_LONG_VALUE_TAG 4
#define SPARKPLUGB_PAYLOAD_TEMPLATE_PARAMETER_FLOAT_VALUE_TAG 5
#define SPARKPLUGB_PAYLOAD_TEMPLATE_PARAMETER_DOUBLE_VALUE_TAG 6
#define SPARKPLUGB_PAYLOAD_TEMPLATE_PARAMETER_BOOLEAN_VALUE_TAG 7
#define SPARKPLUGB_PAYLOAD_TEMPLATE_PARAMETER_STRING_VALUE_TAG 8
#define SPARKPLUGB_PAYLOAD_TEMPLATE_PARAMETER_EXTENSION_VALUE_TAG 9
#define SPARKPLUGB_PAYLOAD_DATA_SET_DATA_SET_VALUE_INT_VALUE_TAG 1
#define SPARKPLUGB_PAYLOAD_DATA_SET_DATA_SET_VALUE_LONG_VALUE_TAG 2
#define SPARKPLUGB_PAYLOAD_DATA_SET_DATA_SET_VALUE_FLOAT_VALUE_TAG 3
#define SPARKPLUGB_PAYLOAD_DATA_SET_DATA_SET_VALUE_DOUBLE_VALUE_TAG 4
#define SPARKPLUGB_PAYLOAD_DATA_SET_DATA_SET_VALUE_BOOLEAN_VALUE_TAG 5
#define SPARKPLUGB_PAYLOAD_DATA_SET_DATA_SET_VALUE_STRING_VALUE_TAG 6
#define SPARKPLUGB_PAYLOAD_DATA_SET_DATA_SET_VALUE_EXTENSION_VALUE_TAG 7
#define SPARKPLUGB_PAYLOAD_DATA_SET_ROW_ELEMENTS_TAG 1
#define SPARKPLUGB_PAYLOAD_DATA_SET_NUM_OF_COLUMNS_TAG 1
#define SPARKPLUGB_PAYLOAD_DATA_SET_COLUMNS_TAG  2
#define SPARKPLUGB_PAYLOAD_DATA_SET_TYPES_TAG    3
#define SPARKPLUGB_PAYLOAD_DATA_SET_ROWS_TAG     4
#define SPARKPLUGB_PAYLOAD_PROPERTY_SET_LIST_PROPERTYSET_TAG 1
#define SPARKPLUGB_PAYLOAD_PROPERTY_VALUE_TYPE_TAG 1
#define SPARKPLUGB_PAYLOAD_PROPERTY_VALUE_IS_NULL_TAG 2
#define SPARKPLUGB_PAYLOAD_PROPERTY_VALUE_INT_VALUE_TAG 3
#define SPARKPLUGB_PAYLOAD_PROPERTY_VALUE_LONG_VALUE_TAG 4
#define SPARKPLUGB_PAYLOAD_PROPERTY_VALUE_FLOAT_VALUE_TAG 5
#define SPARKPLUGB_PAYLOAD_PROPERTY_VALUE_DOUBLE_VALUE_TAG 6
#define SPARKPLUGB_PAYLOAD_PROPERTY_VALUE_BOOLEAN_VALUE_TAG 7
#define SPARKPLUGB_PAYLOAD_PROPERTY_VALUE_STRING_VALUE_TAG 8
#define SPARKPLUGB_PAYLOAD_PROPERTY_VALUE_PROPERTYSETS_VALUE_TAG 10
#define SPARKPLUGB_PAYLOAD_PROPERTY_VALUE_EXTENSION_VALUE_TAG 11
#define SPARKPLUGB_PAYLOAD_PROPERTY_SET_KEYS_TAG 1
#define SPARKPLUGB_PAYLOAD_PROPERTY_SET_VALUES_TAG 2
#define SPARKPLUGB_PAYLOAD_META_DATA_IS_MULTI_PART_TAG 1
#define SPARKPLUGB_PAYLOAD_META_DATA_CONTENT_TYPE_TAG 2
#define SPARKPLUGB_PAYLOAD_META_DATA_SIZE_TAG    3
#define SPARKPLUGB_PAYLOAD_META_DATA_SEQ_TAG     4
#define SPARKPLUGB_PAYLOAD_META_DATA_FILE_NAME_TAG 5
#define SPARKPLUGB_PAYLOAD_META_DATA_FILE_TYPE_TAG 6
#define SPARKPLUGB_PAYLOAD_META_DATA_MD5_TAG     7
#define SPARKPLUGB_PAYLOAD_META_DATA_DESCRIPTION_TAG 8
#define SPARKPLUGB_PAYLOAD_METRIC_NAME_TAG       1
#define SPARKPLUGB_PAYLOAD_METRIC_ALIAS_TAG      2
#define SPARKPLUGB_PAYLOAD_METRIC_TIMESTAMP_TAG  3
#define SPARKPLUGB_PAYLOAD_METRIC_DATATYPE_TAG   4
#define SPARKPLUGB_PAYLOAD_METRIC_IS_HISTORICAL_TAG 5
#define SPARKPLUGB_PAYLOAD_METRIC_IS_TRANSIENT_TAG 6
#define SPARKPLUGB_PAYLOAD_METRIC_IS_NULL_TAG    7
#define SPARKPLUGB_PAYLOAD_METRIC_METADATA_TAG   8
#define SPARKPLUGB_PAYLOAD_METRIC_PROPERTIES_TAG 9
#define SPARKPLUGB_PAYLOAD_METRIC_INT_VALUE_TAG  10
#define SPARKPLUGB_PAYLOAD_METRIC_LONG_VALUE_TAG 11
#define SPARKPLUGB_PAYLOAD_METRIC_FLOAT_VALUE_TAG 12
#define SPARKPLUGB_PAYLOAD_METRIC_DOUBLE_VALUE_TAG 13
#define SPARKPLUGB_PAYLOAD_METRIC_BOOLEAN_VALUE_TAG 14
#define SPARKPLUGB_PAYLOAD_METRIC_STRING_VALUE_TAG 15
#define SPARKPLUGB_PAYLOAD_METRIC_BYTES_VALUE_TAG 16
#define SPARKPLUGB_PAYLOAD_METRIC_DATASET_VALUE_TAG 17
#define SPARKPLUGB_PAYLOAD_METRIC_EXTENSION_VALUE_TAG 19
#define SPARKPLUGB_PAYLOAD_TIMESTAMP_TAG         1
#define SPARKPLUGB_PAYLOAD_METRICS_TAG           2
#define SPARKPLUGB_PAYLOAD_SEQ_TAG               3
#define SPARKPLUGB_PAYLOAD_UUID_TAG              4
#define SPARKPLUGB_PAYLOAD_BODY_TAG              5
#define SPARKPLUGB_PAYLOAD_TEMPLATE_VERSION_TAG  1
#define SPARKPLUGB_PAYLOAD_TEMPLATE_METRICS_TAG  2
#define SPARKPLUGB_PAYLOAD_TEMPLATE_PARAMETERS_TAG 3
#define SPARKPLUGB_PAYLOAD_TEMPLATE_TEMPLATE_REF_TAG 4
#define SPARKPLUGB_PAYLOAD_TEMPLATE_IS_DEFINITION_TAG 5

/* Struct field encoding specification for nanopb */
#define SPARKPLUGB_PAYLOAD_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UINT64,   timestamp,         1) \
X(a, STATIC,   REPEATED, MESSAGE,  metrics,           2) \
X(a, STATIC,   OPTIONAL, UINT64,   seq,               3) \
X(a, STATIC,   OPTIONAL, STRING,   uuid,              4) \
X(a, STATIC,   OPTIONAL, BYTES,    body,              5) \
X(a, CALLBACK, OPTIONAL, EXTENSION, extensions,        6)
#define SPARKPLUGB_PAYLOAD_CALLBACK pb_default_field_callback
#define SPARKPLUGB_PAYLOAD_DEFAULT NULL
#define sparkplugb_payload_t_metrics_MSGTYPE sparkplugb_payload_metric_t

#define SPARKPLUGB_PAYLOAD_TEMPLATE_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, STRING,   version,           1) \
X(a, STATIC,   REPEATED, MESSAGE,  metrics,           2) \
X(a, STATIC,   REPEATED, MESSAGE,  parameters,        3) \
X(a, STATIC,   OPTIONAL, STRING,   template_ref,      4) \
X(a, STATIC,   OPTIONAL, BOOL,     is_definition,     5) \
X(a, CALLBACK, OPTIONAL, EXTENSION, extensions,        6)
#define SPARKPLUGB_PAYLOAD_TEMPLATE_CALLBACK pb_default_field_callback
#define SPARKPLUGB_PAYLOAD_TEMPLATE_DEFAULT NULL
#define sparkplugb_payload_template_t_metrics_MSGTYPE sparkplugb_payload_metric_t
#define sparkplugb_payload_template_t_parameters_MSGTYPE sparkplugb_payload_template_parameter_t

#define SPARKPLUGB_PAYLOAD_TEMPLATE_PARAMETER_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, STRING,   name,              1) \
X(a, STATIC,   OPTIONAL, UINT32,   type,              2) \
X(a, STATIC,   ONEOF,    UINT32,   (value,int_value,int_value),   3) \
X(a, STATIC,   ONEOF,    UINT64,   (value,long_value,long_value),   4) \
X(a, STATIC,   ONEOF,    FLOAT,    (value,float_value,float_value),   5) \
X(a, STATIC,   ONEOF,    DOUBLE,   (value,double_value,double_value),   6) \
X(a, STATIC,   ONEOF,    BOOL,     (value,boolean_value,boolean_value),   7) \
X(a, STATIC,   ONEOF,    STRING,   (value,string_value,string_value),   8) \
X(a, STATIC,   ONEOF,    MESSAGE,  (value,extension_value,extension_value),   9)
#define SPARKPLUGB_PAYLOAD_TEMPLATE_PARAMETER_CALLBACK NULL
#define SPARKPLUGB_PAYLOAD_TEMPLATE_PARAMETER_DEFAULT NULL
#define sparkplugb_payload_template_parameter_t_value_extension_value_MSGTYPE sparkplugb_payload_template_parameter_parameter_value_extension_t

#define SPARKPLUGB_PAYLOAD_TEMPLATE_PARAMETER_PARAMETER_VALUE_EXTENSION_FIELDLIST(X, a) \
X(a, CALLBACK, OPTIONAL, EXTENSION, extensions,        1)
#define SPARKPLUGB_PAYLOAD_TEMPLATE_PARAMETER_PARAMETER_VALUE_EXTENSION_CALLBACK pb_default_field_callback
#define SPARKPLUGB_PAYLOAD_TEMPLATE_PARAMETER_PARAMETER_VALUE_EXTENSION_DEFAULT NULL

#define SPARKPLUGB_PAYLOAD_DATA_SET_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UINT64,   num_of_columns,    1) \
X(a, STATIC,   REPEATED, STRING,   columns,           2) \
X(a, STATIC,   REPEATED, UINT32,   types,             3) \
X(a, STATIC,   REPEATED, MESSAGE,  rows,              4) \
X(a, CALLBACK, OPTIONAL, EXTENSION, extensions,        5)
#define SPARKPLUGB_PAYLOAD_DATA_SET_CALLBACK pb_default_field_callback
#define SPARKPLUGB_PAYLOAD_DATA_SET_DEFAULT NULL
#define sparkplugb_payload_data_set_t_rows_MSGTYPE sparkplugb_payload_data_set_row_t

#define SPARKPLUGB_PAYLOAD_DATA_SET_DATA_SET_VALUE_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    UINT32,   (value,int_value,int_value),   1) \
X(a, STATIC,   ONEOF,    UINT64,   (value,long_value,long_value),   2) \
X(a, STATIC,   ONEOF,    FLOAT,    (value,float_value,float_value),   3) \
X(a, STATIC,   ONEOF,    DOUBLE,   (value,double_value,double_value),   4) \
X(a, STATIC,   ONEOF,    BOOL,     (value,boolean_value,boolean_value),   5) \
X(a, STATIC,   ONEOF,    STRING,   (value,string_value,string_value),   6) \
X(a, STATIC,   ONEOF,    MESSAGE,  (value,extension_value,extension_value),   7)
#define SPARKPLUGB_PAYLOAD_DATA_SET_DATA_SET_VALUE_CALLBACK NULL
#define SPARKPLUGB_PAYLOAD_DATA_SET_DATA_SET_VALUE_DEFAULT NULL
#define sparkplugb_payload_data_set_data_set_value_t_value_extension_value_MSGTYPE sparkplugb_payload_data_set_data_set_value_data_set_value_extension_t

#define SPARKPLUGB_PAYLOAD_DATA_SET_DATA_SET_VALUE_DATA_SET_VALUE_EXTENSION_FIELDLIST(X, a) \
X(a, CALLBACK, OPTIONAL, EXTENSION, extensions,        1)
#define SPARKPLUGB_PAYLOAD_DATA_SET_DATA_SET_VALUE_DATA_SET_VALUE_EXTENSION_CALLBACK pb_default_field_callback
#define SPARKPLUGB_PAYLOAD_DATA_SET_DATA_SET_VALUE_DATA_SET_VALUE_EXTENSION_DEFAULT NULL

#define SPARKPLUGB_PAYLOAD_DATA_SET_ROW_FIELDLIST(X, a) \
X(a, STATIC,   REPEATED, MESSAGE,  elements,          1) \
X(a, CALLBACK, OPTIONAL, EXTENSION, extensions,        2)
#define SPARKPLUGB_PAYLOAD_DATA_SET_ROW_CALLBACK pb_default_field_callback
#define SPARKPLUGB_PAYLOAD_DATA_SET_ROW_DEFAULT NULL
#define sparkplugb_payload_data_set_row_t_elements_MSGTYPE sparkplugb_payload_data_set_data_set_value_t

#define SPARKPLUGB_PAYLOAD_PROPERTY_VALUE_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UINT32,   type,              1) \
X(a, STATIC,   OPTIONAL, BOOL,     is_null,           2) \
X(a, STATIC,   ONEOF,    UINT32,   (value,int_value,int_value),   3) \
X(a, STATIC,   ONEOF,    UINT64,   (value,long_value,long_value),   4) \
X(a, STATIC,   ONEOF,    FLOAT,    (value,float_value,float_value),   5) \
X(a, STATIC,   ONEOF,    DOUBLE,   (value,double_value,double_value),   6) \
X(a, STATIC,   ONEOF,    BOOL,     (value,boolean_value,boolean_value),   7) \
X(a, STATIC,   ONEOF,    STRING,   (value,string_value,string_value),   8) \
X(a, STATIC,   ONEOF,    MESSAGE,  (value,propertysets_value,propertysets_value),  10) \
X(a, STATIC,   ONEOF,    MESSAGE,  (value,extension_value,extension_value),  11)
#define SPARKPLUGB_PAYLOAD_PROPERTY_VALUE_CALLBACK NULL
#define SPARKPLUGB_PAYLOAD_PROPERTY_VALUE_DEFAULT NULL
#define sparkplugb_payload_property_value_t_value_propertysets_value_MSGTYPE sparkplugb_payload_property_set_list_t
#define sparkplugb_payload_property_value_t_value_extension_value_MSGTYPE sparkplugb_payload_property_value_property_value_extension_t

#define SPARKPLUGB_PAYLOAD_PROPERTY_VALUE_PROPERTY_VALUE_EXTENSION_FIELDLIST(X, a) \
X(a, CALLBACK, OPTIONAL, EXTENSION, extensions,        1)
#define SPARKPLUGB_PAYLOAD_PROPERTY_VALUE_PROPERTY_VALUE_EXTENSION_CALLBACK pb_default_field_callback
#define SPARKPLUGB_PAYLOAD_PROPERTY_VALUE_PROPERTY_VALUE_EXTENSION_DEFAULT NULL

#define SPARKPLUGB_PAYLOAD_PROPERTY_SET_FIELDLIST(X, a) \
X(a, STATIC,   REPEATED, STRING,   keys,              1) \
X(a, STATIC,   REPEATED, MESSAGE,  values,            2) \
X(a, CALLBACK, OPTIONAL, EXTENSION, extensions,        3)
#define SPARKPLUGB_PAYLOAD_PROPERTY_SET_CALLBACK pb_default_field_callback
#define SPARKPLUGB_PAYLOAD_PROPERTY_SET_DEFAULT NULL
#define sparkplugb_payload_property_set_t_values_MSGTYPE sparkplugb_payload_property_value_t

#define SPARKPLUGB_PAYLOAD_PROPERTY_SET_LIST_FIELDLIST(X, a) \
X(a, POINTER,  REPEATED, MESSAGE,  propertyset,       1) \
X(a, CALLBACK, OPTIONAL, EXTENSION, extensions,        2)
#define SPARKPLUGB_PAYLOAD_PROPERTY_SET_LIST_CALLBACK pb_default_field_callback
#define SPARKPLUGB_PAYLOAD_PROPERTY_SET_LIST_DEFAULT NULL
#define sparkplugb_payload_property_set_list_t_propertyset_MSGTYPE sparkplugb_payload_property_set_t

#define SPARKPLUGB_PAYLOAD_META_DATA_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, BOOL,     is_multi_part,     1) \
X(a, STATIC,   OPTIONAL, STRING,   content_type,      2) \
X(a, STATIC,   OPTIONAL, UINT64,   size,              3) \
X(a, STATIC,   OPTIONAL, UINT64,   seq,               4) \
X(a, STATIC,   OPTIONAL, STRING,   file_name,         5) \
X(a, STATIC,   OPTIONAL, STRING,   file_type,         6) \
X(a, STATIC,   OPTIONAL, STRING,   md5,               7) \
X(a, STATIC,   OPTIONAL, STRING,   description,       8) \
X(a, CALLBACK, OPTIONAL, EXTENSION, extensions,        9)
#define SPARKPLUGB_PAYLOAD_META_DATA_CALLBACK pb_default_field_callback
#define SPARKPLUGB_PAYLOAD_META_DATA_DEFAULT NULL

#define SPARKPLUGB_PAYLOAD_METRIC_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, STRING,   name,              1) \
X(a, STATIC,   OPTIONAL, UINT64,   alias,             2) \
X(a, STATIC,   OPTIONAL, UINT64,   timestamp,         3) \
X(a, STATIC,   OPTIONAL, UINT32,   datatype,          4) \
X(a, STATIC,   OPTIONAL, BOOL,     is_historical,     5) \
X(a, STATIC,   OPTIONAL, BOOL,     is_transient,      6) \
X(a, STATIC,   OPTIONAL, BOOL,     is_null,           7) \
X(a, STATIC,   OPTIONAL, MESSAGE,  metadata,          8) \
X(a, STATIC,   OPTIONAL, MESSAGE,  properties,        9) \
X(a, STATIC,   ONEOF,    UINT32,   (value,int_value,int_value),  10) \
X(a, STATIC,   ONEOF,    UINT64,   (value,long_value,long_value),  11) \
X(a, STATIC,   ONEOF,    FLOAT,    (value,float_value,float_value),  12) \
X(a, STATIC,   ONEOF,    DOUBLE,   (value,double_value,double_value),  13) \
X(a, STATIC,   ONEOF,    BOOL,     (value,boolean_value,boolean_value),  14) \
X(a, STATIC,   ONEOF,    STRING,   (value,string_value,string_value),  15) \
X(a, STATIC,   ONEOF,    BYTES,    (value,bytes_value,bytes_value),  16) \
X(a, STATIC,   ONEOF,    MESSAGE,  (value,dataset_value,dataset_value),  17) \
X(a, STATIC,   ONEOF,    MESSAGE,  (value,extension_value,extension_value),  19)
#define SPARKPLUGB_PAYLOAD_METRIC_CALLBACK NULL
#define SPARKPLUGB_PAYLOAD_METRIC_DEFAULT NULL
#define sparkplugb_payload_metric_t_metadata_MSGTYPE sparkplugb_payload_meta_data_t
#define sparkplugb_payload_metric_t_properties_MSGTYPE sparkplugb_payload_property_set_t
#define sparkplugb_payload_metric_t_value_dataset_value_MSGTYPE sparkplugb_payload_data_set_t
#define sparkplugb_payload_metric_t_value_extension_value_MSGTYPE sparkplugb_payload_metric_metric_value_extension_t

#define SPARKPLUGB_PAYLOAD_METRIC_METRIC_VALUE_EXTENSION_FIELDLIST(X, a) \
X(a, CALLBACK, OPTIONAL, EXTENSION, extensions,        1)
#define SPARKPLUGB_PAYLOAD_METRIC_METRIC_VALUE_EXTENSION_CALLBACK pb_default_field_callback
#define SPARKPLUGB_PAYLOAD_METRIC_METRIC_VALUE_EXTENSION_DEFAULT NULL

extern const pb_msgdesc_t sparkplugb_payload_t_msg;
extern const pb_msgdesc_t sparkplugb_payload_template_t_msg;
extern const pb_msgdesc_t sparkplugb_payload_template_parameter_t_msg;
extern const pb_msgdesc_t sparkplugb_payload_template_parameter_parameter_value_extension_t_msg;
extern const pb_msgdesc_t sparkplugb_payload_data_set_t_msg;
extern const pb_msgdesc_t sparkplugb_payload_data_set_data_set_value_t_msg;
extern const pb_msgdesc_t sparkplugb_payload_data_set_data_set_value_data_set_value_extension_t_msg;
extern const pb_msgdesc_t sparkplugb_payload_data_set_row_t_msg;
extern const pb_msgdesc_t sparkplugb_payload_property_value_t_msg;
extern const pb_msgdesc_t sparkplugb_payload_property_value_property_value_extension_t_msg;
extern const pb_msgdesc_t sparkplugb_payload_property_set_t_msg;
extern const pb_msgdesc_t sparkplugb_payload_property_set_list_t_msg;
extern const pb_msgdesc_t sparkplugb_payload_meta_data_t_msg;
extern const pb_msgdesc_t sparkplugb_payload_metric_t_msg;
extern const pb_msgdesc_t sparkplugb_payload_metric_metric_value_extension_t_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define SPARKPLUGB_PAYLOAD_FIELDS &sparkplugb_payload_t_msg
#define SPARKPLUGB_PAYLOAD_TEMPLATE_FIELDS &sparkplugb_payload_template_t_msg
#define SPARKPLUGB_PAYLOAD_TEMPLATE_PARAMETER_FIELDS &sparkplugb_payload_template_parameter_t_msg
#define SPARKPLUGB_PAYLOAD_TEMPLATE_PARAMETER_PARAMETER_VALUE_EXTENSION_FIELDS &sparkplugb_payload_template_parameter_parameter_value_extension_t_msg
#define SPARKPLUGB_PAYLOAD_DATA_SET_FIELDS &sparkplugb_payload_data_set_t_msg
#define SPARKPLUGB_PAYLOAD_DATA_SET_DATA_SET_VALUE_FIELDS &sparkplugb_payload_data_set_data_set_value_t_msg
#define SPARKPLUGB_PAYLOAD_DATA_SET_DATA_SET_VALUE_DATA_SET_VALUE_EXTENSION_FIELDS &sparkplugb_payload_data_set_data_set_value_data_set_value_extension_t_msg
#define SPARKPLUGB_PAYLOAD_DATA_SET_ROW_FIELDS &sparkplugb_payload_data_set_row_t_msg
#define SPARKPLUGB_PAYLOAD_PROPERTY_VALUE_FIELDS &sparkplugb_payload_property_value_t_msg
#define SPARKPLUGB_PAYLOAD_PROPERTY_VALUE_PROPERTY_VALUE_EXTENSION_FIELDS &sparkplugb_payload_property_value_property_value_extension_t_msg
#define SPARKPLUGB_PAYLOAD_PROPERTY_SET_FIELDS &sparkplugb_payload_property_set_t_msg
#define SPARKPLUGB_PAYLOAD_PROPERTY_SET_LIST_FIELDS &sparkplugb_payload_property_set_list_t_msg
#define SPARKPLUGB_PAYLOAD_META_DATA_FIELDS &sparkplugb_payload_meta_data_t_msg
#define SPARKPLUGB_PAYLOAD_METRIC_FIELDS &sparkplugb_payload_metric_t_msg
#define SPARKPLUGB_PAYLOAD_METRIC_METRIC_VALUE_EXTENSION_FIELDS &sparkplugb_payload_metric_metric_value_extension_t_msg

/* Maximum encoded size of messages (where known) */
/* Sparkplugb_Payload_size depends on runtime parameters */
/* Sparkplugb_Payload_Template_size depends on runtime parameters */
/* Sparkplugb_Payload_PropertyValue_size depends on runtime parameters */
/* Sparkplugb_Payload_PropertySet_size depends on runtime parameters */
/* Sparkplugb_Payload_PropertySetList_size depends on runtime parameters */
/* Sparkplugb_Payload_Metric_size depends on runtime parameters */
#define COM_CIRRUSLINK_SPARKPLUG_PROTOBUF_SPARKPLUG_B_PROTO_V1_SPARKPLUG_B_PB_H_MAX_SIZE SPARKPLUGB_PAYLOAD_DATA_SET_SIZE
#define SPARKPLUGB_PAYLOAD_DATA_SET_DATA_SET_VALUE_DATA_SET_VALUE_EXTENSION_SIZE 0
#define SPARKPLUGB_PAYLOAD_DATA_SET_DATA_SET_VALUE_SIZE 33
#define SPARKPLUGB_PAYLOAD_DATA_SET_ROW_SIZE     280
#define SPARKPLUGB_PAYLOAD_DATA_SET_SIZE         2587
#define SPARKPLUGB_PAYLOAD_META_DATA_SIZE        205
#define SPARKPLUGB_PAYLOAD_METRIC_METRIC_VALUE_EXTENSION_SIZE 0
#define SPARKPLUGB_PAYLOAD_PROPERTY_VALUE_PROPERTY_VALUE_EXTENSION_SIZE 0
#define SPARKPLUGB_PAYLOAD_TEMPLATE_PARAMETER_PARAMETER_VALUE_EXTENSION_SIZE 0
#define SPARKPLUGB_PAYLOAD_TEMPLATE_PARAMETER_SIZE 72

/* Mapping from canonical names (mangle_names or overridden package name) */
#define com_cirruslink_sparkplug_protobuf_Payload Sparkplugb_Payload
#define Sparkplugb_Payload com_cirruslink_sparkplug_protobuf_payload_t
#define com_cirruslink_sparkplug_protobuf_payload_t sparkplugb_payload_t
#define com_cirruslink_sparkplug_protobuf_Payload_Template Sparkplugb_Payload_Template
#define Sparkplugb_Payload_Template com_cirruslink_sparkplug_protobuf_payload_template_t
#define com_cirruslink_sparkplug_protobuf_payload_template_t sparkplugb_payload_template_t
#define com_cirruslink_sparkplug_protobuf_Payload_Template_Parameter Sparkplugb_Payload_Template_Parameter
#define Sparkplugb_Payload_Template_Parameter com_cirruslink_sparkplug_protobuf_payload_template_parameter_t
#define com_cirruslink_sparkplug_protobuf_payload_template_parameter_t sparkplugb_payload_template_parameter_t
#define com_cirruslink_sparkplug_protobuf_Payload_Template_Parameter_ParameterValueExtension Sparkplugb_Payload_Template_Parameter_ParameterValueExtension
#define Sparkplugb_Payload_Template_Parameter_ParameterValueExtension com_cirruslink_sparkplug_protobuf_payload_template_parameter_parameter_value_extension_t
#define com_cirruslink_sparkplug_protobuf_payload_template_parameter_parameter_value_extension_t sparkplugb_payload_template_parameter_parameter_value_extension_t
#define com_cirruslink_sparkplug_protobuf_Payload_DataSet Sparkplugb_Payload_DataSet
#define Sparkplugb_Payload_DataSet com_cirruslink_sparkplug_protobuf_payload_data_set_t
#define com_cirruslink_sparkplug_protobuf_payload_data_set_t sparkplugb_payload_data_set_t
#define com_cirruslink_sparkplug_protobuf_Payload_DataSet_DataSetValue Sparkplugb_Payload_DataSet_DataSetValue
#define Sparkplugb_Payload_DataSet_DataSetValue com_cirruslink_sparkplug_protobuf_payload_data_set_data_set_value_t
#define com_cirruslink_sparkplug_protobuf_payload_data_set_data_set_value_t sparkplugb_payload_data_set_data_set_value_t
#define com_cirruslink_sparkplug_protobuf_Payload_DataSet_DataSetValue_DataSetValueExtension Sparkplugb_Payload_DataSet_DataSetValue_DataSetValueExtension
#define Sparkplugb_Payload_DataSet_DataSetValue_DataSetValueExtension com_cirruslink_sparkplug_protobuf_payload_data_set_data_set_value_data_set_value_extension_t
#define com_cirruslink_sparkplug_protobuf_payload_data_set_data_set_value_data_set_value_extension_t sparkplugb_payload_data_set_data_set_value_data_set_value_extension_t
#define com_cirruslink_sparkplug_protobuf_Payload_DataSet_Row Sparkplugb_Payload_DataSet_Row
#define Sparkplugb_Payload_DataSet_Row com_cirruslink_sparkplug_protobuf_payload_data_set_row_t
#define com_cirruslink_sparkplug_protobuf_payload_data_set_row_t sparkplugb_payload_data_set_row_t
#define com_cirruslink_sparkplug_protobuf_Payload_PropertyValue Sparkplugb_Payload_PropertyValue
#define Sparkplugb_Payload_PropertyValue com_cirruslink_sparkplug_protobuf_payload_property_value_t
#define com_cirruslink_sparkplug_protobuf_payload_property_value_t sparkplugb_payload_property_value_t
#define com_cirruslink_sparkplug_protobuf_Payload_PropertyValue_PropertyValueExtension Sparkplugb_Payload_PropertyValue_PropertyValueExtension
#define Sparkplugb_Payload_PropertyValue_PropertyValueExtension com_cirruslink_sparkplug_protobuf_payload_property_value_property_value_extension_t
#define com_cirruslink_sparkplug_protobuf_payload_property_value_property_value_extension_t sparkplugb_payload_property_value_property_value_extension_t
#define com_cirruslink_sparkplug_protobuf_Payload_PropertySet Sparkplugb_Payload_PropertySet
#define Sparkplugb_Payload_PropertySet com_cirruslink_sparkplug_protobuf_payload_property_set_t
#define com_cirruslink_sparkplug_protobuf_payload_property_set_t sparkplugb_payload_property_set_t
#define com_cirruslink_sparkplug_protobuf_Payload_PropertySetList Sparkplugb_Payload_PropertySetList
#define Sparkplugb_Payload_PropertySetList com_cirruslink_sparkplug_protobuf_payload_property_set_list_t
#define com_cirruslink_sparkplug_protobuf_payload_property_set_list_t sparkplugb_payload_property_set_list_t
#define com_cirruslink_sparkplug_protobuf_Payload_MetaData Sparkplugb_Payload_MetaData
#define Sparkplugb_Payload_MetaData com_cirruslink_sparkplug_protobuf_payload_meta_data_t
#define com_cirruslink_sparkplug_protobuf_payload_meta_data_t sparkplugb_payload_meta_data_t
#define com_cirruslink_sparkplug_protobuf_Payload_Metric Sparkplugb_Payload_Metric
#define Sparkplugb_Payload_Metric com_cirruslink_sparkplug_protobuf_payload_metric_t
#define com_cirruslink_sparkplug_protobuf_payload_metric_t sparkplugb_payload_metric_t
#define com_cirruslink_sparkplug_protobuf_Payload_Metric_MetricValueExtension Sparkplugb_Payload_Metric_MetricValueExtension
#define Sparkplugb_Payload_Metric_MetricValueExtension com_cirruslink_sparkplug_protobuf_payload_metric_metric_value_extension_t
#define com_cirruslink_sparkplug_protobuf_payload_metric_metric_value_extension_t sparkplugb_payload_metric_metric_value_extension_t
#define COM_CIRRUSLINK_SPARKPLUG_PROTOBUF_PAYLOAD_INIT_DEFAULT SPARKPLUGB_PAYLOAD_INIT_DEFAULT
#define COM_CIRRUSLINK_SPARKPLUG_PROTOBUF_PAYLOAD_TEMPLATE_INIT_DEFAULT SPARKPLUGB_PAYLOAD_TEMPLATE_INIT_DEFAULT
#define COM_CIRRUSLINK_SPARKPLUG_PROTOBUF_PAYLOAD_TEMPLATE_PARAMETER_INIT_DEFAULT SPARKPLUGB_PAYLOAD_TEMPLATE_PARAMETER_INIT_DEFAULT
#define COM_CIRRUSLINK_SPARKPLUG_PROTOBUF_PAYLOAD_TEMPLATE_PARAMETER_PARAMETER_VALUE_EXTENSION_INIT_DEFAULT SPARKPLUGB_PAYLOAD_TEMPLATE_PARAMETER_PARAMETER_VALUE_EXTENSION_INIT_DEFAULT
#define COM_CIRRUSLINK_SPARKPLUG_PROTOBUF_PAYLOAD_DATA_SET_INIT_DEFAULT SPARKPLUGB_PAYLOAD_DATA_SET_INIT_DEFAULT
#define COM_CIRRUSLINK_SPARKPLUG_PROTOBUF_PAYLOAD_DATA_SET_DATA_SET_VALUE_INIT_DEFAULT SPARKPLUGB_PAYLOAD_DATA_SET_DATA_SET_VALUE_INIT_DEFAULT
#define COM_CIRRUSLINK_SPARKPLUG_PROTOBUF_PAYLOAD_DATA_SET_DATA_SET_VALUE_DATA_SET_VALUE_EXTENSION_INIT_DEFAULT SPARKPLUGB_PAYLOAD_DATA_SET_DATA_SET_VALUE_DATA_SET_VALUE_EXTENSION_INIT_DEFAULT
#define COM_CIRRUSLINK_SPARKPLUG_PROTOBUF_PAYLOAD_DATA_SET_ROW_INIT_DEFAULT SPARKPLUGB_PAYLOAD_DATA_SET_ROW_INIT_DEFAULT
#define COM_CIRRUSLINK_SPARKPLUG_PROTOBUF_PAYLOAD_PROPERTY_VALUE_INIT_DEFAULT SPARKPLUGB_PAYLOAD_PROPERTY_VALUE_INIT_DEFAULT
#define COM_CIRRUSLINK_SPARKPLUG_PROTOBUF_PAYLOAD_PROPERTY_VALUE_PROPERTY_VALUE_EXTENSION_INIT_DEFAULT SPARKPLUGB_PAYLOAD_PROPERTY_VALUE_PROPERTY_VALUE_EXTENSION_INIT_DEFAULT
#define COM_CIRRUSLINK_SPARKPLUG_PROTOBUF_PAYLOAD_PROPERTY_SET_INIT_DEFAULT SPARKPLUGB_PAYLOAD_PROPERTY_SET_INIT_DEFAULT
#define COM_CIRRUSLINK_SPARKPLUG_PROTOBUF_PAYLOAD_PROPERTY_SET_LIST_INIT_DEFAULT SPARKPLUGB_PAYLOAD_PROPERTY_SET_LIST_INIT_DEFAULT
#define COM_CIRRUSLINK_SPARKPLUG_PROTOBUF_PAYLOAD_META_DATA_INIT_DEFAULT SPARKPLUGB_PAYLOAD_META_DATA_INIT_DEFAULT
#define COM_CIRRUSLINK_SPARKPLUG_PROTOBUF_PAYLOAD_METRIC_INIT_DEFAULT SPARKPLUGB_PAYLOAD_METRIC_INIT_DEFAULT
#define COM_CIRRUSLINK_SPARKPLUG_PROTOBUF_PAYLOAD_METRIC_METRIC_VALUE_EXTENSION_INIT_DEFAULT SPARKPLUGB_PAYLOAD_METRIC_METRIC_VALUE_EXTENSION_INIT_DEFAULT
#define COM_CIRRUSLINK_SPARKPLUG_PROTOBUF_PAYLOAD_INIT_ZERO SPARKPLUGB_PAYLOAD_INIT_ZERO
#define COM_CIRRUSLINK_SPARKPLUG_PROTOBUF_PAYLOAD_TEMPLATE_INIT_ZERO SPARKPLUGB_PAYLOAD_TEMPLATE_INIT_ZERO
#define COM_CIRRUSLINK_SPARKPLUG_PROTOBUF_PAYLOAD_TEMPLATE_PARAMETER_INIT_ZERO SPARKPLUGB_PAYLOAD_TEMPLATE_PARAMETER_INIT_ZERO
#define COM_CIRRUSLINK_SPARKPLUG_PROTOBUF_PAYLOAD_TEMPLATE_PARAMETER_PARAMETER_VALUE_EXTENSION_INIT_ZERO SPARKPLUGB_PAYLOAD_TEMPLATE_PARAMETER_PARAMETER_VALUE_EXTENSION_INIT_ZERO
#define COM_CIRRUSLINK_SPARKPLUG_PROTOBUF_PAYLOAD_DATA_SET_INIT_ZERO SPARKPLUGB_PAYLOAD_DATA_SET_INIT_ZERO
#define COM_CIRRUSLINK_SPARKPLUG_PROTOBUF_PAYLOAD_DATA_SET_DATA_SET_VALUE_INIT_ZERO SPARKPLUGB_PAYLOAD_DATA_SET_DATA_SET_VALUE_INIT_ZERO
#define COM_CIRRUSLINK_SPARKPLUG_PROTOBUF_PAYLOAD_DATA_SET_DATA_SET_VALUE_DATA_SET_VALUE_EXTENSION_INIT_ZERO SPARKPLUGB_PAYLOAD_DATA_SET_DATA_SET_VALUE_DATA_SET_VALUE_EXTENSION_INIT_ZERO
#define COM_CIRRUSLINK_SPARKPLUG_PROTOBUF_PAYLOAD_DATA_SET_ROW_INIT_ZERO SPARKPLUGB_PAYLOAD_DATA_SET_ROW_INIT_ZERO
#define COM_CIRRUSLINK_SPARKPLUG_PROTOBUF_PAYLOAD_PROPERTY_VALUE_INIT_ZERO SPARKPLUGB_PAYLOAD_PROPERTY_VALUE_INIT_ZERO
#define COM_CIRRUSLINK_SPARKPLUG_PROTOBUF_PAYLOAD_PROPERTY_VALUE_PROPERTY_VALUE_EXTENSION_INIT_ZERO SPARKPLUGB_PAYLOAD_PROPERTY_VALUE_PROPERTY_VALUE_EXTENSION_INIT_ZERO
#define COM_CIRRUSLINK_SPARKPLUG_PROTOBUF_PAYLOAD_PROPERTY_SET_INIT_ZERO SPARKPLUGB_PAYLOAD_PROPERTY_SET_INIT_ZERO
#define COM_CIRRUSLINK_SPARKPLUG_PROTOBUF_PAYLOAD_PROPERTY_SET_LIST_INIT_ZERO SPARKPLUGB_PAYLOAD_PROPERTY_SET_LIST_INIT_ZERO
#define COM_CIRRUSLINK_SPARKPLUG_PROTOBUF_PAYLOAD_META_DATA_INIT_ZERO SPARKPLUGB_PAYLOAD_META_DATA_INIT_ZERO
#define COM_CIRRUSLINK_SPARKPLUG_PROTOBUF_PAYLOAD_METRIC_INIT_ZERO SPARKPLUGB_PAYLOAD_METRIC_INIT_ZERO
#define COM_CIRRUSLINK_SPARKPLUG_PROTOBUF_PAYLOAD_METRIC_METRIC_VALUE_EXTENSION_INIT_ZERO SPARKPLUGB_PAYLOAD_METRIC_METRIC_VALUE_EXTENSION_INIT_ZERO

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
