get_filename_component(CIOT_DIR "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)

set(CIOT_INCLUDE_DIRS
    ${CIOT_DIR}/include
    ${CIOT_DIR}/src/protos
    ${CIOT_DIR}/src/mg
    ${CIOT_DIR}/src/nanopb
    ${CIOT_DIR}/src/nanomodbus
)

set(CIOT_PB_INCLUDE_DIRS
    ${CIOT_DIR}/src/
)

FILE(GLOB_RECURSE CIOT_COMMON_SRCS ${CIOT_DIR}/src/common/*.c)
FILE(GLOB_RECURSE CIOT_CORE_SRCS  ${CIOT_DIR}/src/core/*.c)
FILE(GLOB_RECURSE CIOT_NANOPB_C_SRCS ${CIOT_DIR}/src/nanopb/*.c)
FILE(GLOB_RECURSE CIOT_PB_V1_SRCS ${CIOT_DIR}/src/protos/ciot/proto/v1/*.c)
FILE(GLOB_RECURSE CIOT_PB_V2_SRCS ${CIOT_DIR}/src/protos/ciot/proto/v2/*.c)
FILE(GLOB_RECURSE SPARKPLUGB_V1_SRCS ${CIOT_DIR}/src/protos/sparkplug-b/proto/v1/*.c)
FILE(GLOB_RECURSE CIOT_MBED_SRCS ${CIOT_DIR}/src/crypt/*.c)
FILE(GLOB_RECURSE CIOT_MBUS_SRCS ${CIOT_DIR}/src/nanomodbus/*.c)

list(APPEND CIOT_SRCS ${CIOT_COMMON_SRCS})
list(APPEND CIOT_SRCS ${CIOT_CORE_SRCS})
list(APPEND CIOT_SRCS ${CIOT_NANOPB_C_SRCS})
list(APPEND CIOT_SRCS ${CIOT_MBUS_SRCS})

FILE(GLOB_RECURSE CIOT_NRF_SRCS ${CIOT_DIR}/src/nrf/*.c)
FILE(GLOB_RECURSE CIOT_ESP32_SRCS ${CIOT_DIR}/src/esp32/*.c)
FILE(GLOB_RECURSE CIOT_MG_SRCS ${CIOT_DIR}/src/mg/*.c)
FILE(GLOB_RECURSE CIOT_WIN_SRCS ${CIOT_DIR}/src/win/*.c)
FILE(GLOB_RECURSE CIOT_DEFAULT_SRCS ${CIOT_DIR}/src/default/*.c)

if(WIN32)
    list(APPEND CIOT_INCLUDE_DIRS ${CIOT_DIR}/src/crypt)
    list(APPEND CIOT_WIN_SRCS ${CIOT_MBED_SRCS})
endif()
