"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import ciot.proto.v2.errors_pb2
import google.protobuf.descriptor
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _BleScnState:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _BleScnStateEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_BleScnState.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    BLE_SCN_STATE_IDLE: _BleScnState.ValueType  # 0
    """Idle state"""
    BLE_SCN_STATE_PASSIVE: _BleScnState.ValueType  # 1
    """Passive scan enabled"""
    BLE_SCN_STATE_ACTIVE: _BleScnState.ValueType  # 2
    """Active scan enabled"""

class BleScnState(_BleScnState, metaclass=_BleScnStateEnumTypeWrapper):
    """Possible ble scanner states"""

BLE_SCN_STATE_IDLE: BleScnState.ValueType  # 0
"""Idle state"""
BLE_SCN_STATE_PASSIVE: BleScnState.ValueType  # 1
"""Passive scan enabled"""
BLE_SCN_STATE_ACTIVE: BleScnState.ValueType  # 2
"""Active scan enabled"""
global___BleScnState = BleScnState

@typing.final
class BleScnStop(google.protobuf.message.Message):
    """Ble scanner stop message"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___BleScnStop = BleScnStop

@typing.final
class BleScnCfg(google.protobuf.message.Message):
    """Ble scanner configuration"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    INTERVAL_FIELD_NUMBER: builtins.int
    WINDOW_FIELD_NUMBER: builtins.int
    TIMEOUT_FIELD_NUMBER: builtins.int
    ACTIVE_FIELD_NUMBER: builtins.int
    BRIDGE_MODE_FIELD_NUMBER: builtins.int
    interval: builtins.int
    """Scanner interval"""
    window: builtins.int
    """Scanner window"""
    timeout: builtins.int
    """Scanner timeout"""
    active: builtins.bool
    """Enable/disable active scan mode"""
    bridge_mode: builtins.bool
    """Enable/disable bridge. On bridge mode ciot lib dosen't interpret adv
    messages as an CioT requests and send all of them to the main application
    as an data message.
    """
    def __init__(
        self,
        *,
        interval: builtins.int = ...,
        window: builtins.int = ...,
        timeout: builtins.int = ...,
        active: builtins.bool = ...,
        bridge_mode: builtins.bool = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["active", b"active", "bridge_mode", b"bridge_mode", "interval", b"interval", "timeout", b"timeout", "window", b"window"]) -> None: ...

global___BleScnCfg = BleScnCfg

@typing.final
class BleScnAdvInfo(google.protobuf.message.Message):
    """Ble scanner advertisement information"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    MAC_FIELD_NUMBER: builtins.int
    RSSI_FIELD_NUMBER: builtins.int
    mac: builtins.bytes
    """Device mac"""
    rssi: builtins.int
    """Signal strenght"""
    def __init__(
        self,
        *,
        mac: builtins.bytes = ...,
        rssi: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["mac", b"mac", "rssi", b"rssi"]) -> None: ...

global___BleScnAdvInfo = BleScnAdvInfo

@typing.final
class BleScnAdv(google.protobuf.message.Message):
    """Ble scanner advertisement"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    INFO_FIELD_NUMBER: builtins.int
    PAYLOAD_FIELD_NUMBER: builtins.int
    payload: builtins.bytes
    """Advertisement payload"""
    @property
    def info(self) -> global___BleScnAdvInfo:
        """Advertisement information"""

    def __init__(
        self,
        *,
        info: global___BleScnAdvInfo | None = ...,
        payload: builtins.bytes = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["info", b"info"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["info", b"info", "payload", b"payload"]) -> None: ...

global___BleScnAdv = BleScnAdv

@typing.final
class BleScnStatus(google.protobuf.message.Message):
    """Ble scanner status"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    STATE_FIELD_NUMBER: builtins.int
    ERR_CODE_FIELD_NUMBER: builtins.int
    ADVS_LOSTED_FIELD_NUMBER: builtins.int
    FIFO_LEN_FIELD_NUMBER: builtins.int
    FIFO_MAX_FIELD_NUMBER: builtins.int
    state: global___BleScnState.ValueType
    """Current state"""
    err_code: ciot.proto.v2.errors_pb2.Err.ValueType
    """Current error code"""
    advs_losted: builtins.int
    """ADVs counter"""
    fifo_len: builtins.int
    """Current fifo lenght"""
    fifo_max: builtins.int
    """Fifo maximum size"""
    def __init__(
        self,
        *,
        state: global___BleScnState.ValueType = ...,
        err_code: ciot.proto.v2.errors_pb2.Err.ValueType = ...,
        advs_losted: builtins.int = ...,
        fifo_len: builtins.int = ...,
        fifo_max: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["advs_losted", b"advs_losted", "err_code", b"err_code", "fifo_len", b"fifo_len", "fifo_max", b"fifo_max", "state", b"state"]) -> None: ...

global___BleScnStatus = BleScnStatus

@typing.final
class BleScnReq(google.protobuf.message.Message):
    """Ble scanner request"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___BleScnReq = BleScnReq

@typing.final
class BleScnData(google.protobuf.message.Message):
    """Ble scanner data"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    STOP_FIELD_NUMBER: builtins.int
    CONFIG_FIELD_NUMBER: builtins.int
    STATUS_FIELD_NUMBER: builtins.int
    REQUEST_FIELD_NUMBER: builtins.int
    @property
    def stop(self) -> global___BleScnStop:
        """Stop ble scanner interface"""

    @property
    def config(self) -> global___BleScnCfg:
        """Configuration"""

    @property
    def status(self) -> global___BleScnStatus:
        """Status"""

    @property
    def request(self) -> global___BleScnReq:
        """Request"""

    def __init__(
        self,
        *,
        stop: global___BleScnStop | None = ...,
        config: global___BleScnCfg | None = ...,
        status: global___BleScnStatus | None = ...,
        request: global___BleScnReq | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["config", b"config", "request", b"request", "status", b"status", "stop", b"stop", "type", b"type"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["config", b"config", "request", b"request", "status", b"status", "stop", b"stop", "type", b"type"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["type", b"type"]) -> typing.Literal["stop", "config", "status", "request"] | None: ...

global___BleScnData = BleScnData
