"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import google.protobuf.descriptor
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _BleState:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _BleStateEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_BleState.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    BLE_STATE_IDLE: _BleState.ValueType  # 0
    """Idle state"""
    BLE_STATE_STARTED: _BleState.ValueType  # 1
    """Bluetooth module started"""

class BleState(_BleState, metaclass=_BleStateEnumTypeWrapper):
    """Possible ble states"""

BLE_STATE_IDLE: BleState.ValueType  # 0
"""Idle state"""
BLE_STATE_STARTED: BleState.ValueType  # 1
"""Bluetooth module started"""
global___BleState = BleState

@typing.final
class BleStop(google.protobuf.message.Message):
    """Bluetooth stop"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___BleStop = BleStop

@typing.final
class BleCfg(google.protobuf.message.Message):
    """Bluetooth module configuration"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    MAC_FIELD_NUMBER: builtins.int
    mac: builtins.bytes
    """Mac address. If empty, is ignored, and the hardware mac"""
    def __init__(
        self,
        *,
        mac: builtins.bytes = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["mac", b"mac"]) -> None: ...

global___BleCfg = BleCfg

@typing.final
class BleInfo(google.protobuf.message.Message):
    """Bluetooth module information"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    HW_MAC_FIELD_NUMBER: builtins.int
    SW_MAC_FIELD_NUMBER: builtins.int
    hw_mac: builtins.bytes
    """Hardware mac address"""
    sw_mac: builtins.bytes
    """Software mac address"""
    def __init__(
        self,
        *,
        hw_mac: builtins.bytes = ...,
        sw_mac: builtins.bytes = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["hw_mac", b"hw_mac", "sw_mac", b"sw_mac"]) -> None: ...

global___BleInfo = BleInfo

@typing.final
class BleStatus(google.protobuf.message.Message):
    """Bluetooth module status"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    STATE_FIELD_NUMBER: builtins.int
    ERR_CODE_FIELD_NUMBER: builtins.int
    USING_SW_MAC_FIELD_NUMBER: builtins.int
    state: global___BleState.ValueType
    """Current state"""
    err_code: builtins.int
    """Current error code"""
    using_sw_mac: builtins.bool
    """Software mac assigned"""
    def __init__(
        self,
        *,
        state: global___BleState.ValueType = ...,
        err_code: builtins.int = ...,
        using_sw_mac: builtins.bool = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["err_code", b"err_code", "state", b"state", "using_sw_mac", b"using_sw_mac"]) -> None: ...

global___BleStatus = BleStatus

@typing.final
class BleReq(google.protobuf.message.Message):
    """Bluetooth module request"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SET_MAC_FIELD_NUMBER: builtins.int
    set_mac: builtins.bytes
    def __init__(
        self,
        *,
        set_mac: builtins.bytes = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["set_mac", b"set_mac", "type", b"type"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["set_mac", b"set_mac", "type", b"type"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["type", b"type"]) -> typing.Literal["set_mac"] | None: ...

global___BleReq = BleReq

@typing.final
class BleData(google.protobuf.message.Message):
    """Bluetooth module data"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    STOP_FIELD_NUMBER: builtins.int
    CONFIG_FIELD_NUMBER: builtins.int
    STATUS_FIELD_NUMBER: builtins.int
    REQUEST_FIELD_NUMBER: builtins.int
    INFO_FIELD_NUMBER: builtins.int
    @property
    def stop(self) -> global___BleStop: ...
    @property
    def config(self) -> global___BleCfg: ...
    @property
    def status(self) -> global___BleStatus: ...
    @property
    def request(self) -> global___BleReq: ...
    @property
    def info(self) -> global___BleInfo: ...
    def __init__(
        self,
        *,
        stop: global___BleStop | None = ...,
        config: global___BleCfg | None = ...,
        status: global___BleStatus | None = ...,
        request: global___BleReq | None = ...,
        info: global___BleInfo | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["config", b"config", "info", b"info", "request", b"request", "status", b"status", "stop", b"stop", "type", b"type"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["config", b"config", "info", b"info", "request", b"request", "status", b"status", "stop", b"stop", "type", b"type"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["type", b"type"]) -> typing.Literal["stop", "config", "status", "request", "info"] | None: ...

global___BleData = BleData
