# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ciot/proto/v2/ble_scn.proto
# Protobuf Python Version: 6.30.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    0,
    '',
    'ciot/proto/v2/ble_scn.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ciot.proto.v2 import errors_pb2 as ciot_dot_proto_dot_v2_dot_errors__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1b\x63iot/proto/v2/ble_scn.proto\x12\x04\x43iot\x1a\x1a\x63iot/proto/v2/errors.proto\"\x0c\n\nBleScnStop\"c\n\tBleScnCfg\x12\x10\n\x08interval\x18\x01 \x01(\r\x12\x0e\n\x06window\x18\x02 \x01(\r\x12\x0f\n\x07timeout\x18\x03 \x01(\r\x12\x0e\n\x06\x61\x63tive\x18\x04 \x01(\x08\x12\x13\n\x0b\x62ridge_mode\x18\x05 \x01(\x08\"*\n\rBleScnAdvInfo\x12\x0b\n\x03mac\x18\x01 \x01(\x0c\x12\x0c\n\x04rssi\x18\x02 \x01(\x11\"?\n\tBleScnAdv\x12!\n\x04info\x18\x01 \x01(\x0b\x32\x13.Ciot.BleScnAdvInfo\x12\x0f\n\x07payload\x18\x02 \x01(\x0c\"\x86\x01\n\x0c\x42leScnStatus\x12 \n\x05state\x18\x01 \x01(\x0e\x32\x11.Ciot.BleScnState\x12\x1b\n\x08\x65rr_code\x18\x02 \x01(\x0e\x32\t.Ciot.Err\x12\x13\n\x0b\x61\x64vs_losted\x18\x03 \x01(\r\x12\x10\n\x08\x66ifo_len\x18\x04 \x01(\r\x12\x10\n\x08\x66ifo_max\x18\x05 \x01(\r\"\x0b\n\tBleScnReq\"\xa3\x01\n\nBleScnData\x12 \n\x04stop\x18\x01 \x01(\x0b\x32\x10.Ciot.BleScnStopH\x00\x12!\n\x06\x63onfig\x18\x02 \x01(\x0b\x32\x0f.Ciot.BleScnCfgH\x00\x12$\n\x06status\x18\x03 \x01(\x0b\x32\x12.Ciot.BleScnStatusH\x00\x12\"\n\x07request\x18\x04 \x01(\x0b\x32\x0f.Ciot.BleScnReqH\x00\x42\x06\n\x04type*Z\n\x0b\x42leScnState\x12\x16\n\x12\x42LE_SCN_STATE_IDLE\x10\x00\x12\x19\n\x15\x42LE_SCN_STATE_PASSIVE\x10\x01\x12\x18\n\x14\x42LE_SCN_STATE_ACTIVE\x10\x02\x42\x11\xaa\x02\x0e\x43iot.Protos.V2b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ciot.proto.v2.ble_scn_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002\016Ciot.Protos.V2'
  _globals['_BLESCNSTATE']._serialized_start=605
  _globals['_BLESCNSTATE']._serialized_end=695
  _globals['_BLESCNSTOP']._serialized_start=65
  _globals['_BLESCNSTOP']._serialized_end=77
  _globals['_BLESCNCFG']._serialized_start=79
  _globals['_BLESCNCFG']._serialized_end=178
  _globals['_BLESCNADVINFO']._serialized_start=180
  _globals['_BLESCNADVINFO']._serialized_end=222
  _globals['_BLESCNADV']._serialized_start=224
  _globals['_BLESCNADV']._serialized_end=287
  _globals['_BLESCNSTATUS']._serialized_start=290
  _globals['_BLESCNSTATUS']._serialized_end=424
  _globals['_BLESCNREQ']._serialized_start=426
  _globals['_BLESCNREQ']._serialized_end=437
  _globals['_BLESCNDATA']._serialized_start=440
  _globals['_BLESCNDATA']._serialized_end=603
# @@protoc_insertion_point(module_scope)
