# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ciot/proto/v2/ble_adv.proto
# Protobuf Python Version: 6.30.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    0,
    '',
    'ciot/proto/v2/ble_adv.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1b\x63iot/proto/v2/ble_adv.proto\x12\x04\x43iot\"\x0c\n\nBleAdvStop\"f\n\tBleAdvCfg\x12\x10\n\x08interval\x18\x01 \x01(\r\x12\x10\n\x08\x64uration\x18\x02 \x01(\r\x12\x0c\n\x04type\x18\x03 \x01(\r\x12\x15\n\rfilter_policy\x18\x04 \x01(\r\x12\x10\n\x08tx_power\x18\x05 \x01(\r\"B\n\x0c\x42leAdvStatus\x12 \n\x05state\x18\x01 \x01(\x0e\x32\x11.Ciot.BleAdvState\x12\x10\n\x08\x65rr_code\x18\x02 \x01(\r\"\x0b\n\tBleAdvReq\"\xa3\x01\n\nBleAdvData\x12 \n\x04stop\x18\x01 \x01(\x0b\x32\x10.Ciot.BleAdvStopH\x00\x12!\n\x06\x63onfig\x18\x02 \x01(\x0b\x32\x0f.Ciot.BleAdvCfgH\x00\x12$\n\x06status\x18\x03 \x01(\x0b\x32\x12.Ciot.BleAdvStatusH\x00\x12\"\n\x07request\x18\x04 \x01(\x0b\x32\x0f.Ciot.BleAdvReqH\x00\x42\x06\n\x04type*[\n\x0b\x42leAdvState\x12\x16\n\x12\x42LE_ADV_STATE_IDLE\x10\x00\x12\x19\n\x15\x42LE_ADV_STATE_STARTED\x10\x01\x12\x19\n\x15\x42LE_ADV_STATE_SENDING\x10\x02\x42\x11\xaa\x02\x0e\x43iot.Protos.V2b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ciot.proto.v2.ble_adv_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002\016Ciot.Protos.V2'
  _globals['_BLEADVSTATE']._serialized_start=402
  _globals['_BLEADVSTATE']._serialized_end=493
  _globals['_BLEADVSTOP']._serialized_start=37
  _globals['_BLEADVSTOP']._serialized_end=49
  _globals['_BLEADVCFG']._serialized_start=51
  _globals['_BLEADVCFG']._serialized_end=153
  _globals['_BLEADVSTATUS']._serialized_start=155
  _globals['_BLEADVSTATUS']._serialized_end=221
  _globals['_BLEADVREQ']._serialized_start=223
  _globals['_BLEADVREQ']._serialized_end=234
  _globals['_BLEADVDATA']._serialized_start=237
  _globals['_BLEADVDATA']._serialized_end=400
# @@protoc_insertion_point(module_scope)
