# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ciot/proto/v2/ble.proto
# Protobuf Python Version: 6.30.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    0,
    '',
    'ciot/proto/v2/ble.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17\x63iot/proto/v2/ble.proto\x12\x04\x43iot\"\t\n\x07\x42leStop\"\x15\n\x06\x42leCfg\x12\x0b\n\x03mac\x18\x01 \x01(\x0c\")\n\x07\x42leInfo\x12\x0e\n\x06hw_mac\x18\x01 \x01(\x0c\x12\x0e\n\x06sw_mac\x18\x02 \x01(\x0c\"R\n\tBleStatus\x12\x1d\n\x05state\x18\x01 \x01(\x0e\x32\x0e.Ciot.BleState\x12\x10\n\x08\x65rr_code\x18\x02 \x01(\r\x12\x14\n\x0cusing_sw_mac\x18\x03 \x01(\x08\"#\n\x06\x42leReq\x12\x11\n\x07set_mac\x18\x01 \x01(\x0cH\x00\x42\x06\n\x04type\"\xb3\x01\n\x07\x42leData\x12\x1d\n\x04stop\x18\x01 \x01(\x0b\x32\r.Ciot.BleStopH\x00\x12\x1e\n\x06\x63onfig\x18\x02 \x01(\x0b\x32\x0c.Ciot.BleCfgH\x00\x12!\n\x06status\x18\x03 \x01(\x0b\x32\x0f.Ciot.BleStatusH\x00\x12\x1f\n\x07request\x18\x04 \x01(\x0b\x32\x0c.Ciot.BleReqH\x00\x12\x1d\n\x04info\x18\x06 \x01(\x0b\x32\r.Ciot.BleInfoH\x00\x42\x06\n\x04type*5\n\x08\x42leState\x12\x12\n\x0e\x42LE_STATE_IDLE\x10\x00\x12\x15\n\x11\x42LE_STATE_STARTED\x10\x01\x42\x11\xaa\x02\x0e\x43iot.Protos.V2b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ciot.proto.v2.ble_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002\016Ciot.Protos.V2'
  _globals['_BLESTATE']._serialized_start=413
  _globals['_BLESTATE']._serialized_end=466
  _globals['_BLESTOP']._serialized_start=33
  _globals['_BLESTOP']._serialized_end=42
  _globals['_BLECFG']._serialized_start=44
  _globals['_BLECFG']._serialized_end=65
  _globals['_BLEINFO']._serialized_start=67
  _globals['_BLEINFO']._serialized_end=108
  _globals['_BLESTATUS']._serialized_start=110
  _globals['_BLESTATUS']._serialized_end=192
  _globals['_BLEREQ']._serialized_start=194
  _globals['_BLEREQ']._serialized_end=229
  _globals['_BLEDATA']._serialized_start=232
  _globals['_BLEDATA']._serialized_end=411
# @@protoc_insertion_point(module_scope)
