"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import google.protobuf.descriptor
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _BleAdvState:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _BleAdvStateEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_BleAdvState.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    BLE_ADV_STATE_IDLE: _BleAdvState.ValueType  # 0
    """Idle state
    BLE adv state: idle.
    """
    BLE_ADV_STATE_STARTED: _BleAdvState.ValueType  # 1
    """BLE adv state: started and waiting for timeout."""
    BLE_ADV_STATE_SENDING: _BleAdvState.ValueType  # 2
    """BLE adv state: sending data."""

class BleAdvState(_BleAdvState, metaclass=_BleAdvStateEnumTypeWrapper):
    """Possible ble adv states"""

BLE_ADV_STATE_IDLE: BleAdvState.ValueType  # 0
"""Idle state
BLE adv state: idle.
"""
BLE_ADV_STATE_STARTED: BleAdvState.ValueType  # 1
"""BLE adv state: started and waiting for timeout."""
BLE_ADV_STATE_SENDING: BleAdvState.ValueType  # 2
"""BLE adv state: sending data."""
global___BleAdvState = BleAdvState

@typing.final
class BleAdvStop(google.protobuf.message.Message):
    """Ble adv stop message"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___BleAdvStop = BleAdvStop

@typing.final
class BleAdvCfg(google.protobuf.message.Message):
    """Ble adv configuration"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    INTERVAL_FIELD_NUMBER: builtins.int
    DURATION_FIELD_NUMBER: builtins.int
    TYPE_FIELD_NUMBER: builtins.int
    FILTER_POLICY_FIELD_NUMBER: builtins.int
    TX_POWER_FIELD_NUMBER: builtins.int
    interval: builtins.int
    """Advertising interval"""
    duration: builtins.int
    """Advertising duration"""
    type: builtins.int
    """Advertising type"""
    filter_policy: builtins.int
    """Advertising filter policy"""
    tx_power: builtins.int
    """Advertising tx power"""
    def __init__(
        self,
        *,
        interval: builtins.int = ...,
        duration: builtins.int = ...,
        type: builtins.int = ...,
        filter_policy: builtins.int = ...,
        tx_power: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["duration", b"duration", "filter_policy", b"filter_policy", "interval", b"interval", "tx_power", b"tx_power", "type", b"type"]) -> None: ...

global___BleAdvCfg = BleAdvCfg

@typing.final
class BleAdvStatus(google.protobuf.message.Message):
    """Ble adv status"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    STATE_FIELD_NUMBER: builtins.int
    ERR_CODE_FIELD_NUMBER: builtins.int
    state: global___BleAdvState.ValueType
    err_code: builtins.int
    def __init__(
        self,
        *,
        state: global___BleAdvState.ValueType = ...,
        err_code: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["err_code", b"err_code", "state", b"state"]) -> None: ...

global___BleAdvStatus = BleAdvStatus

@typing.final
class BleAdvReq(google.protobuf.message.Message):
    """Ble adv request"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___BleAdvReq = BleAdvReq

@typing.final
class BleAdvData(google.protobuf.message.Message):
    """Ble adv data"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    STOP_FIELD_NUMBER: builtins.int
    CONFIG_FIELD_NUMBER: builtins.int
    STATUS_FIELD_NUMBER: builtins.int
    REQUEST_FIELD_NUMBER: builtins.int
    @property
    def stop(self) -> global___BleAdvStop:
        """Stop BLE adv interface."""

    @property
    def config(self) -> global___BleAdvCfg:
        """BLE adv interface configuration."""

    @property
    def status(self) -> global___BleAdvStatus:
        """BLE adv interface status."""

    @property
    def request(self) -> global___BleAdvReq:
        """BLE adv interface request data."""

    def __init__(
        self,
        *,
        stop: global___BleAdvStop | None = ...,
        config: global___BleAdvCfg | None = ...,
        status: global___BleAdvStatus | None = ...,
        request: global___BleAdvReq | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["config", b"config", "request", b"request", "status", b"status", "stop", b"stop", "type", b"type"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["config", b"config", "request", b"request", "status", b"status", "stop", b"stop", "type", b"type"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["type", b"type"]) -> typing.Literal["stop", "config", "status", "request"] | None: ...

global___BleAdvData = BleAdvData
