# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ciot/proto/v2/ciot.proto
# Protobuf Python Version: 6.30.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    0,
    '',
    'ciot/proto/v2/ciot.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ciot.proto.v2 import iface_pb2 as ciot_dot_proto_dot_v2_dot_iface__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18\x63iot/proto/v2/ciot.proto\x12\x04\x43iot\x1a\x19\x63iot/proto/v2/iface.proto\"8\n\x04Info\x12\x0f\n\x07version\x18\x01 \x01(\x0c\x12\x1f\n\x06ifaces\x18\x02 \x03(\x0e\x32\x0f.Ciot.IfaceType\"G\n\x06Status\x12\x1a\n\x05state\x18\x01 \x01(\x0e\x32\x0b.Ciot.State\x12!\n\x06ifaces\x18\x02 \x03(\x0b\x32\x11.Ciot.IfaceStatus\"M\n\x0bIfaceStatus\x12\x1d\n\x04type\x18\x01 \x01(\x0e\x32\x0f.Ciot.IfaceType\x12\x1f\n\x05state\x18\x02 \x01(\x0e\x32\x10.Ciot.IfaceState\"Y\n\x03Req\x12#\n\x08save_cfg\x18\x01 \x01(\x0b\x32\x0f.Ciot.IfaceInfoH\x00\x12%\n\ndelete_cfg\x18\x02 \x01(\x0b\x32\x0f.Ciot.IfaceInfoH\x00\x42\x06\n\x04type\"h\n\x04\x44\x61ta\x12\x1e\n\x06status\x18\x02 \x01(\x0b\x32\x0c.Ciot.StatusH\x00\x12\x1c\n\x07request\x18\x03 \x01(\x0b\x32\t.Ciot.ReqH\x00\x12\x1a\n\x04info\x18\x06 \x01(\x0b\x32\n.Ciot.InfoH\x00\x42\x06\n\x04type*x\n\x05State\x12\x0e\n\nSTATE_IDLE\x10\x00\x12\x11\n\rSTATE_STARTED\x10\x01\x12\x12\n\x0eSTATE_STARTING\x10\x02\x12\x0e\n\nSTATE_BUSY\x10\x03\x12\x17\n\x13STATE_PENDING_EVENT\x10\x04\x12\x0f\n\x0bSTATE_ERROR\x10\x05*/\n\x11SerializationType\x12\x1a\n\x16SERIALIZATION_PROTOBUF\x10\x00\x42\x11\xaa\x02\x0e\x43iot.Protos.V2b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ciot.proto.v2.ciot_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002\016Ciot.Protos.V2'
  _globals['_STATE']._serialized_start=468
  _globals['_STATE']._serialized_end=588
  _globals['_SERIALIZATIONTYPE']._serialized_start=590
  _globals['_SERIALIZATIONTYPE']._serialized_end=637
  _globals['_INFO']._serialized_start=61
  _globals['_INFO']._serialized_end=117
  _globals['_STATUS']._serialized_start=119
  _globals['_STATUS']._serialized_end=190
  _globals['_IFACESTATUS']._serialized_start=192
  _globals['_IFACESTATUS']._serialized_end=269
  _globals['_REQ']._serialized_start=271
  _globals['_REQ']._serialized_end=360
  _globals['_DATA']._serialized_start=362
  _globals['_DATA']._serialized_end=466
# @@protoc_insertion_point(module_scope)
