"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import ciot.proto.v2.iface_pb2
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _State:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _StateEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_State.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    STATE_IDLE: _State.ValueType  # 0
    """CIOT core is in an idle state."""
    STATE_STARTED: _State.ValueType  # 1
    """CIOT core is started."""
    STATE_STARTING: _State.ValueType  # 2
    """CIOT core is starting."""
    STATE_BUSY: _State.ValueType  # 3
    """CIOT core is busy."""
    STATE_PENDING_EVENT: _State.ValueType  # 4
    """CIOT core has an event pending."""
    STATE_ERROR: _State.ValueType  # 5
    """CIOT core encountered an error."""

class State(_State, metaclass=_StateEnumTypeWrapper):
    """Enum representing the state of CIOT."""

STATE_IDLE: State.ValueType  # 0
"""CIOT core is in an idle state."""
STATE_STARTED: State.ValueType  # 1
"""CIOT core is started."""
STATE_STARTING: State.ValueType  # 2
"""CIOT core is starting."""
STATE_BUSY: State.ValueType  # 3
"""CIOT core is busy."""
STATE_PENDING_EVENT: State.ValueType  # 4
"""CIOT core has an event pending."""
STATE_ERROR: State.ValueType  # 5
"""CIOT core encountered an error."""
global___State = State

class _SerializationType:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _SerializationTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_SerializationType.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    SERIALIZATION_PROTOBUF: _SerializationType.ValueType  # 0
    """Protocol Buffers serialization type."""

class SerializationType(_SerializationType, metaclass=_SerializationTypeEnumTypeWrapper):
    """Enum representing different serialization types for CIOT."""

SERIALIZATION_PROTOBUF: SerializationType.ValueType  # 0
"""Protocol Buffers serialization type."""
global___SerializationType = SerializationType

@typing.final
class Info(google.protobuf.message.Message):
    """Message representing CIOT information."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    VERSION_FIELD_NUMBER: builtins.int
    IFACES_FIELD_NUMBER: builtins.int
    version: builtins.bytes
    """CIOT library version"""
    @property
    def ifaces(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[ciot.proto.v2.iface_pb2.IfaceType.ValueType]:
        """CIOT ifaces types list"""

    def __init__(
        self,
        *,
        version: builtins.bytes = ...,
        ifaces: collections.abc.Iterable[ciot.proto.v2.iface_pb2.IfaceType.ValueType] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["ifaces", b"ifaces", "version", b"version"]) -> None: ...

global___Info = Info

@typing.final
class Status(google.protobuf.message.Message):
    """Message representing CIOT status."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    STATE_FIELD_NUMBER: builtins.int
    IFACES_FIELD_NUMBER: builtins.int
    state: global___State.ValueType
    """State of the CIOT device."""
    @property
    def ifaces(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___IfaceStatus]:
        """Status of each CIOT iface."""

    def __init__(
        self,
        *,
        state: global___State.ValueType = ...,
        ifaces: collections.abc.Iterable[global___IfaceStatus] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["ifaces", b"ifaces", "state", b"state"]) -> None: ...

global___Status = Status

@typing.final
class IfaceStatus(google.protobuf.message.Message):
    """Message representing an CIOT iface status."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TYPE_FIELD_NUMBER: builtins.int
    STATE_FIELD_NUMBER: builtins.int
    type: ciot.proto.v2.iface_pb2.IfaceType.ValueType
    """Iface type"""
    state: ciot.proto.v2.iface_pb2.IfaceState.ValueType
    """Iface state"""
    def __init__(
        self,
        *,
        type: ciot.proto.v2.iface_pb2.IfaceType.ValueType = ...,
        state: ciot.proto.v2.iface_pb2.IfaceState.ValueType = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["state", b"state", "type", b"type"]) -> None: ...

global___IfaceStatus = IfaceStatus

@typing.final
class Req(google.protobuf.message.Message):
    """Message representing a CIOT request."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SAVE_CFG_FIELD_NUMBER: builtins.int
    DELETE_CFG_FIELD_NUMBER: builtins.int
    @property
    def save_cfg(self) -> ciot.proto.v2.iface_pb2.IfaceInfo:
        """Save interface configuration"""

    @property
    def delete_cfg(self) -> ciot.proto.v2.iface_pb2.IfaceInfo:
        """Delete interface configuration"""

    def __init__(
        self,
        *,
        save_cfg: ciot.proto.v2.iface_pb2.IfaceInfo | None = ...,
        delete_cfg: ciot.proto.v2.iface_pb2.IfaceInfo | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["delete_cfg", b"delete_cfg", "save_cfg", b"save_cfg", "type", b"type"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["delete_cfg", b"delete_cfg", "save_cfg", b"save_cfg", "type", b"type"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["type", b"type"]) -> typing.Literal["save_cfg", "delete_cfg"] | None: ...

global___Req = Req

@typing.final
class Data(google.protobuf.message.Message):
    """Message representing CIOT data."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    STATUS_FIELD_NUMBER: builtins.int
    REQUEST_FIELD_NUMBER: builtins.int
    INFO_FIELD_NUMBER: builtins.int
    @property
    def status(self) -> global___Status:
        """Status of the CIOT device."""

    @property
    def request(self) -> global___Req:
        """CIOT request data."""

    @property
    def info(self) -> global___Info:
        """Additional information about the CIOT device."""

    def __init__(
        self,
        *,
        status: global___Status | None = ...,
        request: global___Req | None = ...,
        info: global___Info | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["info", b"info", "request", b"request", "status", b"status", "type", b"type"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["info", b"info", "request", b"request", "status", b"status", "type", b"type"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["type", b"type"]) -> typing.Literal["status", "request", "info"] | None: ...

global___Data = Data
