"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import ciot.proto.v2.errors_pb2
import google.protobuf.descriptor
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _DfuState:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _DfuStateEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_DfuState.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    DFU_STATE_IDLE: _DfuState.ValueType  # 0
    """Idle state"""
    DFU_STATE_STARTING: _DfuState.ValueType  # 1
    """Dfu Starting"""
    DFU_STATE_STARTED: _DfuState.ValueType  # 2
    """Dfu Interrface started"""
    DFU_STATE_IN_PROGRESS: _DfuState.ValueType  # 3
    """Dfu in progress"""
    DFU_STATE_COMPLETED: _DfuState.ValueType  # 4
    """Dfu completed"""
    DFU_STATE_ERROR: _DfuState.ValueType  # 5
    """Dfu error"""

class DfuState(_DfuState, metaclass=_DfuStateEnumTypeWrapper):
    """Possible dfu states"""

DFU_STATE_IDLE: DfuState.ValueType  # 0
"""Idle state"""
DFU_STATE_STARTING: DfuState.ValueType  # 1
"""Dfu Starting"""
DFU_STATE_STARTED: DfuState.ValueType  # 2
"""Dfu Interrface started"""
DFU_STATE_IN_PROGRESS: DfuState.ValueType  # 3
"""Dfu in progress"""
DFU_STATE_COMPLETED: DfuState.ValueType  # 4
"""Dfu completed"""
DFU_STATE_ERROR: DfuState.ValueType  # 5
"""Dfu error"""
global___DfuState = DfuState

class _DfuType:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _DfuTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_DfuType.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    DFU_TYPE_UNKNOWN: _DfuType.ValueType  # 0
    """Unknown type"""
    DFU_TYPE_UART: _DfuType.ValueType  # 1
    """Dfu over uart"""
    DFU_TYPE_USB: _DfuType.ValueType  # 2
    """Dfu over USB"""
    DFU_TYPE_BLE: _DfuType.ValueType  # 3
    """Dfu over bluetooth low energy"""

class DfuType(_DfuType, metaclass=_DfuTypeEnumTypeWrapper):
    """Dfu types"""

DFU_TYPE_UNKNOWN: DfuType.ValueType  # 0
"""Unknown type"""
DFU_TYPE_UART: DfuType.ValueType  # 1
"""Dfu over uart"""
DFU_TYPE_USB: DfuType.ValueType  # 2
"""Dfu over USB"""
DFU_TYPE_BLE: DfuType.ValueType  # 3
"""Dfu over bluetooth low energy"""
global___DfuType = DfuType

@typing.final
class DfuStop(google.protobuf.message.Message):
    """Dfu stop message"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___DfuStop = DfuStop

@typing.final
class DfuCfg(google.protobuf.message.Message):
    """Dfu configuration"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TYPE_FIELD_NUMBER: builtins.int
    type: global___DfuType.ValueType
    """DFU type"""
    def __init__(
        self,
        *,
        type: global___DfuType.ValueType = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["type", b"type"]) -> None: ...

global___DfuCfg = DfuCfg

@typing.final
class DfuStatus(google.protobuf.message.Message):
    """Dfu status"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    STATE_FIELD_NUMBER: builtins.int
    CODE_FIELD_NUMBER: builtins.int
    ERROR_FIELD_NUMBER: builtins.int
    IMAGE_SIZE_FIELD_NUMBER: builtins.int
    IMAGE_WRITTEN_FIELD_NUMBER: builtins.int
    state: global___DfuState.ValueType
    """Dfu current state"""
    code: builtins.int
    """Dfu response/status code"""
    error: ciot.proto.v2.errors_pb2.Err.ValueType
    """Dfu error code"""
    image_size: builtins.int
    """Dfu image size"""
    image_written: builtins.int
    """Dfu image written on client"""
    def __init__(
        self,
        *,
        state: global___DfuState.ValueType = ...,
        code: builtins.int = ...,
        error: ciot.proto.v2.errors_pb2.Err.ValueType = ...,
        image_size: builtins.int = ...,
        image_written: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["code", b"code", "error", b"error", "image_size", b"image_size", "image_written", b"image_written", "state", b"state"]) -> None: ...

global___DfuStatus = DfuStatus

@typing.final
class DfuReq(google.protobuf.message.Message):
    """Dfu request"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___DfuReq = DfuReq

@typing.final
class DfuData(google.protobuf.message.Message):
    """Dfu data"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    STOP_FIELD_NUMBER: builtins.int
    CONFIG_FIELD_NUMBER: builtins.int
    STATUS_FIELD_NUMBER: builtins.int
    REQUEST_FIELD_NUMBER: builtins.int
    @property
    def stop(self) -> global___DfuStop:
        """Dfu stop"""

    @property
    def config(self) -> global___DfuCfg:
        """Dfu configuration data"""

    @property
    def status(self) -> global___DfuStatus:
        """Dfu status data"""

    @property
    def request(self) -> global___DfuReq:
        """Dfu request data"""

    def __init__(
        self,
        *,
        stop: global___DfuStop | None = ...,
        config: global___DfuCfg | None = ...,
        status: global___DfuStatus | None = ...,
        request: global___DfuReq | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["config", b"config", "request", b"request", "status", b"status", "stop", b"stop", "type", b"type"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["config", b"config", "request", b"request", "status", b"status", "stop", b"stop", "type", b"type"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["type", b"type"]) -> typing.Literal["stop", "config", "status", "request"] | None: ...

global___DfuData = DfuData
