# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ciot/proto/v2/dfu.proto
# Protobuf Python Version: 6.30.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    0,
    '',
    'ciot/proto/v2/dfu.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ciot.proto.v2 import errors_pb2 as ciot_dot_proto_dot_v2_dot_errors__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17\x63iot/proto/v2/dfu.proto\x12\x04\x43iot\x1a\x1a\x63iot/proto/v2/errors.proto\"\t\n\x07\x44\x66uStop\"%\n\x06\x44\x66uCfg\x12\x1b\n\x04type\x18\x01 \x01(\x0e\x32\r.Ciot.DfuType\"}\n\tDfuStatus\x12\x1d\n\x05state\x18\x01 \x01(\x0e\x32\x0e.Ciot.DfuState\x12\x0c\n\x04\x63ode\x18\x02 \x01(\r\x12\x18\n\x05\x65rror\x18\x03 \x01(\x0e\x32\t.Ciot.Err\x12\x12\n\nimage_size\x18\x04 \x01(\r\x12\x15\n\rimage_written\x18\x05 \x01(\r\"\x08\n\x06\x44\x66uReq\"\x94\x01\n\x07\x44\x66uData\x12\x1d\n\x04stop\x18\x01 \x01(\x0b\x32\r.Ciot.DfuStopH\x00\x12\x1e\n\x06\x63onfig\x18\x02 \x01(\x0b\x32\x0c.Ciot.DfuCfgH\x00\x12!\n\x06status\x18\x03 \x01(\x0b\x32\x0f.Ciot.DfuStatusH\x00\x12\x1f\n\x07request\x18\x04 \x01(\x0b\x32\x0c.Ciot.DfuReqH\x00\x42\x06\n\x04type*\x96\x01\n\x08\x44\x66uState\x12\x12\n\x0e\x44\x46U_STATE_IDLE\x10\x00\x12\x16\n\x12\x44\x46U_STATE_STARTING\x10\x01\x12\x15\n\x11\x44\x46U_STATE_STARTED\x10\x02\x12\x19\n\x15\x44\x46U_STATE_IN_PROGRESS\x10\x03\x12\x17\n\x13\x44\x46U_STATE_COMPLETED\x10\x04\x12\x13\n\x0f\x44\x46U_STATE_ERROR\x10\x05*V\n\x07\x44\x66uType\x12\x14\n\x10\x44\x46U_TYPE_UNKNOWN\x10\x00\x12\x11\n\rDFU_TYPE_UART\x10\x01\x12\x10\n\x0c\x44\x46U_TYPE_USB\x10\x02\x12\x10\n\x0c\x44\x46U_TYPE_BLE\x10\x03\x42\x11\xaa\x02\x0e\x43iot.Protos.V2b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ciot.proto.v2.dfu_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002\016Ciot.Protos.V2'
  _globals['_DFUSTATE']._serialized_start=400
  _globals['_DFUSTATE']._serialized_end=550
  _globals['_DFUTYPE']._serialized_start=552
  _globals['_DFUTYPE']._serialized_end=638
  _globals['_DFUSTOP']._serialized_start=61
  _globals['_DFUSTOP']._serialized_end=70
  _globals['_DFUCFG']._serialized_start=72
  _globals['_DFUCFG']._serialized_end=109
  _globals['_DFUSTATUS']._serialized_start=111
  _globals['_DFUSTATUS']._serialized_end=236
  _globals['_DFUREQ']._serialized_start=238
  _globals['_DFUREQ']._serialized_end=246
  _globals['_DFUDATA']._serialized_start=249
  _globals['_DFUDATA']._serialized_end=397
# @@protoc_insertion_point(module_scope)
