"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import google.protobuf.descriptor
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _Err:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _ErrEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_Err.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    ERR_OK: _Err.ValueType  # 0
    """No error"""
    ERR_NULL_ARG: _Err.ValueType  # 1
    """Null argunment"""
    ERR_INVALID_ID: _Err.ValueType  # 2
    """Invalid ID"""
    ERR_INVALID_TYPE: _Err.ValueType  # 3
    """Invalid Type"""
    ERR_OVERFLOW: _Err.ValueType  # 4
    """Memory overflow"""
    ERR_NOT_IMPLEMENTED: _Err.ValueType  # 5
    """Not implemented"""
    ERR_NOT_SUPPORTED: _Err.ValueType  # 6
    """Not supported"""
    ERR_BUSY: _Err.ValueType  # 7
    """Busy"""
    ERR_INVALID_STATE: _Err.ValueType  # 8
    """Invalid state"""
    ERR_SERIALIZATION: _Err.ValueType  # 9
    """Serialization error"""
    ERR_DESERIALIZATION: _Err.ValueType  # 10
    """Deserialization error"""
    ERR_SEND_DATA: _Err.ValueType  # 11
    """Error sending data"""
    ERR_RECV_DATA: _Err.ValueType  # 12
    """Error on data receive"""
    ERR_INVALID_SIZE: _Err.ValueType  # 13
    """Invalid size"""
    ERR_CLOSED: _Err.ValueType  # 14
    """Closed"""
    ERR_NOT_FOUND: _Err.ValueType  # 15
    """Resource not found"""
    ERR_VALIDATION_FAILED: _Err.ValueType  # 16
    """Validation failed"""
    ERR_CONNECTION: _Err.ValueType  # 17
    """Connection failed"""
    ERR_DISCONNECTION: _Err.ValueType  # 18
    """Disconnection failed"""
    ERR_EXCEPTION: _Err.ValueType  # 19
    """Unknown exception occours"""
    ERR_INVALID_ARG: _Err.ValueType  # 20
    """Invalid argument detected"""
    ERR_NO_MEMORY: _Err.ValueType  # 21
    """Insuficient memory"""
    ERR_TIMEOUT: _Err.ValueType  # 22
    """Timeout"""
    ERR_MONGOOSE: _Err.ValueType  # 23
    """Internal error on mongoose framework"""
    ERR_IMPOSSIBLE_OP: _Err.ValueType  # 24
    """Requested operation is impossible"""
    ERR_CHECKSUM: _Err.ValueType  # 25
    """Checksum validation error"""
    ERR_PROTOCOL_VIOLATION: _Err.ValueType  # 26
    """Protocol validation error"""
    ERR_DATA_LOSS: _Err.ValueType  # 27
    """Data loss"""
    ERR_INVALID_HEADER: _Err.ValueType  # 28
    """Invalid message header"""
    ERR_DISABLED: _Err.ValueType  # 29
    """Feature disabled"""
    ERR_FAIL: _Err.ValueType  # 30
    """Operation failed"""
    ERR_INVALID_INDEX: _Err.ValueType  # 31
    """Invalid index"""
    ERR_INVALID_KEY_SIZE: _Err.ValueType  # 32
    """Invalid key size"""
    ERR_FIFO_READ: _Err.ValueType  # 33
    """Error reading fifo data"""
    ERR_FIFO_WRITE: _Err.ValueType  # 34
    """Error writing data to fifo"""
    ERR_INVALID_ADDR: _Err.ValueType  # 35
    """Invalid address"""
    ERR_RESOURCES: _Err.ValueType  # 36
    """Not enough resources"""
    ERR_UNKNOWN: _Err.ValueType  # 37
    """Unknown error"""
    ERR_READING: _Err.ValueType  # 38
    """Reading error"""
    ERR_ERASING: _Err.ValueType  # 39
    """Erasing error"""
    ERR_WRITING: _Err.ValueType  # 40
    """Writing error"""
    ERR_INVALID_NAME: _Err.ValueType  # 41
    """Invalid name error"""
    ERR_DECODER_MISSING: _Err.ValueType  # 42
    """Decoder is missing"""
    ERR_SERIALIZER_MISSING: _Err.ValueType  # 43
    """Serializer is missing"""
    ERR_SMALL_RAW: _Err.ValueType  # 44
    """Data size is greater than raw bytes array"""
    ERR_INVALID_REQUEST: _Err.ValueType  # 45
    """Invalid request received"""
    ERR_INVALID_TCP_MBAP: _Err.ValueType  # 47
    """Invalid TCP MBAP"""
    ERR_CRC: _Err.ValueType  # 48
    """Invalid CRC"""
    ERR_TRANSPORT: _Err.ValueType  # 49
    """Transport error"""
    ERR_INVALID_RESPONSE: _Err.ValueType  # 50
    """Invalid response received"""
    ERR_NULL_EVENT_HANDLER: _Err.ValueType  # 51
    """Null iface event handler"""
    ERR_DEPRECATED: _Err.ValueType  # 52
    """Deprecated feature"""
    ERR_MBUS_EXCEPTION_ILLEGAL_FUNCTION: _Err.ValueType  # 101
    """Modbus exception 1"""
    ERR_MBUS_EXCEPTION_ILLEGAL_DATA_ADDR: _Err.ValueType  # 102
    """Modbus exception 2"""
    ERR_MBUS_EXCEPTION_ILLEGAL_DATA_VAL: _Err.ValueType  # 103
    """Modbus exception 3"""
    ERR_MBUS_EXCEPTION_SERVER_DEVICE_FAILURE: _Err.ValueType  # 104
    """Modbus exception 4"""

class Err(_Err, metaclass=_ErrEnumTypeWrapper):
    """Error codes"""

ERR_OK: Err.ValueType  # 0
"""No error"""
ERR_NULL_ARG: Err.ValueType  # 1
"""Null argunment"""
ERR_INVALID_ID: Err.ValueType  # 2
"""Invalid ID"""
ERR_INVALID_TYPE: Err.ValueType  # 3
"""Invalid Type"""
ERR_OVERFLOW: Err.ValueType  # 4
"""Memory overflow"""
ERR_NOT_IMPLEMENTED: Err.ValueType  # 5
"""Not implemented"""
ERR_NOT_SUPPORTED: Err.ValueType  # 6
"""Not supported"""
ERR_BUSY: Err.ValueType  # 7
"""Busy"""
ERR_INVALID_STATE: Err.ValueType  # 8
"""Invalid state"""
ERR_SERIALIZATION: Err.ValueType  # 9
"""Serialization error"""
ERR_DESERIALIZATION: Err.ValueType  # 10
"""Deserialization error"""
ERR_SEND_DATA: Err.ValueType  # 11
"""Error sending data"""
ERR_RECV_DATA: Err.ValueType  # 12
"""Error on data receive"""
ERR_INVALID_SIZE: Err.ValueType  # 13
"""Invalid size"""
ERR_CLOSED: Err.ValueType  # 14
"""Closed"""
ERR_NOT_FOUND: Err.ValueType  # 15
"""Resource not found"""
ERR_VALIDATION_FAILED: Err.ValueType  # 16
"""Validation failed"""
ERR_CONNECTION: Err.ValueType  # 17
"""Connection failed"""
ERR_DISCONNECTION: Err.ValueType  # 18
"""Disconnection failed"""
ERR_EXCEPTION: Err.ValueType  # 19
"""Unknown exception occours"""
ERR_INVALID_ARG: Err.ValueType  # 20
"""Invalid argument detected"""
ERR_NO_MEMORY: Err.ValueType  # 21
"""Insuficient memory"""
ERR_TIMEOUT: Err.ValueType  # 22
"""Timeout"""
ERR_MONGOOSE: Err.ValueType  # 23
"""Internal error on mongoose framework"""
ERR_IMPOSSIBLE_OP: Err.ValueType  # 24
"""Requested operation is impossible"""
ERR_CHECKSUM: Err.ValueType  # 25
"""Checksum validation error"""
ERR_PROTOCOL_VIOLATION: Err.ValueType  # 26
"""Protocol validation error"""
ERR_DATA_LOSS: Err.ValueType  # 27
"""Data loss"""
ERR_INVALID_HEADER: Err.ValueType  # 28
"""Invalid message header"""
ERR_DISABLED: Err.ValueType  # 29
"""Feature disabled"""
ERR_FAIL: Err.ValueType  # 30
"""Operation failed"""
ERR_INVALID_INDEX: Err.ValueType  # 31
"""Invalid index"""
ERR_INVALID_KEY_SIZE: Err.ValueType  # 32
"""Invalid key size"""
ERR_FIFO_READ: Err.ValueType  # 33
"""Error reading fifo data"""
ERR_FIFO_WRITE: Err.ValueType  # 34
"""Error writing data to fifo"""
ERR_INVALID_ADDR: Err.ValueType  # 35
"""Invalid address"""
ERR_RESOURCES: Err.ValueType  # 36
"""Not enough resources"""
ERR_UNKNOWN: Err.ValueType  # 37
"""Unknown error"""
ERR_READING: Err.ValueType  # 38
"""Reading error"""
ERR_ERASING: Err.ValueType  # 39
"""Erasing error"""
ERR_WRITING: Err.ValueType  # 40
"""Writing error"""
ERR_INVALID_NAME: Err.ValueType  # 41
"""Invalid name error"""
ERR_DECODER_MISSING: Err.ValueType  # 42
"""Decoder is missing"""
ERR_SERIALIZER_MISSING: Err.ValueType  # 43
"""Serializer is missing"""
ERR_SMALL_RAW: Err.ValueType  # 44
"""Data size is greater than raw bytes array"""
ERR_INVALID_REQUEST: Err.ValueType  # 45
"""Invalid request received"""
ERR_INVALID_TCP_MBAP: Err.ValueType  # 47
"""Invalid TCP MBAP"""
ERR_CRC: Err.ValueType  # 48
"""Invalid CRC"""
ERR_TRANSPORT: Err.ValueType  # 49
"""Transport error"""
ERR_INVALID_RESPONSE: Err.ValueType  # 50
"""Invalid response received"""
ERR_NULL_EVENT_HANDLER: Err.ValueType  # 51
"""Null iface event handler"""
ERR_DEPRECATED: Err.ValueType  # 52
"""Deprecated feature"""
ERR_MBUS_EXCEPTION_ILLEGAL_FUNCTION: Err.ValueType  # 101
"""Modbus exception 1"""
ERR_MBUS_EXCEPTION_ILLEGAL_DATA_ADDR: Err.ValueType  # 102
"""Modbus exception 2"""
ERR_MBUS_EXCEPTION_ILLEGAL_DATA_VAL: Err.ValueType  # 103
"""Modbus exception 3"""
ERR_MBUS_EXCEPTION_SERVER_DEVICE_FAILURE: Err.ValueType  # 104
"""Modbus exception 4"""
global___Err = Err

@typing.final
class ErrData(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ERR_FIELD_NUMBER: builtins.int
    err: global___Err.ValueType
    def __init__(
        self,
        *,
        err: global___Err.ValueType = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["err", b"err"]) -> None: ...

global___ErrData = ErrData
