# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ciot/proto/v2/event.proto
# Protobuf Python Version: 6.30.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    0,
    '',
    'ciot/proto/v2/event.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ciot.proto.v2 import msg_pb2 as ciot_dot_proto_dot_v2_dot_msg__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19\x63iot/proto/v2/event.proto\x12\x04\x43iot\x1a\x17\x63iot/proto/v2/msg.proto\"+\n\rEventInternal\x12\x0c\n\x04type\x18\x01 \x01(\x05\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\"\x80\x01\n\x05\x45vent\x12\x1d\n\x04type\x18\x01 \x01(\x0e\x32\x0f.Ciot.EventType\x12\x18\n\x03msg\x18\x02 \x01(\x0b\x32\t.Ciot.MsgH\x00\x12\r\n\x03raw\x18\x03 \x01(\x0cH\x00\x12\'\n\x08internal\x18\x04 \x01(\x0b\x32\x13.Ciot.EventInternalH\x00\x42\x06\n\x04\x64\x61ta*\xf5\x01\n\tEventType\x12\x16\n\x12\x45VENT_TYPE_UNKNOWN\x10\x00\x12\x13\n\x0f\x45VENT_TYPE_DATA\x10\x01\x12\x16\n\x12\x45VENT_TYPE_STARTED\x10\x02\x12\x16\n\x12\x45VENT_TYPE_STOPPED\x10\x03\x12\x14\n\x10\x45VENT_TYPE_ERROR\x10\x04\x12\x12\n\x0e\x45VENT_TYPE_MSG\x10\x05\x12\x13\n\x0f\x45VENT_TYPE_DONE\x10\x06\x12\x1c\n\x18\x45VENT_TYPE_STATE_CHANGED\x10\x07\x12\x17\n\x13\x45VENT_TYPE_INTERNAL\x10\x08\x12\x15\n\x11\x45VENT_TYPE_CUSTOM\x10\tB\x11\xaa\x02\x0e\x43iot.Protos.V2b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ciot.proto.v2.event_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002\016Ciot.Protos.V2'
  _globals['_EVENTTYPE']._serialized_start=237
  _globals['_EVENTTYPE']._serialized_end=482
  _globals['_EVENTINTERNAL']._serialized_start=60
  _globals['_EVENTINTERNAL']._serialized_end=103
  _globals['_EVENT']._serialized_start=106
  _globals['_EVENT']._serialized_end=234
# @@protoc_insertion_point(module_scope)
