"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import ciot.proto.v2.msg_pb2
import google.protobuf.descriptor
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _EventType:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _EventTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_EventType.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    EVENT_TYPE_UNKNOWN: _EventType.ValueType  # 0
    """Unknown event type"""
    EVENT_TYPE_DATA: _EventType.ValueType  # 1
    """Event data"""
    EVENT_TYPE_STARTED: _EventType.ValueType  # 2
    """Event interface started"""
    EVENT_TYPE_STOPPED: _EventType.ValueType  # 3
    """Event interface stopped"""
    EVENT_TYPE_ERROR: _EventType.ValueType  # 4
    """Event error"""
    EVENT_TYPE_MSG: _EventType.ValueType  # 5
    """Event message"""
    EVENT_TYPE_DONE: _EventType.ValueType  # 6
    """Event request done"""
    EVENT_TYPE_STATE_CHANGED: _EventType.ValueType  # 7
    """Event interface state changed"""
    EVENT_TYPE_INTERNAL: _EventType.ValueType  # 8
    """Event internal"""
    EVENT_TYPE_CUSTOM: _EventType.ValueType  # 9
    """Event custom"""

class EventType(_EventType, metaclass=_EventTypeEnumTypeWrapper):
    """Enum representing different event types"""

EVENT_TYPE_UNKNOWN: EventType.ValueType  # 0
"""Unknown event type"""
EVENT_TYPE_DATA: EventType.ValueType  # 1
"""Event data"""
EVENT_TYPE_STARTED: EventType.ValueType  # 2
"""Event interface started"""
EVENT_TYPE_STOPPED: EventType.ValueType  # 3
"""Event interface stopped"""
EVENT_TYPE_ERROR: EventType.ValueType  # 4
"""Event error"""
EVENT_TYPE_MSG: EventType.ValueType  # 5
"""Event message"""
EVENT_TYPE_DONE: EventType.ValueType  # 6
"""Event request done"""
EVENT_TYPE_STATE_CHANGED: EventType.ValueType  # 7
"""Event interface state changed"""
EVENT_TYPE_INTERNAL: EventType.ValueType  # 8
"""Event internal"""
EVENT_TYPE_CUSTOM: EventType.ValueType  # 9
"""Event custom"""
global___EventType = EventType

@typing.final
class EventInternal(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TYPE_FIELD_NUMBER: builtins.int
    DATA_FIELD_NUMBER: builtins.int
    type: builtins.int
    """Internal event type"""
    data: builtins.bytes
    """Internal event data"""
    def __init__(
        self,
        *,
        type: builtins.int = ...,
        data: builtins.bytes = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["data", b"data", "type", b"type"]) -> None: ...

global___EventInternal = EventInternal

@typing.final
class Event(google.protobuf.message.Message):
    """Message representing an CIoT event"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TYPE_FIELD_NUMBER: builtins.int
    MSG_FIELD_NUMBER: builtins.int
    RAW_FIELD_NUMBER: builtins.int
    INTERNAL_FIELD_NUMBER: builtins.int
    type: global___EventType.ValueType
    """Event type"""
    raw: builtins.bytes
    """Event raw data"""
    @property
    def msg(self) -> ciot.proto.v2.msg_pb2.Msg:
        """Event message"""

    @property
    def internal(self) -> global___EventInternal:
        """Event internal"""

    def __init__(
        self,
        *,
        type: global___EventType.ValueType = ...,
        msg: ciot.proto.v2.msg_pb2.Msg | None = ...,
        raw: builtins.bytes = ...,
        internal: global___EventInternal | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["data", b"data", "internal", b"internal", "msg", b"msg", "raw", b"raw"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["data", b"data", "internal", b"internal", "msg", b"msg", "raw", b"raw", "type", b"type"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["data", b"data"]) -> typing.Literal["msg", "raw", "internal"] | None: ...

global___Event = Event
