# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ciot/proto/v2/gpio.proto
# Protobuf Python Version: 6.30.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    0,
    '',
    'ciot/proto/v2/gpio.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18\x63iot/proto/v2/gpio.proto\x12\x04\x43iot\"&\n\x08GpioStop\x12\x1a\n\x03\x63\x66g\x18\x01 \x01(\x0b\x32\r.Ciot.GpioCfg\"U\n\nGpioPinCfg\x12\x0b\n\x03num\x18\x01 \x01(\r\x12\x1c\n\x04mode\x18\x02 \x01(\x0e\x32\x0e.Ciot.GpioMode\x12\x1c\n\x04pull\x18\x03 \x01(\x0e\x32\x0e.Ciot.GpioPull\"A\n\x07GpioCfg\x12\x1e\n\x04pins\x18\x01 \x03(\x0b\x32\x10.Ciot.GpioPinCfg\x12\x16\n\x0e\x62link_interval\x18\x02 \x01(\r\"\x1c\n\nGpioStatus\x12\x0e\n\x06states\x18\x01 \x01(\x0c\"<\n\rGpioStateInfo\x12\x0b\n\x03num\x18\x01 \x01(\r\x12\x1e\n\x05state\x18\x02 \x01(\x0e\x32\x0f.Ciot.GpioState\"c\n\x07GpioReq\x12&\n\nset_status\x18\x01 \x01(\x0b\x32\x10.Ciot.GpioStatusH\x00\x12(\n\tset_state\x18\x02 \x01(\x0b\x32\x13.Ciot.GpioStateInfoH\x00\x42\x06\n\x04type\"\x99\x01\n\x08GpioData\x12\x1e\n\x04stop\x18\x01 \x01(\x0b\x32\x0e.Ciot.GpioStopH\x00\x12\x1f\n\x06\x63onfig\x18\x02 \x01(\x0b\x32\r.Ciot.GpioCfgH\x00\x12\"\n\x06status\x18\x03 \x01(\x0b\x32\x10.Ciot.GpioStatusH\x00\x12 \n\x07request\x18\x04 \x01(\x0b\x32\r.Ciot.GpioReqH\x00\x42\x06\n\x04type*\x91\x01\n\tGpioState\x12\x12\n\x0eGPIO_STATE_LOW\x10\x00\x12\x13\n\x0fGPIO_STATE_HIGH\x10\x01\x12\x14\n\x10GPIO_STATE_BLINK\x10\x02\x12\x16\n\x12GPIO_STATE_BLINKED\x10\x03\x12\x17\n\x13GPIO_STATE_BLINKING\x10\x04\x12\x14\n\x10GPIO_STATE_ERROR\x10\x05*M\n\x08GpioMode\x12\x16\n\x12GPIO_MODE_DISABLED\x10\x00\x12\x13\n\x0fGPIO_MODE_INPUT\x10\x01\x12\x14\n\x10GPIO_MODE_OUTPUT\x10\x02*H\n\x08GpioPull\x12\x16\n\x12GPIO_PULL_DISABLED\x10\x00\x12\x10\n\x0cGPIO_PULL_UP\x10\x01\x12\x12\n\x0eGPIO_PULL_DOWN\x10\x02\x42\x11\xaa\x02\x0e\x43iot.Protos.V2b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ciot.proto.v2.gpio_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002\016Ciot.Protos.V2'
  _globals['_GPIOSTATE']._serialized_start=578
  _globals['_GPIOSTATE']._serialized_end=723
  _globals['_GPIOMODE']._serialized_start=725
  _globals['_GPIOMODE']._serialized_end=802
  _globals['_GPIOPULL']._serialized_start=804
  _globals['_GPIOPULL']._serialized_end=876
  _globals['_GPIOSTOP']._serialized_start=34
  _globals['_GPIOSTOP']._serialized_end=72
  _globals['_GPIOPINCFG']._serialized_start=74
  _globals['_GPIOPINCFG']._serialized_end=159
  _globals['_GPIOCFG']._serialized_start=161
  _globals['_GPIOCFG']._serialized_end=226
  _globals['_GPIOSTATUS']._serialized_start=228
  _globals['_GPIOSTATUS']._serialized_end=256
  _globals['_GPIOSTATEINFO']._serialized_start=258
  _globals['_GPIOSTATEINFO']._serialized_end=318
  _globals['_GPIOREQ']._serialized_start=320
  _globals['_GPIOREQ']._serialized_end=419
  _globals['_GPIODATA']._serialized_start=422
  _globals['_GPIODATA']._serialized_end=575
# @@protoc_insertion_point(module_scope)
