"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _GpioState:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _GpioStateEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_GpioState.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    GPIO_STATE_LOW: _GpioState.ValueType  # 0
    """Gpio is low"""
    GPIO_STATE_HIGH: _GpioState.ValueType  # 1
    """Gpio is high"""
    GPIO_STATE_BLINK: _GpioState.ValueType  # 2
    """Gpio is alternating it state once"""
    GPIO_STATE_BLINKED: _GpioState.ValueType  # 3
    """Gpio alternated it state once"""
    GPIO_STATE_BLINKING: _GpioState.ValueType  # 4
    """Gpio is alternating it state"""
    GPIO_STATE_ERROR: _GpioState.ValueType  # 5
    """Gpio is in error"""

class GpioState(_GpioState, metaclass=_GpioStateEnumTypeWrapper):
    """Enum representing the state of gpio"""

GPIO_STATE_LOW: GpioState.ValueType  # 0
"""Gpio is low"""
GPIO_STATE_HIGH: GpioState.ValueType  # 1
"""Gpio is high"""
GPIO_STATE_BLINK: GpioState.ValueType  # 2
"""Gpio is alternating it state once"""
GPIO_STATE_BLINKED: GpioState.ValueType  # 3
"""Gpio alternated it state once"""
GPIO_STATE_BLINKING: GpioState.ValueType  # 4
"""Gpio is alternating it state"""
GPIO_STATE_ERROR: GpioState.ValueType  # 5
"""Gpio is in error"""
global___GpioState = GpioState

class _GpioMode:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _GpioModeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_GpioMode.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    GPIO_MODE_DISABLED: _GpioMode.ValueType  # 0
    """Disable gpio"""
    GPIO_MODE_INPUT: _GpioMode.ValueType  # 1
    """Enable gpio input mode"""
    GPIO_MODE_OUTPUT: _GpioMode.ValueType  # 2
    """Enable gpio output mode"""

class GpioMode(_GpioMode, metaclass=_GpioModeEnumTypeWrapper):
    """Enum representing gpio modes"""

GPIO_MODE_DISABLED: GpioMode.ValueType  # 0
"""Disable gpio"""
GPIO_MODE_INPUT: GpioMode.ValueType  # 1
"""Enable gpio input mode"""
GPIO_MODE_OUTPUT: GpioMode.ValueType  # 2
"""Enable gpio output mode"""
global___GpioMode = GpioMode

class _GpioPull:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _GpioPullEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_GpioPull.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    GPIO_PULL_DISABLED: _GpioPull.ValueType  # 0
    """Disable gpio internal pullup/pulldown"""
    GPIO_PULL_UP: _GpioPull.ValueType  # 1
    """Enable gpio internal pullup"""
    GPIO_PULL_DOWN: _GpioPull.ValueType  # 2
    """Enable gpio internal pulldown"""

class GpioPull(_GpioPull, metaclass=_GpioPullEnumTypeWrapper):
    """Enum representing gpio internal pullup/pulldown modes"""

GPIO_PULL_DISABLED: GpioPull.ValueType  # 0
"""Disable gpio internal pullup/pulldown"""
GPIO_PULL_UP: GpioPull.ValueType  # 1
"""Enable gpio internal pullup"""
GPIO_PULL_DOWN: GpioPull.ValueType  # 2
"""Enable gpio internal pulldown"""
global___GpioPull = GpioPull

@typing.final
class GpioStop(google.protobuf.message.Message):
    """Gpio stop message"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CFG_FIELD_NUMBER: builtins.int
    @property
    def cfg(self) -> global___GpioCfg:
        """Config of gpio to be stopped"""

    def __init__(
        self,
        *,
        cfg: global___GpioCfg | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["cfg", b"cfg"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["cfg", b"cfg"]) -> None: ...

global___GpioStop = GpioStop

@typing.final
class GpioPinCfg(google.protobuf.message.Message):
    """Gpio pin configuration"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NUM_FIELD_NUMBER: builtins.int
    MODE_FIELD_NUMBER: builtins.int
    PULL_FIELD_NUMBER: builtins.int
    num: builtins.int
    """Gpio pin number"""
    mode: global___GpioMode.ValueType
    """Gpio mode"""
    pull: global___GpioPull.ValueType
    """Gpio pullup/pulldown configuration"""
    def __init__(
        self,
        *,
        num: builtins.int = ...,
        mode: global___GpioMode.ValueType = ...,
        pull: global___GpioPull.ValueType = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["mode", b"mode", "num", b"num", "pull", b"pull"]) -> None: ...

global___GpioPinCfg = GpioPinCfg

@typing.final
class GpioCfg(google.protobuf.message.Message):
    """Message representing gpio configuration"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PINS_FIELD_NUMBER: builtins.int
    BLINK_INTERVAL_FIELD_NUMBER: builtins.int
    blink_interval: builtins.int
    """Interval between gpio blinks in miliseconds"""
    @property
    def pins(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___GpioPinCfg]:
        """Pins list configuration"""

    def __init__(
        self,
        *,
        pins: collections.abc.Iterable[global___GpioPinCfg] | None = ...,
        blink_interval: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["blink_interval", b"blink_interval", "pins", b"pins"]) -> None: ...

global___GpioCfg = GpioCfg

@typing.final
class GpioStatus(google.protobuf.message.Message):
    """Message used to read/set all gpio states"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    STATES_FIELD_NUMBER: builtins.int
    states: builtins.bytes
    """Gpio states list"""
    def __init__(
        self,
        *,
        states: builtins.bytes = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["states", b"states"]) -> None: ...

global___GpioStatus = GpioStatus

@typing.final
class GpioStateInfo(google.protobuf.message.Message):
    """Message used to set/read signle gpio state info"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NUM_FIELD_NUMBER: builtins.int
    STATE_FIELD_NUMBER: builtins.int
    num: builtins.int
    """Gpio num"""
    state: global___GpioState.ValueType
    """Gpio state"""
    def __init__(
        self,
        *,
        num: builtins.int = ...,
        state: global___GpioState.ValueType = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["num", b"num", "state", b"state"]) -> None: ...

global___GpioStateInfo = GpioStateInfo

@typing.final
class GpioReq(google.protobuf.message.Message):
    """Message representing an gpio request"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SET_STATUS_FIELD_NUMBER: builtins.int
    SET_STATE_FIELD_NUMBER: builtins.int
    @property
    def set_status(self) -> global___GpioStatus:
        """Set Status request."""

    @property
    def set_state(self) -> global___GpioStateInfo:
        """Set sate request"""

    def __init__(
        self,
        *,
        set_status: global___GpioStatus | None = ...,
        set_state: global___GpioStateInfo | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["set_state", b"set_state", "set_status", b"set_status", "type", b"type"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["set_state", b"set_state", "set_status", b"set_status", "type", b"type"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["type", b"type"]) -> typing.Literal["set_status", "set_state"] | None: ...

global___GpioReq = GpioReq

@typing.final
class GpioData(google.protobuf.message.Message):
    """Message representing gpio data"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    STOP_FIELD_NUMBER: builtins.int
    CONFIG_FIELD_NUMBER: builtins.int
    STATUS_FIELD_NUMBER: builtins.int
    REQUEST_FIELD_NUMBER: builtins.int
    @property
    def stop(self) -> global___GpioStop:
        """Stop gpio"""

    @property
    def config(self) -> global___GpioCfg:
        """Configuration data"""

    @property
    def status(self) -> global___GpioStatus:
        """Status data"""

    @property
    def request(self) -> global___GpioReq:
        """Request data"""

    def __init__(
        self,
        *,
        stop: global___GpioStop | None = ...,
        config: global___GpioCfg | None = ...,
        status: global___GpioStatus | None = ...,
        request: global___GpioReq | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["config", b"config", "request", b"request", "status", b"status", "stop", b"stop", "type", b"type"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["config", b"config", "request", b"request", "status", b"status", "stop", b"stop", "type", b"type"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["type", b"type"]) -> typing.Literal["stop", "config", "status", "request"] | None: ...

global___GpioData = GpioData
