# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ciot/proto/v2/http_server.proto
# Protobuf Python Version: 6.30.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    0,
    '',
    'ciot/proto/v2/http_server.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1f\x63iot/proto/v2/http_server.proto\x12\x04\x43iot\"\x10\n\x0eHttpServerStop\"K\n\rHttpServerCfg\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\t\x12\r\n\x05route\x18\x02 \x01(\t\x12\x0c\n\x04port\x18\x03 \x01(\r\x12\x0c\n\x04root\x18\x04 \x01(\t\"G\n\x10HttpServerStatus\x12$\n\x05state\x18\x01 \x01(\x0e\x32\x15.Ciot.HttpServerState\x12\r\n\x05\x65rror\x18\x02 \x01(\r\"\x0f\n\rHttpServerReq\"\xb7\x01\n\x0eHttpServerData\x12$\n\x04stop\x18\x01 \x01(\x0b\x32\x14.Ciot.HttpServerStopH\x00\x12%\n\x06\x63onfig\x18\x02 \x01(\x0b\x32\x13.Ciot.HttpServerCfgH\x00\x12(\n\x06status\x18\x03 \x01(\x0b\x32\x16.Ciot.HttpServerStatusH\x00\x12&\n\x07request\x18\x04 \x01(\x0b\x32\x13.Ciot.HttpServerReqH\x00\x42\x06\n\x04type*l\n\x0fHttpServerState\x12\x1d\n\x19HTTP_SERVER_STATE_STOPPED\x10\x00\x12\x1d\n\x19HTTP_SERVER_STATE_STARTED\x10\x01\x12\x1b\n\x17HTTP_SERVER_STATE_ERROR\x10\x02\x42\x11\xaa\x02\x0e\x43iot.Protos.V2b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ciot.proto.v2.http_server_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002\016Ciot.Protos.V2'
  _globals['_HTTPSERVERSTATE']._serialized_start=412
  _globals['_HTTPSERVERSTATE']._serialized_end=520
  _globals['_HTTPSERVERSTOP']._serialized_start=41
  _globals['_HTTPSERVERSTOP']._serialized_end=57
  _globals['_HTTPSERVERCFG']._serialized_start=59
  _globals['_HTTPSERVERCFG']._serialized_end=134
  _globals['_HTTPSERVERSTATUS']._serialized_start=136
  _globals['_HTTPSERVERSTATUS']._serialized_end=207
  _globals['_HTTPSERVERREQ']._serialized_start=209
  _globals['_HTTPSERVERREQ']._serialized_end=224
  _globals['_HTTPSERVERDATA']._serialized_start=227
  _globals['_HTTPSERVERDATA']._serialized_end=410
# @@protoc_insertion_point(module_scope)
