"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import google.protobuf.descriptor
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _HttpClientState:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _HttpClientStateEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_HttpClientState.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    HTTP_CLIENT_STATE_IDLE: _HttpClientState.ValueType  # 0
    """The HTTP client is idle."""
    HTTP_CLIENT_STATE_STARTED: _HttpClientState.ValueType  # 1
    """The HTTP client has started."""
    HTTP_CLIENT_STATE_CONNECTING: _HttpClientState.ValueType  # 2
    """The HTTP client is connecting."""
    HTTP_CLIENT_STATE_CONNECTED: _HttpClientState.ValueType  # 3
    """The HTTP client is connected."""
    HTTP_CLIENT_STATE_DATA_RECEIVED: _HttpClientState.ValueType  # 4
    """Data has been received by the HTTP client."""
    HTTP_CLIENT_STATE_TIMEOUT: _HttpClientState.ValueType  # 5
    """The HTTP client has timed out."""
    HTTP_CLIENT_STATE_ERROR: _HttpClientState.ValueType  # 6
    """The HTTP client encountered an error."""

class HttpClientState(_HttpClientState, metaclass=_HttpClientStateEnumTypeWrapper):
    """Enum representing the state of the HTTP client."""

HTTP_CLIENT_STATE_IDLE: HttpClientState.ValueType  # 0
"""The HTTP client is idle."""
HTTP_CLIENT_STATE_STARTED: HttpClientState.ValueType  # 1
"""The HTTP client has started."""
HTTP_CLIENT_STATE_CONNECTING: HttpClientState.ValueType  # 2
"""The HTTP client is connecting."""
HTTP_CLIENT_STATE_CONNECTED: HttpClientState.ValueType  # 3
"""The HTTP client is connected."""
HTTP_CLIENT_STATE_DATA_RECEIVED: HttpClientState.ValueType  # 4
"""Data has been received by the HTTP client."""
HTTP_CLIENT_STATE_TIMEOUT: HttpClientState.ValueType  # 5
"""The HTTP client has timed out."""
HTTP_CLIENT_STATE_ERROR: HttpClientState.ValueType  # 6
"""The HTTP client encountered an error."""
global___HttpClientState = HttpClientState

class _HttpClientMethod:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _HttpClientMethodEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_HttpClientMethod.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    HTTP_METHOD_GET: _HttpClientMethod.ValueType  # 0
    """HTTP GET method."""
    HTTP_METHOD_POST: _HttpClientMethod.ValueType  # 1
    """HTTP POST method."""
    HTTP_METHOD_PUT: _HttpClientMethod.ValueType  # 2
    """HTTP PUT method."""
    HTTP_METHOD_PATCH: _HttpClientMethod.ValueType  # 3
    """HTTP PATCH method."""
    HTTP_METHOD_DELETE: _HttpClientMethod.ValueType  # 4
    """HTTP DELETE method."""
    HTTP_METHOD_HEAD: _HttpClientMethod.ValueType  # 5
    """HTTP HEAD method."""
    HTTP_METHOD_NOTIFY: _HttpClientMethod.ValueType  # 6
    """HTTP NOTIFY method."""
    HTTP_METHOD_SUBSCRIBE: _HttpClientMethod.ValueType  # 7
    """HTTP SUBSCRIBE method."""
    HTTP_METHOD_UNSUBSCRIBE: _HttpClientMethod.ValueType  # 8
    """HTTP UNSUBSCRIBE method."""
    HTTP_METHOD_OPTIONS: _HttpClientMethod.ValueType  # 9
    """HTTP OPTIONS method."""
    HTTP_METHOD_COPY: _HttpClientMethod.ValueType  # 10
    """HTTP COPY method."""
    HTTP_METHOD_MOVE: _HttpClientMethod.ValueType  # 11
    """HTTP MOVE method."""
    HTTP_METHOD_LOCK: _HttpClientMethod.ValueType  # 12
    """HTTP LOCK method."""
    HTTP_METHOD_UNLOCK: _HttpClientMethod.ValueType  # 13
    """HTTP UNLOCK method."""
    HTTP_METHOD_PROPFIND: _HttpClientMethod.ValueType  # 14
    """HTTP PROPFIND method."""
    HTTP_METHOD_PROPPATCH: _HttpClientMethod.ValueType  # 15
    """HTTP PROPPATCH method."""
    HTTP_METHOD_MKCOL: _HttpClientMethod.ValueType  # 16
    """HTTP MKCOL method."""
    HTTP_METHOD_MAX: _HttpClientMethod.ValueType  # 17
    """Maximum value for HTTP methods."""

class HttpClientMethod(_HttpClientMethod, metaclass=_HttpClientMethodEnumTypeWrapper):
    """Enum representing different HTTP methods."""

HTTP_METHOD_GET: HttpClientMethod.ValueType  # 0
"""HTTP GET method."""
HTTP_METHOD_POST: HttpClientMethod.ValueType  # 1
"""HTTP POST method."""
HTTP_METHOD_PUT: HttpClientMethod.ValueType  # 2
"""HTTP PUT method."""
HTTP_METHOD_PATCH: HttpClientMethod.ValueType  # 3
"""HTTP PATCH method."""
HTTP_METHOD_DELETE: HttpClientMethod.ValueType  # 4
"""HTTP DELETE method."""
HTTP_METHOD_HEAD: HttpClientMethod.ValueType  # 5
"""HTTP HEAD method."""
HTTP_METHOD_NOTIFY: HttpClientMethod.ValueType  # 6
"""HTTP NOTIFY method."""
HTTP_METHOD_SUBSCRIBE: HttpClientMethod.ValueType  # 7
"""HTTP SUBSCRIBE method."""
HTTP_METHOD_UNSUBSCRIBE: HttpClientMethod.ValueType  # 8
"""HTTP UNSUBSCRIBE method."""
HTTP_METHOD_OPTIONS: HttpClientMethod.ValueType  # 9
"""HTTP OPTIONS method."""
HTTP_METHOD_COPY: HttpClientMethod.ValueType  # 10
"""HTTP COPY method."""
HTTP_METHOD_MOVE: HttpClientMethod.ValueType  # 11
"""HTTP MOVE method."""
HTTP_METHOD_LOCK: HttpClientMethod.ValueType  # 12
"""HTTP LOCK method."""
HTTP_METHOD_UNLOCK: HttpClientMethod.ValueType  # 13
"""HTTP UNLOCK method."""
HTTP_METHOD_PROPFIND: HttpClientMethod.ValueType  # 14
"""HTTP PROPFIND method."""
HTTP_METHOD_PROPPATCH: HttpClientMethod.ValueType  # 15
"""HTTP PROPPATCH method."""
HTTP_METHOD_MKCOL: HttpClientMethod.ValueType  # 16
"""HTTP MKCOL method."""
HTTP_METHOD_MAX: HttpClientMethod.ValueType  # 17
"""Maximum value for HTTP methods."""
global___HttpClientMethod = HttpClientMethod

class _HttpClientTransportType:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _HttpClientTransportTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_HttpClientTransportType.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    HTTP_TRANSPORT_UNKNOWN: _HttpClientTransportType.ValueType  # 0
    """Unknown transport type."""
    HTTP_TRANSPORT_TCP: _HttpClientTransportType.ValueType  # 1
    """TCP transport."""
    HTTP_TRANSPORT_SSL: _HttpClientTransportType.ValueType  # 2
    """SSL transport."""

class HttpClientTransportType(_HttpClientTransportType, metaclass=_HttpClientTransportTypeEnumTypeWrapper):
    """Enum representing different HTTP transport types."""

HTTP_TRANSPORT_UNKNOWN: HttpClientTransportType.ValueType  # 0
"""Unknown transport type."""
HTTP_TRANSPORT_TCP: HttpClientTransportType.ValueType  # 1
"""TCP transport."""
HTTP_TRANSPORT_SSL: HttpClientTransportType.ValueType  # 2
"""SSL transport."""
global___HttpClientTransportType = HttpClientTransportType

@typing.final
class HttpClientStop(google.protobuf.message.Message):
    """Message used to stop HTTP client interface"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___HttpClientStop = HttpClientStop

@typing.final
class HttpClientCfg(google.protobuf.message.Message):
    """Message representing HTTP client configuration."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    URL_FIELD_NUMBER: builtins.int
    METHOD_FIELD_NUMBER: builtins.int
    TRANSPORT_FIELD_NUMBER: builtins.int
    TIMEOUT_FIELD_NUMBER: builtins.int
    url: builtins.str
    """URL for the HTTP request."""
    method: global___HttpClientMethod.ValueType
    """HTTP method to use."""
    transport: global___HttpClientTransportType.ValueType
    """Transport type for the HTTP request."""
    timeout: builtins.int
    """Timeout for the HTTP request."""
    def __init__(
        self,
        *,
        url: builtins.str = ...,
        method: global___HttpClientMethod.ValueType = ...,
        transport: global___HttpClientTransportType.ValueType = ...,
        timeout: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["method", b"method", "timeout", b"timeout", "transport", b"transport", "url", b"url"]) -> None: ...

global___HttpClientCfg = HttpClientCfg

@typing.final
class HttpClientStatus(google.protobuf.message.Message):
    """Message representing HTTP client status."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    STATE_FIELD_NUMBER: builtins.int
    ERROR_FIELD_NUMBER: builtins.int
    state: global___HttpClientState.ValueType
    """State of the HTTP client."""
    error: builtins.int
    """Error code, if any."""
    def __init__(
        self,
        *,
        state: global___HttpClientState.ValueType = ...,
        error: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["error", b"error", "state", b"state"]) -> None: ...

global___HttpClientStatus = HttpClientStatus

@typing.final
class HttpClientReqSend(google.protobuf.message.Message):
    """Message representing data to be sent by the HTTP client."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CONFIG_FIELD_NUMBER: builtins.int
    BODY_FIELD_NUMBER: builtins.int
    body: builtins.bytes
    """Body of the HTTP request."""
    @property
    def config(self) -> global___HttpClientCfg:
        """Configuration for the HTTP client."""

    def __init__(
        self,
        *,
        config: global___HttpClientCfg | None = ...,
        body: builtins.bytes = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["config", b"config"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["body", b"body", "config", b"config"]) -> None: ...

global___HttpClientReqSend = HttpClientReqSend

@typing.final
class HttpClientReqSetHeader(google.protobuf.message.Message):
    """Message representing setting a header for the HTTP client request."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    HEADER_FIELD_NUMBER: builtins.int
    VALUE_FIELD_NUMBER: builtins.int
    header: builtins.str
    """Header name."""
    value: builtins.str
    """Header value."""
    def __init__(
        self,
        *,
        header: builtins.str = ...,
        value: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["header", b"header", "value", b"value"]) -> None: ...

global___HttpClientReqSetHeader = HttpClientReqSetHeader

@typing.final
class HttpClientReq(google.protobuf.message.Message):
    """Message representing an HTTP client request."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SEND_FIELD_NUMBER: builtins.int
    SET_HEADER_FIELD_NUMBER: builtins.int
    @property
    def send(self) -> global___HttpClientReqSend:
        """Data to be sent in the request."""

    @property
    def set_header(self) -> global___HttpClientReqSetHeader:
        """Header to be set in the request."""

    def __init__(
        self,
        *,
        send: global___HttpClientReqSend | None = ...,
        set_header: global___HttpClientReqSetHeader | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["send", b"send", "set_header", b"set_header", "type", b"type"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["send", b"send", "set_header", b"set_header", "type", b"type"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["type", b"type"]) -> typing.Literal["send", "set_header"] | None: ...

global___HttpClientReq = HttpClientReq

@typing.final
class HttpClientData(google.protobuf.message.Message):
    """Message representing HTTP client data."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    STOP_FIELD_NUMBER: builtins.int
    CONFIG_FIELD_NUMBER: builtins.int
    STATUS_FIELD_NUMBER: builtins.int
    REQUEST_FIELD_NUMBER: builtins.int
    @property
    def stop(self) -> global___HttpClientStop:
        """Stop HTTP client."""

    @property
    def config(self) -> global___HttpClientCfg:
        """Configuration for the HTTP client."""

    @property
    def status(self) -> global___HttpClientStatus:
        """Status of the HTTP client."""

    @property
    def request(self) -> global___HttpClientReq:
        """HTTP client request."""

    def __init__(
        self,
        *,
        stop: global___HttpClientStop | None = ...,
        config: global___HttpClientCfg | None = ...,
        status: global___HttpClientStatus | None = ...,
        request: global___HttpClientReq | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["config", b"config", "request", b"request", "status", b"status", "stop", b"stop", "type", b"type"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["config", b"config", "request", b"request", "status", b"status", "stop", b"stop", "type", b"type"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["type", b"type"]) -> typing.Literal["stop", "config", "status", "request"] | None: ...

global___HttpClientData = HttpClientData
