"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import google.protobuf.descriptor
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _HttpServerState:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _HttpServerStateEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_HttpServerState.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    HTTP_SERVER_STATE_STOPPED: _HttpServerState.ValueType  # 0
    """The HTTP server is stopped."""
    HTTP_SERVER_STATE_STARTED: _HttpServerState.ValueType  # 1
    """The HTTP server is started."""
    HTTP_SERVER_STATE_ERROR: _HttpServerState.ValueType  # 2
    """The HTTP server encountered an error."""

class HttpServerState(_HttpServerState, metaclass=_HttpServerStateEnumTypeWrapper):
    """Enum representing the state of the HTTP server."""

HTTP_SERVER_STATE_STOPPED: HttpServerState.ValueType  # 0
"""The HTTP server is stopped."""
HTTP_SERVER_STATE_STARTED: HttpServerState.ValueType  # 1
"""The HTTP server is started."""
HTTP_SERVER_STATE_ERROR: HttpServerState.ValueType  # 2
"""The HTTP server encountered an error."""
global___HttpServerState = HttpServerState

@typing.final
class HttpServerStop(google.protobuf.message.Message):
    """Message used to stop HTTP server interface"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___HttpServerStop = HttpServerStop

@typing.final
class HttpServerCfg(google.protobuf.message.Message):
    """Message representing HTTP server configuration."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ADDRESS_FIELD_NUMBER: builtins.int
    ROUTE_FIELD_NUMBER: builtins.int
    PORT_FIELD_NUMBER: builtins.int
    ROOT_FIELD_NUMBER: builtins.int
    address: builtins.str
    """Address of the HTTP server."""
    route: builtins.str
    """Route for the HTTP server."""
    port: builtins.int
    """Port number for the HTTP server."""
    root: builtins.str
    """Server files root directory"""
    def __init__(
        self,
        *,
        address: builtins.str = ...,
        route: builtins.str = ...,
        port: builtins.int = ...,
        root: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["address", b"address", "port", b"port", "root", b"root", "route", b"route"]) -> None: ...

global___HttpServerCfg = HttpServerCfg

@typing.final
class HttpServerStatus(google.protobuf.message.Message):
    """Message representing HTTP server status."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    STATE_FIELD_NUMBER: builtins.int
    ERROR_FIELD_NUMBER: builtins.int
    state: global___HttpServerState.ValueType
    """State of the HTTP server."""
    error: builtins.int
    """Error code, if any."""
    def __init__(
        self,
        *,
        state: global___HttpServerState.ValueType = ...,
        error: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["error", b"error", "state", b"state"]) -> None: ...

global___HttpServerStatus = HttpServerStatus

@typing.final
class HttpServerReq(google.protobuf.message.Message):
    """Message representing an HTTP server request."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___HttpServerReq = HttpServerReq

@typing.final
class HttpServerData(google.protobuf.message.Message):
    """Message representing HTTP server data."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    STOP_FIELD_NUMBER: builtins.int
    CONFIG_FIELD_NUMBER: builtins.int
    STATUS_FIELD_NUMBER: builtins.int
    REQUEST_FIELD_NUMBER: builtins.int
    @property
    def stop(self) -> global___HttpServerStop:
        """Stop HTTP server."""

    @property
    def config(self) -> global___HttpServerCfg:
        """Configuration for the HTTP server."""

    @property
    def status(self) -> global___HttpServerStatus:
        """Status of the HTTP server."""

    @property
    def request(self) -> global___HttpServerReq:
        """HTTP server request data."""

    def __init__(
        self,
        *,
        stop: global___HttpServerStop | None = ...,
        config: global___HttpServerCfg | None = ...,
        status: global___HttpServerStatus | None = ...,
        request: global___HttpServerReq | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["config", b"config", "request", b"request", "status", b"status", "stop", b"stop", "type", b"type"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["config", b"config", "request", b"request", "status", b"status", "stop", b"stop", "type", b"type"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["type", b"type"]) -> typing.Literal["stop", "config", "status", "request"] | None: ...

global___HttpServerData = HttpServerData
