"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import google.protobuf.descriptor
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _IfaceState:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _IfaceStateEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_IfaceState.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    IFACE_STATE_STOPPED: _IfaceState.ValueType  # 0
    IFACE_STATE_STARTED: _IfaceState.ValueType  # 1
    IFACE_STATE_ERROR: _IfaceState.ValueType  # 2

class IfaceState(_IfaceState, metaclass=_IfaceStateEnumTypeWrapper): ...

IFACE_STATE_STOPPED: IfaceState.ValueType  # 0
IFACE_STATE_STARTED: IfaceState.ValueType  # 1
IFACE_STATE_ERROR: IfaceState.ValueType  # 2
global___IfaceState = IfaceState

class _IfaceType:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _IfaceTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_IfaceType.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    IFACE_TYPE_UNDEFINED: _IfaceType.ValueType  # 0
    """Undefined interface type."""
    IFACE_TYPE_CUSTOM: _IfaceType.ValueType  # 1
    """Custom interface type."""
    IFACE_TYPE_CIOT: _IfaceType.ValueType  # 2
    """CIOT interface type."""
    IFACE_TYPE_STORAGE: _IfaceType.ValueType  # 3
    """Storage interface type."""
    IFACE_TYPE_SYS: _IfaceType.ValueType  # 4
    """System interface type."""
    IFACE_TYPE_UART: _IfaceType.ValueType  # 5
    """UART interface type."""
    IFACE_TYPE_USB: _IfaceType.ValueType  # 6
    """USB interface type."""
    IFACE_TYPE_TCP: _IfaceType.ValueType  # 7
    """TCP interface type."""
    IFACE_TYPE_ETH: _IfaceType.ValueType  # 8
    """Ethernet interface type."""
    IFACE_TYPE_WIFI: _IfaceType.ValueType  # 9
    """WiFi interface type."""
    IFACE_TYPE_BLE: _IfaceType.ValueType  # 10
    """BLE interface type."""
    IFACE_TYPE_BLE_SCN: _IfaceType.ValueType  # 11
    """BLE SCN interface type."""
    IFACE_TYPE_BLE_ADV: _IfaceType.ValueType  # 12
    """BLE ADV interface type."""
    IFACE_TYPE_GPIO: _IfaceType.ValueType  # 13
    """GPIO interface type."""
    IFACE_TYPE_NTP: _IfaceType.ValueType  # 14
    """NTP interface type."""
    IFACE_TYPE_OTA: _IfaceType.ValueType  # 15
    """OTA interface type."""
    IFACE_TYPE_DFU: _IfaceType.ValueType  # 16
    """DFU interface type."""
    IFACE_TYPE_HTTP_CLIENT: _IfaceType.ValueType  # 17
    """HTTP Client interface type."""
    IFACE_TYPE_HTTP_SERVER: _IfaceType.ValueType  # 18
    """HTTP Server interface type."""
    IFACE_TYPE_MQTT_CLIENT: _IfaceType.ValueType  # 19
    """MQTT interface type."""
    IFACE_TYPE_SOCKET: _IfaceType.ValueType  # 20
    """Socket interface type."""
    IFACE_TYPE_BRIDGE: _IfaceType.ValueType  # 21
    """Bridge interface type."""
    IFACE_TYPE_IOTA_CLIENT: _IfaceType.ValueType  # 22
    """IOTA client interface type."""
    IFACE_TYPE_IOTA_SERVER: _IfaceType.ValueType  # 23
    """IOTA server interface type."""
    IFACE_TYPE_LOG: _IfaceType.ValueType  # 24
    """LOG interface type."""
    IFACE_TYPE_MBUS_CLIENT: _IfaceType.ValueType  # 25
    """Modbus client interface type."""
    IFACE_TYPE_MBUS_SERVER: _IfaceType.ValueType  # 26
    """Modbus server interface type."""
    IFACE_TYPE_PWM: _IfaceType.ValueType  # 27
    """PWM interface type."""

class IfaceType(_IfaceType, metaclass=_IfaceTypeEnumTypeWrapper):
    """Enum representing different interface types."""

IFACE_TYPE_UNDEFINED: IfaceType.ValueType  # 0
"""Undefined interface type."""
IFACE_TYPE_CUSTOM: IfaceType.ValueType  # 1
"""Custom interface type."""
IFACE_TYPE_CIOT: IfaceType.ValueType  # 2
"""CIOT interface type."""
IFACE_TYPE_STORAGE: IfaceType.ValueType  # 3
"""Storage interface type."""
IFACE_TYPE_SYS: IfaceType.ValueType  # 4
"""System interface type."""
IFACE_TYPE_UART: IfaceType.ValueType  # 5
"""UART interface type."""
IFACE_TYPE_USB: IfaceType.ValueType  # 6
"""USB interface type."""
IFACE_TYPE_TCP: IfaceType.ValueType  # 7
"""TCP interface type."""
IFACE_TYPE_ETH: IfaceType.ValueType  # 8
"""Ethernet interface type."""
IFACE_TYPE_WIFI: IfaceType.ValueType  # 9
"""WiFi interface type."""
IFACE_TYPE_BLE: IfaceType.ValueType  # 10
"""BLE interface type."""
IFACE_TYPE_BLE_SCN: IfaceType.ValueType  # 11
"""BLE SCN interface type."""
IFACE_TYPE_BLE_ADV: IfaceType.ValueType  # 12
"""BLE ADV interface type."""
IFACE_TYPE_GPIO: IfaceType.ValueType  # 13
"""GPIO interface type."""
IFACE_TYPE_NTP: IfaceType.ValueType  # 14
"""NTP interface type."""
IFACE_TYPE_OTA: IfaceType.ValueType  # 15
"""OTA interface type."""
IFACE_TYPE_DFU: IfaceType.ValueType  # 16
"""DFU interface type."""
IFACE_TYPE_HTTP_CLIENT: IfaceType.ValueType  # 17
"""HTTP Client interface type."""
IFACE_TYPE_HTTP_SERVER: IfaceType.ValueType  # 18
"""HTTP Server interface type."""
IFACE_TYPE_MQTT_CLIENT: IfaceType.ValueType  # 19
"""MQTT interface type."""
IFACE_TYPE_SOCKET: IfaceType.ValueType  # 20
"""Socket interface type."""
IFACE_TYPE_BRIDGE: IfaceType.ValueType  # 21
"""Bridge interface type."""
IFACE_TYPE_IOTA_CLIENT: IfaceType.ValueType  # 22
"""IOTA client interface type."""
IFACE_TYPE_IOTA_SERVER: IfaceType.ValueType  # 23
"""IOTA server interface type."""
IFACE_TYPE_LOG: IfaceType.ValueType  # 24
"""LOG interface type."""
IFACE_TYPE_MBUS_CLIENT: IfaceType.ValueType  # 25
"""Modbus client interface type."""
IFACE_TYPE_MBUS_SERVER: IfaceType.ValueType  # 26
"""Modbus server interface type."""
IFACE_TYPE_PWM: IfaceType.ValueType  # 27
"""PWM interface type."""
global___IfaceType = IfaceType

class _IfaceReqState:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _IfaceReqStateEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_IfaceReqState.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    IFACE_REQ_STATE_IDLE: _IfaceReqState.ValueType  # 0
    """Idle. No request sended or received."""
    IFACE_REQ_STATE_SENDED: _IfaceReqState.ValueType  # 1
    """Request sended"""
    IFACE_REQ_STATE_RECEIVED: _IfaceReqState.ValueType  # 3
    """Request received"""

class IfaceReqState(_IfaceReqState, metaclass=_IfaceReqStateEnumTypeWrapper):
    """Enum representing different states of the interface request."""

IFACE_REQ_STATE_IDLE: IfaceReqState.ValueType  # 0
"""Idle. No request sended or received."""
IFACE_REQ_STATE_SENDED: IfaceReqState.ValueType  # 1
"""Request sended"""
IFACE_REQ_STATE_RECEIVED: IfaceReqState.ValueType  # 3
"""Request received"""
global___IfaceReqState = IfaceReqState

class _DataType:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _DataTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_DataType.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    DATA_TYPE_UNKNOWN: _DataType.ValueType  # 0
    """Unknown data type."""
    DATA_TYPE_STOP: _DataType.ValueType  # 1
    """Stop data type."""
    DATA_TYPE_CONFIG: _DataType.ValueType  # 2
    """Configuration data type."""
    DATA_TYPE_STATUS: _DataType.ValueType  # 3
    """Status data type."""
    DATA_TYPE_REQUEST: _DataType.ValueType  # 4
    """Request data type."""
    DATA_TYPE_INFO: _DataType.ValueType  # 5
    """Information data type."""

class DataType(_DataType, metaclass=_DataTypeEnumTypeWrapper):
    """Enum representing different data types for the interface request."""

DATA_TYPE_UNKNOWN: DataType.ValueType  # 0
"""Unknown data type."""
DATA_TYPE_STOP: DataType.ValueType  # 1
"""Stop data type."""
DATA_TYPE_CONFIG: DataType.ValueType  # 2
"""Configuration data type."""
DATA_TYPE_STATUS: DataType.ValueType  # 3
"""Status data type."""
DATA_TYPE_REQUEST: DataType.ValueType  # 4
"""Request data type."""
DATA_TYPE_INFO: DataType.ValueType  # 5
"""Information data type."""
global___DataType = DataType

@typing.final
class GetData(google.protobuf.message.Message):
    """Message representing a request to get data."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TYPE_FIELD_NUMBER: builtins.int
    type: global___DataType.ValueType
    """Data type of the request."""
    def __init__(
        self,
        *,
        type: global___DataType.ValueType = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["type", b"type"]) -> None: ...

global___GetData = GetData

@typing.final
class Common(google.protobuf.message.Message):
    """Message representing common data."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    STOP_FIELD_NUMBER: builtins.int
    stop: builtins.bool
    """Stop request."""
    def __init__(
        self,
        *,
        stop: builtins.bool = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["stop", b"stop", "type", b"type"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["stop", b"stop", "type", b"type"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["type", b"type"]) -> typing.Literal["stop"] | None: ...

global___Common = Common

@typing.final
class IfaceInfo(google.protobuf.message.Message):
    """Message representing information about an interface."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    TYPE_FIELD_NUMBER: builtins.int
    id: builtins.int
    """Interface ID."""
    type: global___IfaceType.ValueType
    """Interface type."""
    def __init__(
        self,
        *,
        id: builtins.int = ...,
        type: global___IfaceType.ValueType = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["id", b"id", "type", b"type"]) -> None: ...

global___IfaceInfo = IfaceInfo

@typing.final
class IfaceReqStatus(google.protobuf.message.Message):
    """Message representing interface request status.enum"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    STATE_FIELD_NUMBER: builtins.int
    DATA_TYPE_FIELD_NUMBER: builtins.int
    IFACE_FIELD_NUMBER: builtins.int
    id: builtins.int
    """Request message ID"""
    state: global___IfaceReqState.ValueType
    """Request state"""
    data_type: builtins.int
    """Request message data type"""
    @property
    def iface(self) -> global___IfaceInfo:
        """Interface information"""

    def __init__(
        self,
        *,
        id: builtins.int = ...,
        state: global___IfaceReqState.ValueType = ...,
        data_type: builtins.int = ...,
        iface: global___IfaceInfo | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["iface", b"iface"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["data_type", b"data_type", "id", b"id", "iface", b"iface", "state", b"state"]) -> None: ...

global___IfaceReqStatus = IfaceReqStatus
