"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import ciot.proto.v2.iface_pb2
import ciot.proto.v2.msg_pb2
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class IfacesList(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ITEMS_FIELD_NUMBER: builtins.int
    @property
    def items(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[ciot.proto.v2.msg_pb2.Msg]: ...
    def __init__(
        self,
        *,
        items: collections.abc.Iterable[ciot.proto.v2.msg_pb2.Msg] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["items", b"items"]) -> None: ...

global___IfacesList = IfacesList

@typing.final
class CreateIfaceRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    MESSAGE_FIELD_NUMBER: builtins.int
    @property
    def message(self) -> ciot.proto.v2.msg_pb2.Msg: ...
    def __init__(
        self,
        *,
        message: ciot.proto.v2.msg_pb2.Msg | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["message", b"message"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["message", b"message"]) -> None: ...

global___CreateIfaceRequest = CreateIfaceRequest

@typing.final
class CreateIfaceResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    MESSAGE_FIELD_NUMBER: builtins.int
    @property
    def message(self) -> ciot.proto.v2.msg_pb2.Msg: ...
    def __init__(
        self,
        *,
        message: ciot.proto.v2.msg_pb2.Msg | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["message", b"message"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["message", b"message"]) -> None: ...

global___CreateIfaceResponse = CreateIfaceResponse

@typing.final
class GetIfaceRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    id: builtins.int
    def __init__(
        self,
        *,
        id: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["id", b"id"]) -> None: ...

global___GetIfaceRequest = GetIfaceRequest

@typing.final
class GetIfaceResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    MESSAGE_FIELD_NUMBER: builtins.int
    @property
    def message(self) -> ciot.proto.v2.msg_pb2.Msg: ...
    def __init__(
        self,
        *,
        message: ciot.proto.v2.msg_pb2.Msg | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["message", b"message"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["message", b"message"]) -> None: ...

global___GetIfaceResponse = GetIfaceResponse

@typing.final
class GetIfacesResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    LIST_FIELD_NUMBER: builtins.int
    @property
    def list(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[ciot.proto.v2.msg_pb2.Msg]: ...
    def __init__(
        self,
        *,
        list: collections.abc.Iterable[ciot.proto.v2.msg_pb2.Msg] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["list", b"list"]) -> None: ...

global___GetIfacesResponse = GetIfacesResponse

@typing.final
class UpdateIfaceRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    MESSAGE_FIELD_NUMBER: builtins.int
    @property
    def message(self) -> ciot.proto.v2.msg_pb2.Msg: ...
    def __init__(
        self,
        *,
        message: ciot.proto.v2.msg_pb2.Msg | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["message", b"message"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["message", b"message"]) -> None: ...

global___UpdateIfaceRequest = UpdateIfaceRequest

@typing.final
class UpdateIfaceResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    MESSAGE_FIELD_NUMBER: builtins.int
    @property
    def message(self) -> ciot.proto.v2.msg_pb2.Msg: ...
    def __init__(
        self,
        *,
        message: ciot.proto.v2.msg_pb2.Msg | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["message", b"message"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["message", b"message"]) -> None: ...

global___UpdateIfaceResponse = UpdateIfaceResponse

@typing.final
class DeleteIfaceRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    id: builtins.int
    def __init__(
        self,
        *,
        id: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["id", b"id"]) -> None: ...

global___DeleteIfaceRequest = DeleteIfaceRequest

@typing.final
class DeleteIfaceResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    MESSAGE_FIELD_NUMBER: builtins.int
    @property
    def message(self) -> ciot.proto.v2.msg_pb2.Msg: ...
    def __init__(
        self,
        *,
        message: ciot.proto.v2.msg_pb2.Msg | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["message", b"message"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["message", b"message"]) -> None: ...

global___DeleteIfaceResponse = DeleteIfaceResponse

@typing.final
class SelectIfaceRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    id: builtins.int
    def __init__(
        self,
        *,
        id: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["id", b"id"]) -> None: ...

global___SelectIfaceRequest = SelectIfaceRequest

@typing.final
class SelectIfaceResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    IFACE_FIELD_NUMBER: builtins.int
    @property
    def iface(self) -> ciot.proto.v2.iface_pb2.IfaceInfo: ...
    def __init__(
        self,
        *,
        iface: ciot.proto.v2.iface_pb2.IfaceInfo | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["iface", b"iface"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["iface", b"iface"]) -> None: ...

global___SelectIfaceResponse = SelectIfaceResponse

@typing.final
class GetSelectedIfaceResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    IFACE_FIELD_NUMBER: builtins.int
    @property
    def iface(self) -> ciot.proto.v2.iface_pb2.IfaceInfo: ...
    def __init__(
        self,
        *,
        iface: ciot.proto.v2.iface_pb2.IfaceInfo | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["iface", b"iface"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["iface", b"iface"]) -> None: ...

global___GetSelectedIfaceResponse = GetSelectedIfaceResponse

@typing.final
class SendMessageRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    MESSAGE_FIELD_NUMBER: builtins.int
    @property
    def message(self) -> ciot.proto.v2.msg_pb2.Msg: ...
    def __init__(
        self,
        *,
        message: ciot.proto.v2.msg_pb2.Msg | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["message", b"message"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["message", b"message"]) -> None: ...

global___SendMessageRequest = SendMessageRequest

@typing.final
class SendMessageResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    MESSAGE_FIELD_NUMBER: builtins.int
    @property
    def message(self) -> ciot.proto.v2.msg_pb2.Msg: ...
    def __init__(
        self,
        *,
        message: ciot.proto.v2.msg_pb2.Msg | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["message", b"message"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["message", b"message"]) -> None: ...

global___SendMessageResponse = SendMessageResponse

@typing.final
class SubscribeToEventsRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    IFACE_FIELD_NUMBER: builtins.int
    id: builtins.str
    @property
    def iface(self) -> ciot.proto.v2.iface_pb2.IfaceInfo: ...
    def __init__(
        self,
        *,
        id: builtins.str = ...,
        iface: ciot.proto.v2.iface_pb2.IfaceInfo | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["iface", b"iface"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["id", b"id", "iface", b"iface"]) -> None: ...

global___SubscribeToEventsRequest = SubscribeToEventsRequest
