"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import google.protobuf.descriptor
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _LogLevel:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _LogLevelEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_LogLevel.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    LOG_LEVEL_NONE: _LogLevel.ValueType  # 0
    LOG_LEVEL_ERROR: _LogLevel.ValueType  # 1
    LOG_LEVEL_WARNING: _LogLevel.ValueType  # 2
    LOG_LEVEL_INFO: _LogLevel.ValueType  # 3
    LOG_LEVEL_VERBOSE: _LogLevel.ValueType  # 4
    LOG_LEVEL_DEBUG: _LogLevel.ValueType  # 5

class LogLevel(_LogLevel, metaclass=_LogLevelEnumTypeWrapper): ...

LOG_LEVEL_NONE: LogLevel.ValueType  # 0
LOG_LEVEL_ERROR: LogLevel.ValueType  # 1
LOG_LEVEL_WARNING: LogLevel.ValueType  # 2
LOG_LEVEL_INFO: LogLevel.ValueType  # 3
LOG_LEVEL_VERBOSE: LogLevel.ValueType  # 4
LOG_LEVEL_DEBUG: LogLevel.ValueType  # 5
global___LogLevel = LogLevel

@typing.final
class LogData(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    LEVEL_FIELD_NUMBER: builtins.int
    TAG_FIELD_NUMBER: builtins.int
    MESSAGE_FIELD_NUMBER: builtins.int
    level: global___LogLevel.ValueType
    tag: builtins.str
    message: builtins.str
    def __init__(
        self,
        *,
        level: global___LogLevel.ValueType = ...,
        tag: builtins.str = ...,
        message: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["level", b"level", "message", b"message", "tag", b"tag"]) -> None: ...

global___LogData = LogData
