# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ciot/proto/v2/mbus_client.proto
# Protobuf Python Version: 6.30.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    0,
    '',
    'ciot/proto/v2/mbus_client.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ciot.proto.v2 import mbus_pb2 as ciot_dot_proto_dot_v2_dot_mbus__pb2
from ciot.proto.v2 import uart_pb2 as ciot_dot_proto_dot_v2_dot_uart__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1f\x63iot/proto/v2/mbus_client.proto\x12\x04\x43iot\x1a\x18\x63iot/proto/v2/mbus.proto\x1a\x18\x63iot/proto/v2/uart.proto\"\x10\n\x0eMbusClientStop\"H\n\x10MbusClientRtuCfg\x12\x11\n\tserver_id\x18\x01 \x01(\r\x12!\n\nserial_cfg\x18\x02 \x01(\x0b\x32\r.Ciot.UartCfg\",\n\x10MbusClientTcpCfg\x12\n\n\x02ip\x18\x01 \x01(\x0c\x12\x0c\n\x04port\x18\x02 \x01(\r\"v\n\rMbusClientCfg\x12%\n\x03rtu\x18\x01 \x01(\x0b\x32\x16.Ciot.MbusClientRtuCfgH\x00\x12%\n\x03tcp\x18\x02 \x01(\x0b\x32\x16.Ciot.MbusClientTcpCfgH\x00\x12\x0f\n\x07timeout\x18\x03 \x01(\rB\x06\n\x04type\"X\n\x10MbusClientStatus\x12$\n\x05state\x18\x01 \x01(\x0e\x32\x15.Ciot.MbusClientState\x12\x1e\n\x05\x65rror\x18\x02 \x01(\x0e\x32\x0f.Ciot.MbusError\"B\n\rMbusClientReq\x12)\n\x08\x66unction\x18\x01 \x01(\x0b\x32\x15.Ciot.MbusFunctionReqH\x00\x42\x06\n\x04type\"\xb7\x01\n\x0eMbusClientData\x12$\n\x04stop\x18\x01 \x01(\x0b\x32\x14.Ciot.MbusClientStopH\x00\x12%\n\x06\x63onfig\x18\x02 \x01(\x0b\x32\x13.Ciot.MbusClientCfgH\x00\x12(\n\x06status\x18\x03 \x01(\x0b\x32\x16.Ciot.MbusClientStatusH\x00\x12&\n\x07request\x18\x04 \x01(\x0b\x32\x13.Ciot.MbusClientReqH\x00\x42\x06\n\x04type*l\n\x0fMbusClientState\x12\x1d\n\x19MBUS_CLIENT_STATE_STOPPED\x10\x00\x12\x1d\n\x19MBUS_CLIENT_STATE_STARTED\x10\x01\x12\x1b\n\x17MBUS_CLIENT_STATE_ERROR\x10\x02\x42\x11\xaa\x02\x0e\x43iot.Protos.V2b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ciot.proto.v2.mbus_client_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002\016Ciot.Protos.V2'
  _globals['_MBUSCLIENTSTATE']._serialized_start=695
  _globals['_MBUSCLIENTSTATE']._serialized_end=803
  _globals['_MBUSCLIENTSTOP']._serialized_start=93
  _globals['_MBUSCLIENTSTOP']._serialized_end=109
  _globals['_MBUSCLIENTRTUCFG']._serialized_start=111
  _globals['_MBUSCLIENTRTUCFG']._serialized_end=183
  _globals['_MBUSCLIENTTCPCFG']._serialized_start=185
  _globals['_MBUSCLIENTTCPCFG']._serialized_end=229
  _globals['_MBUSCLIENTCFG']._serialized_start=231
  _globals['_MBUSCLIENTCFG']._serialized_end=349
  _globals['_MBUSCLIENTSTATUS']._serialized_start=351
  _globals['_MBUSCLIENTSTATUS']._serialized_end=439
  _globals['_MBUSCLIENTREQ']._serialized_start=441
  _globals['_MBUSCLIENTREQ']._serialized_end=507
  _globals['_MBUSCLIENTDATA']._serialized_start=510
  _globals['_MBUSCLIENTDATA']._serialized_end=693
# @@protoc_insertion_point(module_scope)
