# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ciot/proto/v2/mbus.proto
# Protobuf Python Version: 6.30.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    0,
    '',
    'ciot/proto/v2/mbus.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18\x63iot/proto/v2/mbus.proto\x12\x04\x43iot\"\x8b\x01\n\x0fMbusFunctionReq\x12 \n\x04\x63ode\x18\x01 \x01(\x0e\x32\x12.Ciot.MbusFuncCode\x12\x0f\n\x07\x61\x64\x64ress\x18\x02 \x01(\r\x12\x0c\n\x04\x64\x61ta\x18\x03 \x03(\r\x12\x12\n\nread_count\x18\x04 \x01(\r\x12\x14\n\x0cmax_attempts\x18\x05 \x01(\r\x12\r\n\x05\x65rror\x18\x06 \x01(\r*\xc5\x01\n\tMbusError\x12\x13\n\x0fMBUS_ERROR_NONE\x10\x00\x12\x17\n\x13MBUS_ERROR_REG_ADDR\x10\x01\x12\x12\n\x0eMBUS_ERROR_ARG\x10\x02\x12\x19\n\x15MBUS_ERROR_PORT_LAYER\x10\x03\x12\x1a\n\x16MBUS_ERROR_NO_RESOURCE\x10\x04\x12\x11\n\rMBUS_ERROR_IO\x10\x05\x12\x14\n\x10MBUS_ERROR_STATE\x10\x06\x12\x16\n\x12MBUS_ERROR_TIMEOUT\x10\x07*\xb3\x02\n\x0cMbusFuncCode\x12\x17\n\x13MBUS_FUNC_CODE_NONE\x10\x00\x12\x1d\n\x19MBUS_FUNC_CODE_READ_COILS\x10\x01\x12\x1a\n\x16MBUS_FUNC_CODE_READ_DI\x10\x02\x12\x1a\n\x16MBUS_FUNC_CODE_READ_HR\x10\x03\x12\x1a\n\x16MBUS_FUNC_CODE_READ_IR\x10\x04\x12$\n MBUS_FUNC_CODE_WRITE_SINGLE_COIL\x10\x05\x12\"\n\x1eMBUS_FUNC_CODE_WRITE_SINGLE_HR\x10\x06\x12\'\n#MBUS_FUNC_CODE_WRITE_MULTIPLE_COILS\x10\x0f\x12$\n MBUS_FUNC_CODE_WRITE_MULTIPLE_HR\x10\x10\x42\x11\xaa\x02\x0e\x43iot.Protos.V2b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ciot.proto.v2.mbus_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002\016Ciot.Protos.V2'
  _globals['_MBUSERROR']._serialized_start=177
  _globals['_MBUSERROR']._serialized_end=374
  _globals['_MBUSFUNCCODE']._serialized_start=377
  _globals['_MBUSFUNCCODE']._serialized_end=684
  _globals['_MBUSFUNCTIONREQ']._serialized_start=35
  _globals['_MBUSFUNCTIONREQ']._serialized_end=174
# @@protoc_insertion_point(module_scope)
