# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ciot/proto/v2/mbus_server.proto
# Protobuf Python Version: 6.30.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    0,
    '',
    'ciot/proto/v2/mbus_server.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ciot.proto.v2 import mbus_pb2 as ciot_dot_proto_dot_v2_dot_mbus__pb2
from ciot.proto.v2 import uart_pb2 as ciot_dot_proto_dot_v2_dot_uart__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1f\x63iot/proto/v2/mbus_server.proto\x12\x04\x43iot\x1a\x18\x63iot/proto/v2/mbus.proto\x1a\x18\x63iot/proto/v2/uart.proto\"\x10\n\x0eMbusServerStop\"B\n\x10MbusServerRtuCfg\x12\x11\n\tserver_id\x18\x01 \x01(\r\x12\x1b\n\x04uart\x18\x02 \x01(\x0b\x32\r.Ciot.UartCfg\"9\n\x10MbusServerTcpCfg\x12\x0c\n\x04port\x18\x01 \x01(\r\x12\x17\n\x0fmax_connections\x18\x02 \x01(\r\"e\n\rMbusServerCfg\x12%\n\x03rtu\x18\x01 \x01(\x0b\x32\x16.Ciot.MbusServerRtuCfgH\x00\x12%\n\x03tcp\x18\x02 \x01(\x0b\x32\x16.Ciot.MbusServerTcpCfgH\x00\x42\x06\n\x04type\"8\n\x10MbusServerStatus\x12$\n\x05state\x18\x01 \x01(\x0e\x32\x15.Ciot.MbusServerState\"B\n\rMbusServerReq\x12)\n\x08\x66unction\x18\x01 \x01(\x0b\x32\x15.Ciot.MbusFunctionReqH\x00\x42\x06\n\x04type\"\xb7\x01\n\x0eMbusServerData\x12$\n\x04stop\x18\x01 \x01(\x0b\x32\x14.Ciot.MbusServerStopH\x00\x12%\n\x06\x63onfig\x18\x02 \x01(\x0b\x32\x13.Ciot.MbusServerCfgH\x00\x12(\n\x06status\x18\x03 \x01(\x0b\x32\x16.Ciot.MbusServerStatusH\x00\x12&\n\x07request\x18\x04 \x01(\x0b\x32\x13.Ciot.MbusServerReqH\x00\x42\x06\n\x04type*l\n\x0fMbusServerState\x12\x1d\n\x19MBUS_SERVER_STATE_STOPPED\x10\x00\x12\x1d\n\x19MBUS_SERVER_STATE_STARTED\x10\x01\x12\x1b\n\x17MBUS_SERVER_STATE_ERROR\x10\x02\x42\x11\xaa\x02\x0e\x43iot.Protos.V2b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ciot.proto.v2.mbus_server_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002\016Ciot.Protos.V2'
  _globals['_MBUSSERVERSTATE']._serialized_start=653
  _globals['_MBUSSERVERSTATE']._serialized_end=761
  _globals['_MBUSSERVERSTOP']._serialized_start=93
  _globals['_MBUSSERVERSTOP']._serialized_end=109
  _globals['_MBUSSERVERRTUCFG']._serialized_start=111
  _globals['_MBUSSERVERRTUCFG']._serialized_end=177
  _globals['_MBUSSERVERTCPCFG']._serialized_start=179
  _globals['_MBUSSERVERTCPCFG']._serialized_end=236
  _globals['_MBUSSERVERCFG']._serialized_start=238
  _globals['_MBUSSERVERCFG']._serialized_end=339
  _globals['_MBUSSERVERSTATUS']._serialized_start=341
  _globals['_MBUSSERVERSTATUS']._serialized_end=397
  _globals['_MBUSSERVERREQ']._serialized_start=399
  _globals['_MBUSSERVERREQ']._serialized_end=465
  _globals['_MBUSSERVERDATA']._serialized_start=468
  _globals['_MBUSSERVERDATA']._serialized_end=651
# @@protoc_insertion_point(module_scope)
