"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import ciot.proto.v2.mbus_pb2
import ciot.proto.v2.uart_pb2
import google.protobuf.descriptor
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _MbusServerState:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _MbusServerStateEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_MbusServerState.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    MBUS_SERVER_STATE_STOPPED: _MbusServerState.ValueType  # 0
    """The Modbus server is stopped."""
    MBUS_SERVER_STATE_STARTED: _MbusServerState.ValueType  # 1
    """The Modbus server is started."""
    MBUS_SERVER_STATE_ERROR: _MbusServerState.ValueType  # 2
    """The Modbus server encountered an error."""

class MbusServerState(_MbusServerState, metaclass=_MbusServerStateEnumTypeWrapper):
    """Enum representing the state of the Modbus server."""

MBUS_SERVER_STATE_STOPPED: MbusServerState.ValueType  # 0
"""The Modbus server is stopped."""
MBUS_SERVER_STATE_STARTED: MbusServerState.ValueType  # 1
"""The Modbus server is started."""
MBUS_SERVER_STATE_ERROR: MbusServerState.ValueType  # 2
"""The Modbus server encountered an error."""
global___MbusServerState = MbusServerState

@typing.final
class MbusServerStop(google.protobuf.message.Message):
    """Message used to stop Modbus server interface"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___MbusServerStop = MbusServerStop

@typing.final
class MbusServerRtuCfg(google.protobuf.message.Message):
    """Message representing Modbus RTU configuration"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SERVER_ID_FIELD_NUMBER: builtins.int
    UART_FIELD_NUMBER: builtins.int
    server_id: builtins.int
    """Server ID"""
    @property
    def uart(self) -> ciot.proto.v2.uart_pb2.UartCfg:
        """UART settings"""

    def __init__(
        self,
        *,
        server_id: builtins.int = ...,
        uart: ciot.proto.v2.uart_pb2.UartCfg | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["uart", b"uart"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["server_id", b"server_id", "uart", b"uart"]) -> None: ...

global___MbusServerRtuCfg = MbusServerRtuCfg

@typing.final
class MbusServerTcpCfg(google.protobuf.message.Message):
    """Message representing Modbus TCP configuration"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PORT_FIELD_NUMBER: builtins.int
    MAX_CONNECTIONS_FIELD_NUMBER: builtins.int
    port: builtins.int
    """Server port"""
    max_connections: builtins.int
    """Max simultaneos connections"""
    def __init__(
        self,
        *,
        port: builtins.int = ...,
        max_connections: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["max_connections", b"max_connections", "port", b"port"]) -> None: ...

global___MbusServerTcpCfg = MbusServerTcpCfg

@typing.final
class MbusServerCfg(google.protobuf.message.Message):
    """Message representing Modbus server configuration."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    RTU_FIELD_NUMBER: builtins.int
    TCP_FIELD_NUMBER: builtins.int
    @property
    def rtu(self) -> global___MbusServerRtuCfg:
        """Modbus RTU configuration"""

    @property
    def tcp(self) -> global___MbusServerTcpCfg:
        """Modbus TCP configuration"""

    def __init__(
        self,
        *,
        rtu: global___MbusServerRtuCfg | None = ...,
        tcp: global___MbusServerTcpCfg | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["rtu", b"rtu", "tcp", b"tcp", "type", b"type"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["rtu", b"rtu", "tcp", b"tcp", "type", b"type"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["type", b"type"]) -> typing.Literal["rtu", "tcp"] | None: ...

global___MbusServerCfg = MbusServerCfg

@typing.final
class MbusServerStatus(google.protobuf.message.Message):
    """Message representing Modbus server status."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    STATE_FIELD_NUMBER: builtins.int
    state: global___MbusServerState.ValueType
    """State of the Modbus server."""
    def __init__(
        self,
        *,
        state: global___MbusServerState.ValueType = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["state", b"state"]) -> None: ...

global___MbusServerStatus = MbusServerStatus

@typing.final
class MbusServerReq(google.protobuf.message.Message):
    """Message representing an Modbus server request."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    FUNCTION_FIELD_NUMBER: builtins.int
    @property
    def function(self) -> ciot.proto.v2.mbus_pb2.MbusFunctionReq:
        """Function request"""

    def __init__(
        self,
        *,
        function: ciot.proto.v2.mbus_pb2.MbusFunctionReq | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["function", b"function", "type", b"type"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["function", b"function", "type", b"type"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["type", b"type"]) -> typing.Literal["function"] | None: ...

global___MbusServerReq = MbusServerReq

@typing.final
class MbusServerData(google.protobuf.message.Message):
    """Message representing Modbus server data."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    STOP_FIELD_NUMBER: builtins.int
    CONFIG_FIELD_NUMBER: builtins.int
    STATUS_FIELD_NUMBER: builtins.int
    REQUEST_FIELD_NUMBER: builtins.int
    @property
    def stop(self) -> global___MbusServerStop:
        """Stop Modbus server."""

    @property
    def config(self) -> global___MbusServerCfg:
        """Configuration for the Modbus server."""

    @property
    def status(self) -> global___MbusServerStatus:
        """Status of the Modbus server."""

    @property
    def request(self) -> global___MbusServerReq:
        """Modbus server request data."""

    def __init__(
        self,
        *,
        stop: global___MbusServerStop | None = ...,
        config: global___MbusServerCfg | None = ...,
        status: global___MbusServerStatus | None = ...,
        request: global___MbusServerReq | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["config", b"config", "request", b"request", "status", b"status", "stop", b"stop", "type", b"type"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["config", b"config", "request", b"request", "status", b"status", "stop", b"stop", "type", b"type"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["type", b"type"]) -> typing.Literal["stop", "config", "status", "request"] | None: ...

global___MbusServerData = MbusServerData
