"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _MbusError:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _MbusErrorEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_MbusError.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    MBUS_ERROR_NONE: _MbusError.ValueType  # 0
    """No error"""
    MBUS_ERROR_REG_ADDR: _MbusError.ValueType  # 1
    """Invalid register address"""
    MBUS_ERROR_ARG: _MbusError.ValueType  # 2
    """Invalid argument"""
    MBUS_ERROR_PORT_LAYER: _MbusError.ValueType  # 3
    """Port layer error"""
    MBUS_ERROR_NO_RESOURCE: _MbusError.ValueType  # 4
    """No resource error"""
    MBUS_ERROR_IO: _MbusError.ValueType  # 5
    """I/O error"""
    MBUS_ERROR_STATE: _MbusError.ValueType  # 6
    """Protocol stack invalid state error"""
    MBUS_ERROR_TIMEOUT: _MbusError.ValueType  # 7
    """Timeout error"""

class MbusError(_MbusError, metaclass=_MbusErrorEnumTypeWrapper):
    """Enum representing Modbus client error codes."""

MBUS_ERROR_NONE: MbusError.ValueType  # 0
"""No error"""
MBUS_ERROR_REG_ADDR: MbusError.ValueType  # 1
"""Invalid register address"""
MBUS_ERROR_ARG: MbusError.ValueType  # 2
"""Invalid argument"""
MBUS_ERROR_PORT_LAYER: MbusError.ValueType  # 3
"""Port layer error"""
MBUS_ERROR_NO_RESOURCE: MbusError.ValueType  # 4
"""No resource error"""
MBUS_ERROR_IO: MbusError.ValueType  # 5
"""I/O error"""
MBUS_ERROR_STATE: MbusError.ValueType  # 6
"""Protocol stack invalid state error"""
MBUS_ERROR_TIMEOUT: MbusError.ValueType  # 7
"""Timeout error"""
global___MbusError = MbusError

class _MbusFuncCode:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _MbusFuncCodeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_MbusFuncCode.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    MBUS_FUNC_CODE_NONE: _MbusFuncCode.ValueType  # 0
    """No function"""
    MBUS_FUNC_CODE_READ_COILS: _MbusFuncCode.ValueType  # 1
    """Read Coils (0x01)"""
    MBUS_FUNC_CODE_READ_DI: _MbusFuncCode.ValueType  # 2
    """Read Discrete Inputs (0x02)"""
    MBUS_FUNC_CODE_READ_HR: _MbusFuncCode.ValueType  # 3
    """Read Holding Registers (0x03)"""
    MBUS_FUNC_CODE_READ_IR: _MbusFuncCode.ValueType  # 4
    """Read Input Registers (0x04)"""
    MBUS_FUNC_CODE_WRITE_SINGLE_COIL: _MbusFuncCode.ValueType  # 5
    """Write Single Coil (0x05)"""
    MBUS_FUNC_CODE_WRITE_SINGLE_HR: _MbusFuncCode.ValueType  # 6
    """Write Single Holding Register (0x06)"""
    MBUS_FUNC_CODE_WRITE_MULTIPLE_COILS: _MbusFuncCode.ValueType  # 15
    """Write Coils (0x0F)"""
    MBUS_FUNC_CODE_WRITE_MULTIPLE_HR: _MbusFuncCode.ValueType  # 16
    """Write Holding Registers (0x10)"""

class MbusFuncCode(_MbusFuncCode, metaclass=_MbusFuncCodeEnumTypeWrapper):
    """Enum representing Modbus function codes"""

MBUS_FUNC_CODE_NONE: MbusFuncCode.ValueType  # 0
"""No function"""
MBUS_FUNC_CODE_READ_COILS: MbusFuncCode.ValueType  # 1
"""Read Coils (0x01)"""
MBUS_FUNC_CODE_READ_DI: MbusFuncCode.ValueType  # 2
"""Read Discrete Inputs (0x02)"""
MBUS_FUNC_CODE_READ_HR: MbusFuncCode.ValueType  # 3
"""Read Holding Registers (0x03)"""
MBUS_FUNC_CODE_READ_IR: MbusFuncCode.ValueType  # 4
"""Read Input Registers (0x04)"""
MBUS_FUNC_CODE_WRITE_SINGLE_COIL: MbusFuncCode.ValueType  # 5
"""Write Single Coil (0x05)"""
MBUS_FUNC_CODE_WRITE_SINGLE_HR: MbusFuncCode.ValueType  # 6
"""Write Single Holding Register (0x06)"""
MBUS_FUNC_CODE_WRITE_MULTIPLE_COILS: MbusFuncCode.ValueType  # 15
"""Write Coils (0x0F)"""
MBUS_FUNC_CODE_WRITE_MULTIPLE_HR: MbusFuncCode.ValueType  # 16
"""Write Holding Registers (0x10)"""
global___MbusFuncCode = MbusFuncCode

@typing.final
class MbusFunctionReq(google.protobuf.message.Message):
    """Message representing a Modbus function request"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CODE_FIELD_NUMBER: builtins.int
    ADDRESS_FIELD_NUMBER: builtins.int
    DATA_FIELD_NUMBER: builtins.int
    READ_COUNT_FIELD_NUMBER: builtins.int
    MAX_ATTEMPTS_FIELD_NUMBER: builtins.int
    ERROR_FIELD_NUMBER: builtins.int
    code: global___MbusFuncCode.ValueType
    """Modbus function code"""
    address: builtins.int
    """Register/coil start address"""
    read_count: builtins.int
    """Optional values count to read"""
    max_attempts: builtins.int
    """Max attempts"""
    error: builtins.int
    """Error code"""
    @property
    def data(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.int]:
        """Optional written values."""

    def __init__(
        self,
        *,
        code: global___MbusFuncCode.ValueType = ...,
        address: builtins.int = ...,
        data: collections.abc.Iterable[builtins.int] | None = ...,
        read_count: builtins.int = ...,
        max_attempts: builtins.int = ...,
        error: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["address", b"address", "code", b"code", "data", b"data", "error", b"error", "max_attempts", b"max_attempts", "read_count", b"read_count"]) -> None: ...

global___MbusFunctionReq = MbusFunctionReq
