"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import ciot.proto.v2.mbus_pb2
import ciot.proto.v2.uart_pb2
import google.protobuf.descriptor
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _MbusClientState:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _MbusClientStateEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_MbusClientState.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    MBUS_CLIENT_STATE_STOPPED: _MbusClientState.ValueType  # 0
    """Modbus client is stopped."""
    MBUS_CLIENT_STATE_STARTED: _MbusClientState.ValueType  # 1
    """Modbus client is started."""
    MBUS_CLIENT_STATE_ERROR: _MbusClientState.ValueType  # 2
    """Modbus client encountered an error."""

class MbusClientState(_MbusClientState, metaclass=_MbusClientStateEnumTypeWrapper):
    """Enum representing Modbus client states."""

MBUS_CLIENT_STATE_STOPPED: MbusClientState.ValueType  # 0
"""Modbus client is stopped."""
MBUS_CLIENT_STATE_STARTED: MbusClientState.ValueType  # 1
"""Modbus client is started."""
MBUS_CLIENT_STATE_ERROR: MbusClientState.ValueType  # 2
"""Modbus client encountered an error."""
global___MbusClientState = MbusClientState

@typing.final
class MbusClientStop(google.protobuf.message.Message):
    """Message used to stop Modbus client interface"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___MbusClientStop = MbusClientStop

@typing.final
class MbusClientRtuCfg(google.protobuf.message.Message):
    """Message representing Modbus RTU configuration"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SERVER_ID_FIELD_NUMBER: builtins.int
    SERIAL_CFG_FIELD_NUMBER: builtins.int
    server_id: builtins.int
    """Server ID"""
    @property
    def serial_cfg(self) -> ciot.proto.v2.uart_pb2.UartCfg:
        """Serial port config"""

    def __init__(
        self,
        *,
        server_id: builtins.int = ...,
        serial_cfg: ciot.proto.v2.uart_pb2.UartCfg | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["serial_cfg", b"serial_cfg"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["serial_cfg", b"serial_cfg", "server_id", b"server_id"]) -> None: ...

global___MbusClientRtuCfg = MbusClientRtuCfg

@typing.final
class MbusClientTcpCfg(google.protobuf.message.Message):
    """Message representing Modbus TCP configuration"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    IP_FIELD_NUMBER: builtins.int
    PORT_FIELD_NUMBER: builtins.int
    ip: builtins.bytes
    """Server IP Address (4 bytes)"""
    port: builtins.int
    """Server port"""
    def __init__(
        self,
        *,
        ip: builtins.bytes = ...,
        port: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["ip", b"ip", "port", b"port"]) -> None: ...

global___MbusClientTcpCfg = MbusClientTcpCfg

@typing.final
class MbusClientCfg(google.protobuf.message.Message):
    """Message representing Modbus client configuration."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    RTU_FIELD_NUMBER: builtins.int
    TCP_FIELD_NUMBER: builtins.int
    TIMEOUT_FIELD_NUMBER: builtins.int
    timeout: builtins.int
    """Timeout in milliseconds"""
    @property
    def rtu(self) -> global___MbusClientRtuCfg:
        """Modbus RTU configuration"""

    @property
    def tcp(self) -> global___MbusClientTcpCfg:
        """Modbus TCP configuration"""

    def __init__(
        self,
        *,
        rtu: global___MbusClientRtuCfg | None = ...,
        tcp: global___MbusClientTcpCfg | None = ...,
        timeout: builtins.int = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["rtu", b"rtu", "tcp", b"tcp", "type", b"type"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["rtu", b"rtu", "tcp", b"tcp", "timeout", b"timeout", "type", b"type"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["type", b"type"]) -> typing.Literal["rtu", "tcp"] | None: ...

global___MbusClientCfg = MbusClientCfg

@typing.final
class MbusClientStatus(google.protobuf.message.Message):
    """Message representing Modbus client status."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    STATE_FIELD_NUMBER: builtins.int
    ERROR_FIELD_NUMBER: builtins.int
    state: global___MbusClientState.ValueType
    """State of the Modbus client."""
    error: ciot.proto.v2.mbus_pb2.MbusError.ValueType
    """Modbus client error code."""
    def __init__(
        self,
        *,
        state: global___MbusClientState.ValueType = ...,
        error: ciot.proto.v2.mbus_pb2.MbusError.ValueType = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["error", b"error", "state", b"state"]) -> None: ...

global___MbusClientStatus = MbusClientStatus

@typing.final
class MbusClientReq(google.protobuf.message.Message):
    """Message representing an Modbus client request."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    FUNCTION_FIELD_NUMBER: builtins.int
    @property
    def function(self) -> ciot.proto.v2.mbus_pb2.MbusFunctionReq:
        """Function request"""

    def __init__(
        self,
        *,
        function: ciot.proto.v2.mbus_pb2.MbusFunctionReq | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["function", b"function", "type", b"type"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["function", b"function", "type", b"type"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["type", b"type"]) -> typing.Literal["function"] | None: ...

global___MbusClientReq = MbusClientReq

@typing.final
class MbusClientData(google.protobuf.message.Message):
    """Message representing Modbus client data."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    STOP_FIELD_NUMBER: builtins.int
    CONFIG_FIELD_NUMBER: builtins.int
    STATUS_FIELD_NUMBER: builtins.int
    REQUEST_FIELD_NUMBER: builtins.int
    @property
    def stop(self) -> global___MbusClientStop:
        """Message used to stop interface."""

    @property
    def config(self) -> global___MbusClientCfg:
        """Message used to get or set interface config."""

    @property
    def status(self) -> global___MbusClientStatus:
        """Message used to get interface status."""

    @property
    def request(self) -> global___MbusClientReq:
        """Message used to set an request on the interface."""

    def __init__(
        self,
        *,
        stop: global___MbusClientStop | None = ...,
        config: global___MbusClientCfg | None = ...,
        status: global___MbusClientStatus | None = ...,
        request: global___MbusClientReq | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["config", b"config", "request", b"request", "status", b"status", "stop", b"stop", "type", b"type"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["config", b"config", "request", b"request", "status", b"status", "stop", b"stop", "type", b"type"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["type", b"type"]) -> typing.Literal["stop", "config", "status", "request"] | None: ...

global___MbusClientData = MbusClientData
