"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import google.protobuf.descriptor
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _MqttClientState:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _MqttClientStateEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_MqttClientState.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    MQTT_CLIENT_STATE_DISCONNECTED: _MqttClientState.ValueType  # 0
    """The MQTT client is disconnected."""
    MQTT_CLIENT_STATE_CONNECTING: _MqttClientState.ValueType  # 1
    """The MQTT client is connecting."""
    MQTT_CLIENT_STATE_DISCONNECTING: _MqttClientState.ValueType  # 2
    """The MQTT client is disconnecting."""
    MQTT_CLIENT_STATE_CONNECTED: _MqttClientState.ValueType  # 3
    """The MQTT client is connected."""
    MQTT_CLIENT_STATE_ERROR: _MqttClientState.ValueType  # 4
    """The MQTT client encountered an error."""

class MqttClientState(_MqttClientState, metaclass=_MqttClientStateEnumTypeWrapper):
    """Enum representing the state of the MQTT client."""

MQTT_CLIENT_STATE_DISCONNECTED: MqttClientState.ValueType  # 0
"""The MQTT client is disconnected."""
MQTT_CLIENT_STATE_CONNECTING: MqttClientState.ValueType  # 1
"""The MQTT client is connecting."""
MQTT_CLIENT_STATE_DISCONNECTING: MqttClientState.ValueType  # 2
"""The MQTT client is disconnecting."""
MQTT_CLIENT_STATE_CONNECTED: MqttClientState.ValueType  # 3
"""The MQTT client is connected."""
MQTT_CLIENT_STATE_ERROR: MqttClientState.ValueType  # 4
"""The MQTT client encountered an error."""
global___MqttClientState = MqttClientState

class _MqttClientReqType:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _MqttClientReqTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_MqttClientReqType.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    MQTT_CLIENT_REQ_TYPE_UNKOWN: _MqttClientReqType.ValueType  # 0
    """Unknown MQTT request type."""
    MQTT_CLIENT_REQ_TYPE_PUBLISH: _MqttClientReqType.ValueType  # 1
    """MQTT publish request."""
    MQTT_CLIENT_REQ_TYPE_SUBSCRIBE: _MqttClientReqType.ValueType  # 2
    """MQTT subscribe request."""

class MqttClientReqType(_MqttClientReqType, metaclass=_MqttClientReqTypeEnumTypeWrapper):
    """Enum representing different types of MQTT client requests."""

MQTT_CLIENT_REQ_TYPE_UNKOWN: MqttClientReqType.ValueType  # 0
"""Unknown MQTT request type."""
MQTT_CLIENT_REQ_TYPE_PUBLISH: MqttClientReqType.ValueType  # 1
"""MQTT publish request."""
MQTT_CLIENT_REQ_TYPE_SUBSCRIBE: MqttClientReqType.ValueType  # 2
"""MQTT subscribe request."""
global___MqttClientReqType = MqttClientReqType

class _MqttClientBrokerKind:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _MqttClientBrokerKindEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_MqttClientBrokerKind.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    MQTT_CLIENT_BROKER_KIND_DEFAULT: _MqttClientBrokerKind.ValueType  # 0
    """Default used in common mqtt connections"""
    MQTT_CLIENT_BROKER_KIND_SSL_1_2: _MqttClientBrokerKind.ValueType  # 1
    """SSL v1.2 required"""
    MQTT_CLIENT_BROKER_KIND_SSL_1_3: _MqttClientBrokerKind.ValueType  # 2
    """SSL v1.3 required"""
    MQTT_CLIENT_BROKER_KIND_AWS: _MqttClientBrokerKind.ValueType  # 3
    """AWS authentication required"""
    MQTT_CLIENT_BROKER_KIND_AZURE: _MqttClientBrokerKind.ValueType  # 4
    """AZURE authentication required"""

class MqttClientBrokerKind(_MqttClientBrokerKind, metaclass=_MqttClientBrokerKindEnumTypeWrapper):
    """Enum representing different MQTT Broker kinds"""

MQTT_CLIENT_BROKER_KIND_DEFAULT: MqttClientBrokerKind.ValueType  # 0
"""Default used in common mqtt connections"""
MQTT_CLIENT_BROKER_KIND_SSL_1_2: MqttClientBrokerKind.ValueType  # 1
"""SSL v1.2 required"""
MQTT_CLIENT_BROKER_KIND_SSL_1_3: MqttClientBrokerKind.ValueType  # 2
"""SSL v1.3 required"""
MQTT_CLIENT_BROKER_KIND_AWS: MqttClientBrokerKind.ValueType  # 3
"""AWS authentication required"""
MQTT_CLIENT_BROKER_KIND_AZURE: MqttClientBrokerKind.ValueType  # 4
"""AZURE authentication required"""
global___MqttClientBrokerKind = MqttClientBrokerKind

@typing.final
class MqttClientError(google.protobuf.message.Message):
    """Message representing error details for the MQTT client."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TLS_LAST_ERR_FIELD_NUMBER: builtins.int
    TLS_STACK_ERR_FIELD_NUMBER: builtins.int
    TLS_CERT_VERIFY_FLAGS_FIELD_NUMBER: builtins.int
    TYPE_FIELD_NUMBER: builtins.int
    CODE_FIELD_NUMBER: builtins.int
    TRANSPORT_SOCK_FIELD_NUMBER: builtins.int
    tls_last_err: builtins.int
    """TLS last error code."""
    tls_stack_err: builtins.int
    """TLS stack error code."""
    tls_cert_verify_flags: builtins.int
    """TLS certificate verification flags."""
    type: builtins.int
    """Type of the error."""
    code: builtins.int
    """Error code."""
    transport_sock: builtins.int
    """Transport socket error."""
    def __init__(
        self,
        *,
        tls_last_err: builtins.int = ...,
        tls_stack_err: builtins.int = ...,
        tls_cert_verify_flags: builtins.int = ...,
        type: builtins.int = ...,
        code: builtins.int = ...,
        transport_sock: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["code", b"code", "tls_cert_verify_flags", b"tls_cert_verify_flags", "tls_last_err", b"tls_last_err", "tls_stack_err", b"tls_stack_err", "transport_sock", b"transport_sock", "type", b"type"]) -> None: ...

global___MqttClientError = MqttClientError

@typing.final
class MqttClientTopicsCfg(google.protobuf.message.Message):
    """Message representing configuration for MQTT client topics."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PUB_FIELD_NUMBER: builtins.int
    SUB_FIELD_NUMBER: builtins.int
    pub: builtins.str
    """Topic used to publish data"""
    sub: builtins.str
    """Topic used to receive data."""
    def __init__(
        self,
        *,
        pub: builtins.str = ...,
        sub: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["pub", b"pub", "sub", b"sub"]) -> None: ...

global___MqttClientTopicsCfg = MqttClientTopicsCfg

@typing.final
class MqttClientLastWill(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TOPIC_FIELD_NUMBER: builtins.int
    PAYLOAD_FIELD_NUMBER: builtins.int
    QOS_FIELD_NUMBER: builtins.int
    RETAIN_FIELD_NUMBER: builtins.int
    topic: builtins.str
    """Topic for the last will message."""
    payload: builtins.bytes
    """Payload for the last will message."""
    qos: builtins.int
    """Quality of Service level for the last will message."""
    retain: builtins.bool
    """Retain flag for the last will message."""
    def __init__(
        self,
        *,
        topic: builtins.str = ...,
        payload: builtins.bytes = ...,
        qos: builtins.int = ...,
        retain: builtins.bool = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["payload", b"payload", "qos", b"qos", "retain", b"retain", "topic", b"topic"]) -> None: ...

global___MqttClientLastWill = MqttClientLastWill

@typing.final
class MqttClientStop(google.protobuf.message.Message):
    """Message used to stop MQTT client interface"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___MqttClientStop = MqttClientStop

@typing.final
class MqttClientSessionCfg(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CLEAN_SESSION_FIELD_NUMBER: builtins.int
    KEEP_ALIVE_FIELD_NUMBER: builtins.int
    clean_session: builtins.bool
    """Clean session flag"""
    keep_alive: builtins.int
    """Keep alive interval in seconds"""
    def __init__(
        self,
        *,
        clean_session: builtins.bool = ...,
        keep_alive: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["clean_session", b"clean_session", "keep_alive", b"keep_alive"]) -> None: ...

global___MqttClientSessionCfg = MqttClientSessionCfg

@typing.final
class MqttClientCfg(google.protobuf.message.Message):
    """Message representing configuration for the MQTT client."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CLIENT_ID_FIELD_NUMBER: builtins.int
    URL_FIELD_NUMBER: builtins.int
    USER_FIELD_NUMBER: builtins.int
    PASSWORD_FIELD_NUMBER: builtins.int
    QOS_FIELD_NUMBER: builtins.int
    TOPICS_FIELD_NUMBER: builtins.int
    BROKER_KIND_FIELD_NUMBER: builtins.int
    LAST_WILL_FIELD_NUMBER: builtins.int
    SESSION_FIELD_NUMBER: builtins.int
    client_id: builtins.str
    """Client ID for MQTT connection."""
    url: builtins.str
    """URL for MQTT connection."""
    user: builtins.str
    """Username for MQTT authentication."""
    password: builtins.str
    """Password for MQTT authentication."""
    qos: builtins.int
    """Quality of Service level for MQTT communication."""
    broker_kind: global___MqttClientBrokerKind.ValueType
    """MQTT broker kind."""
    @property
    def topics(self) -> global___MqttClientTopicsCfg:
        """Topics configuration for MQTT communication."""

    @property
    def last_will(self) -> global___MqttClientLastWill:
        """Last will message configuration."""

    @property
    def session(self) -> global___MqttClientSessionCfg:
        """Session configuration."""

    def __init__(
        self,
        *,
        client_id: builtins.str = ...,
        url: builtins.str = ...,
        user: builtins.str = ...,
        password: builtins.str = ...,
        qos: builtins.int = ...,
        topics: global___MqttClientTopicsCfg | None = ...,
        broker_kind: global___MqttClientBrokerKind.ValueType = ...,
        last_will: global___MqttClientLastWill | None = ...,
        session: global___MqttClientSessionCfg | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_last_will", b"_last_will", "_session", b"_session", "last_will", b"last_will", "session", b"session", "topics", b"topics"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_last_will", b"_last_will", "_session", b"_session", "broker_kind", b"broker_kind", "client_id", b"client_id", "last_will", b"last_will", "password", b"password", "qos", b"qos", "session", b"session", "topics", b"topics", "url", b"url", "user", b"user"]) -> None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_last_will", b"_last_will"]) -> typing.Literal["last_will"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_session", b"_session"]) -> typing.Literal["session"] | None: ...

global___MqttClientCfg = MqttClientCfg

@typing.final
class MqttClientStatus(google.protobuf.message.Message):
    """Message representing status information for the MQTT client."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    STATE_FIELD_NUMBER: builtins.int
    CONN_COUNT_FIELD_NUMBER: builtins.int
    DATA_RATE_FIELD_NUMBER: builtins.int
    LAST_MSG_TIME_FIELD_NUMBER: builtins.int
    ERROR_FIELD_NUMBER: builtins.int
    state: global___MqttClientState.ValueType
    """State of the MQTT client."""
    conn_count: builtins.int
    """Connection count."""
    data_rate: builtins.int
    """Data rate."""
    last_msg_time: builtins.int
    """Timestamp of the last message."""
    @property
    def error(self) -> global___MqttClientError:
        """Error details for the MQTT client."""

    def __init__(
        self,
        *,
        state: global___MqttClientState.ValueType = ...,
        conn_count: builtins.int = ...,
        data_rate: builtins.int = ...,
        last_msg_time: builtins.int = ...,
        error: global___MqttClientError | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["error", b"error"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["conn_count", b"conn_count", "data_rate", b"data_rate", "error", b"error", "last_msg_time", b"last_msg_time", "state", b"state"]) -> None: ...

global___MqttClientStatus = MqttClientStatus

@typing.final
class MqttClientReqPublish(google.protobuf.message.Message):
    """Message representing a publish request for the MQTT client."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TOPIC_FIELD_NUMBER: builtins.int
    PAYLOAD_FIELD_NUMBER: builtins.int
    QOS_FIELD_NUMBER: builtins.int
    topic: builtins.str
    """Topic for publishing."""
    payload: builtins.bytes
    """Message payload."""
    qos: builtins.int
    """Quality of Service level for the publish request."""
    def __init__(
        self,
        *,
        topic: builtins.str = ...,
        payload: builtins.bytes = ...,
        qos: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["payload", b"payload", "qos", b"qos", "topic", b"topic"]) -> None: ...

global___MqttClientReqPublish = MqttClientReqPublish

@typing.final
class MqttClientReqSubscribe(google.protobuf.message.Message):
    """Message representing a subscribe request for the MQTT client."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TOPIC_FIELD_NUMBER: builtins.int
    QOS_FIELD_NUMBER: builtins.int
    topic: builtins.str
    """Topic to subscribe to."""
    qos: builtins.int
    """Quality of Service level for the subscribe request."""
    def __init__(
        self,
        *,
        topic: builtins.str = ...,
        qos: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["qos", b"qos", "topic", b"topic"]) -> None: ...

global___MqttClientReqSubscribe = MqttClientReqSubscribe

@typing.final
class MqttClientReq(google.protobuf.message.Message):
    """Message representing a request for the MQTT client."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PUBLISH_FIELD_NUMBER: builtins.int
    SUBSCRIBE_FIELD_NUMBER: builtins.int
    @property
    def publish(self) -> global___MqttClientReqPublish:
        """Publish request."""

    @property
    def subscribe(self) -> global___MqttClientReqSubscribe:
        """Subscribe request."""

    def __init__(
        self,
        *,
        publish: global___MqttClientReqPublish | None = ...,
        subscribe: global___MqttClientReqSubscribe | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["publish", b"publish", "subscribe", b"subscribe", "type", b"type"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["publish", b"publish", "subscribe", b"subscribe", "type", b"type"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["type", b"type"]) -> typing.Literal["publish", "subscribe"] | None: ...

global___MqttClientReq = MqttClientReq

@typing.final
class MqttClientData(google.protobuf.message.Message):
    """Message representing data for the MQTT client."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    STOP_FIELD_NUMBER: builtins.int
    CONFIG_FIELD_NUMBER: builtins.int
    STATUS_FIELD_NUMBER: builtins.int
    REQUEST_FIELD_NUMBER: builtins.int
    @property
    def stop(self) -> global___MqttClientStop:
        """Stop MQTT client."""

    @property
    def config(self) -> global___MqttClientCfg:
        """Configuration for the MQTT client."""

    @property
    def status(self) -> global___MqttClientStatus:
        """Status of the MQTT client."""

    @property
    def request(self) -> global___MqttClientReq:
        """MQTT client request data."""

    def __init__(
        self,
        *,
        stop: global___MqttClientStop | None = ...,
        config: global___MqttClientCfg | None = ...,
        status: global___MqttClientStatus | None = ...,
        request: global___MqttClientReq | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["config", b"config", "request", b"request", "status", b"status", "stop", b"stop", "type", b"type"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["config", b"config", "request", b"request", "status", b"status", "stop", b"stop", "type", b"type"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["type", b"type"]) -> typing.Literal["stop", "config", "status", "request"] | None: ...

global___MqttClientData = MqttClientData
