"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import ciot.proto.v2.ble_adv_pb2
import ciot.proto.v2.ble_pb2
import ciot.proto.v2.ble_scn_pb2
import ciot.proto.v2.ciot_pb2
import ciot.proto.v2.dfu_pb2
import ciot.proto.v2.gpio_pb2
import ciot.proto.v2.http_client_pb2
import ciot.proto.v2.http_server_pb2
import ciot.proto.v2.iface_pb2
import ciot.proto.v2.logger_pb2
import ciot.proto.v2.mbus_client_pb2
import ciot.proto.v2.mbus_server_pb2
import ciot.proto.v2.mqtt_client_pb2
import ciot.proto.v2.ntp_pb2
import ciot.proto.v2.ota_pb2
import ciot.proto.v2.storage_pb2
import ciot.proto.v2.sys_pb2
import ciot.proto.v2.tcp_pb2
import ciot.proto.v2.uart_pb2
import ciot.proto.v2.usb_pb2
import ciot.proto.v2.wifi_pb2
import google.protobuf.descriptor
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class MsgData(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    COMMON_FIELD_NUMBER: builtins.int
    GET_DATA_FIELD_NUMBER: builtins.int
    CIOT_FIELD_NUMBER: builtins.int
    SYS_FIELD_NUMBER: builtins.int
    HTTP_CLIENT_FIELD_NUMBER: builtins.int
    HTTP_SERVER_FIELD_NUMBER: builtins.int
    MQTT_CLIENT_FIELD_NUMBER: builtins.int
    UART_FIELD_NUMBER: builtins.int
    NTP_FIELD_NUMBER: builtins.int
    BLE_ADV_FIELD_NUMBER: builtins.int
    BLE_SCN_FIELD_NUMBER: builtins.int
    BLE_FIELD_NUMBER: builtins.int
    DFU_FIELD_NUMBER: builtins.int
    GPIO_FIELD_NUMBER: builtins.int
    OTA_FIELD_NUMBER: builtins.int
    STORAGE_FIELD_NUMBER: builtins.int
    ETH_FIELD_NUMBER: builtins.int
    WIFI_FIELD_NUMBER: builtins.int
    LOG_FIELD_NUMBER: builtins.int
    USB_FIELD_NUMBER: builtins.int
    MBUS_CLIENT_FIELD_NUMBER: builtins.int
    MBUS_SERVER_FIELD_NUMBER: builtins.int
    @property
    def common(self) -> ciot.proto.v2.iface_pb2.Common:
        """CustomType custom = 1;        // Custom data.
        Common data.
        """

    @property
    def get_data(self) -> ciot.proto.v2.iface_pb2.GetData:
        """Get data request."""

    @property
    def ciot(self) -> ciot.proto.v2.ciot_pb2.Data:
        """CioT data."""

    @property
    def sys(self) -> ciot.proto.v2.sys_pb2.SysData:
        """System data."""

    @property
    def http_client(self) -> ciot.proto.v2.http_client_pb2.HttpClientData:
        """HTTP Client data."""

    @property
    def http_server(self) -> ciot.proto.v2.http_server_pb2.HttpServerData:
        """HTTP Server data."""

    @property
    def mqtt_client(self) -> ciot.proto.v2.mqtt_client_pb2.MqttClientData:
        """MQTT Client data."""

    @property
    def uart(self) -> ciot.proto.v2.uart_pb2.UartData:
        """UART data."""

    @property
    def ntp(self) -> ciot.proto.v2.ntp_pb2.NtpData:
        """NTP data."""

    @property
    def ble_adv(self) -> ciot.proto.v2.ble_adv_pb2.BleAdvData:
        """BLE adv data."""

    @property
    def ble_scn(self) -> ciot.proto.v2.ble_scn_pb2.BleScnData:
        """BLE scanner data."""

    @property
    def ble(self) -> ciot.proto.v2.ble_pb2.BleData:
        """BLE data."""

    @property
    def dfu(self) -> ciot.proto.v2.dfu_pb2.DfuData:
        """DFU data."""

    @property
    def gpio(self) -> ciot.proto.v2.gpio_pb2.GpioData:
        """GPIO data."""

    @property
    def ota(self) -> ciot.proto.v2.ota_pb2.OtaData:
        """OTA data."""

    @property
    def storage(self) -> ciot.proto.v2.storage_pb2.StorageData:
        """Storage data."""

    @property
    def eth(self) -> ciot.proto.v2.tcp_pb2.TcpData:
        """Ethernet data."""

    @property
    def wifi(self) -> ciot.proto.v2.wifi_pb2.WifiData:
        """WiFi data."""

    @property
    def log(self) -> ciot.proto.v2.logger_pb2.LogData:
        """Log data."""

    @property
    def usb(self) -> ciot.proto.v2.usb_pb2.UsbData:
        """USB data."""

    @property
    def mbus_client(self) -> ciot.proto.v2.mbus_client_pb2.MbusClientData:
        """Modbus client data."""

    @property
    def mbus_server(self) -> ciot.proto.v2.mbus_server_pb2.MbusServerData:
        """Modbus server data."""

    def __init__(
        self,
        *,
        common: ciot.proto.v2.iface_pb2.Common | None = ...,
        get_data: ciot.proto.v2.iface_pb2.GetData | None = ...,
        ciot: ciot.proto.v2.ciot_pb2.Data | None = ...,
        sys: ciot.proto.v2.sys_pb2.SysData | None = ...,
        http_client: ciot.proto.v2.http_client_pb2.HttpClientData | None = ...,
        http_server: ciot.proto.v2.http_server_pb2.HttpServerData | None = ...,
        mqtt_client: ciot.proto.v2.mqtt_client_pb2.MqttClientData | None = ...,
        uart: ciot.proto.v2.uart_pb2.UartData | None = ...,
        ntp: ciot.proto.v2.ntp_pb2.NtpData | None = ...,
        ble_adv: ciot.proto.v2.ble_adv_pb2.BleAdvData | None = ...,
        ble_scn: ciot.proto.v2.ble_scn_pb2.BleScnData | None = ...,
        ble: ciot.proto.v2.ble_pb2.BleData | None = ...,
        dfu: ciot.proto.v2.dfu_pb2.DfuData | None = ...,
        gpio: ciot.proto.v2.gpio_pb2.GpioData | None = ...,
        ota: ciot.proto.v2.ota_pb2.OtaData | None = ...,
        storage: ciot.proto.v2.storage_pb2.StorageData | None = ...,
        eth: ciot.proto.v2.tcp_pb2.TcpData | None = ...,
        wifi: ciot.proto.v2.wifi_pb2.WifiData | None = ...,
        log: ciot.proto.v2.logger_pb2.LogData | None = ...,
        usb: ciot.proto.v2.usb_pb2.UsbData | None = ...,
        mbus_client: ciot.proto.v2.mbus_client_pb2.MbusClientData | None = ...,
        mbus_server: ciot.proto.v2.mbus_server_pb2.MbusServerData | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["ble", b"ble", "ble_adv", b"ble_adv", "ble_scn", b"ble_scn", "ciot", b"ciot", "common", b"common", "dfu", b"dfu", "eth", b"eth", "get_data", b"get_data", "gpio", b"gpio", "http_client", b"http_client", "http_server", b"http_server", "log", b"log", "mbus_client", b"mbus_client", "mbus_server", b"mbus_server", "mqtt_client", b"mqtt_client", "ntp", b"ntp", "ota", b"ota", "storage", b"storage", "sys", b"sys", "type", b"type", "uart", b"uart", "usb", b"usb", "wifi", b"wifi"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["ble", b"ble", "ble_adv", b"ble_adv", "ble_scn", b"ble_scn", "ciot", b"ciot", "common", b"common", "dfu", b"dfu", "eth", b"eth", "get_data", b"get_data", "gpio", b"gpio", "http_client", b"http_client", "http_server", b"http_server", "log", b"log", "mbus_client", b"mbus_client", "mbus_server", b"mbus_server", "mqtt_client", b"mqtt_client", "ntp", b"ntp", "ota", b"ota", "storage", b"storage", "sys", b"sys", "type", b"type", "uart", b"uart", "usb", b"usb", "wifi", b"wifi"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["type", b"type"]) -> typing.Literal["common", "get_data", "ciot", "sys", "http_client", "http_server", "mqtt_client", "uart", "ntp", "ble_adv", "ble_scn", "ble", "dfu", "gpio", "ota", "storage", "eth", "wifi", "log", "usb", "mbus_client", "mbus_server"] | None: ...

global___MsgData = MsgData
