"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import ciot.proto.v2.errors_pb2
import ciot.proto.v2.iface_pb2
import ciot.proto.v2.msg_data_pb2
import google.protobuf.descriptor
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _MsgType:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _MsgTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_MsgType.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    MSG_TYPE_REQUEST: _MsgType.ValueType  # 0
    """Request message."""
    MSG_TYPE_RESPONSE: _MsgType.ValueType  # 1
    """Response message."""
    MSG_TYPE_NOTIFICATION: _MsgType.ValueType  # 2
    """Notification message."""

class MsgType(_MsgType, metaclass=_MsgTypeEnumTypeWrapper): ...

MSG_TYPE_REQUEST: MsgType.ValueType  # 0
"""Request message."""
MSG_TYPE_RESPONSE: MsgType.ValueType  # 1
"""Response message."""
MSG_TYPE_NOTIFICATION: MsgType.ValueType  # 2
"""Notification message."""
global___MsgType = MsgType

class _ProxyState:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _ProxyStateEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_ProxyState.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    PROXY_STATE_PENDING: _ProxyState.ValueType  # 0
    """Proxy is pending. CIoT will send message using the proxy interface."""
    PROXY_STATE_READY_TO_PROCESS: _ProxyState.ValueType  # 1
    """Proxy is ready. CIoT will process the message locally."""
    PROXY_STATE_SENT: _ProxyState.ValueType  # 2
    """Proxy is sent. CIoT will not process the message locally."""

class ProxyState(_ProxyState, metaclass=_ProxyStateEnumTypeWrapper): ...

PROXY_STATE_PENDING: ProxyState.ValueType  # 0
"""Proxy is pending. CIoT will send message using the proxy interface."""
PROXY_STATE_READY_TO_PROCESS: ProxyState.ValueType  # 1
"""Proxy is ready. CIoT will process the message locally."""
PROXY_STATE_SENT: ProxyState.ValueType  # 2
"""Proxy is sent. CIoT will not process the message locally."""
global___ProxyState = ProxyState

@typing.final
class Proxy(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    IFACE_FIELD_NUMBER: builtins.int
    STATE_FIELD_NUMBER: builtins.int
    SAVE_FIELD_NUMBER: builtins.int
    state: global___ProxyState.ValueType
    """Proxy state."""
    save: builtins.bool
    """Use ciot to save msg data"""
    @property
    def iface(self) -> ciot.proto.v2.iface_pb2.IfaceInfo:
        """Proxy interface information."""

    def __init__(
        self,
        *,
        iface: ciot.proto.v2.iface_pb2.IfaceInfo | None = ...,
        state: global___ProxyState.ValueType = ...,
        save: builtins.bool = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["iface", b"iface"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["iface", b"iface", "save", b"save", "state", b"state"]) -> None: ...

global___Proxy = Proxy

@typing.final
class Msg(google.protobuf.message.Message):
    """Represents an CioT message"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    IFACE_FIELD_NUMBER: builtins.int
    ERROR_FIELD_NUMBER: builtins.int
    DATA_FIELD_NUMBER: builtins.int
    TYPE_FIELD_NUMBER: builtins.int
    PROXY_FIELD_NUMBER: builtins.int
    id: builtins.int
    """Message ID."""
    error: ciot.proto.v2.errors_pb2.Err.ValueType
    """Error code."""
    type: global___MsgType.ValueType
    """Message type."""
    @property
    def iface(self) -> ciot.proto.v2.iface_pb2.IfaceInfo:
        """Interface information."""

    @property
    def data(self) -> ciot.proto.v2.msg_data_pb2.MsgData:
        """Message data."""

    @property
    def proxy(self) -> global___Proxy:
        """Proxy information."""

    def __init__(
        self,
        *,
        id: builtins.int = ...,
        iface: ciot.proto.v2.iface_pb2.IfaceInfo | None = ...,
        error: ciot.proto.v2.errors_pb2.Err.ValueType = ...,
        data: ciot.proto.v2.msg_data_pb2.MsgData | None = ...,
        type: global___MsgType.ValueType = ...,
        proxy: global___Proxy | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_proxy", b"_proxy", "data", b"data", "iface", b"iface", "proxy", b"proxy"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_proxy", b"_proxy", "data", b"data", "error", b"error", "id", b"id", "iface", b"iface", "proxy", b"proxy", "type", b"type"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["_proxy", b"_proxy"]) -> typing.Literal["proxy"] | None: ...

global___Msg = Msg
