# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ciot/proto/v2/msg.proto
# Protobuf Python Version: 6.30.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    0,
    '',
    'ciot/proto/v2/msg.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ciot.proto.v2 import iface_pb2 as ciot_dot_proto_dot_v2_dot_iface__pb2
from ciot.proto.v2 import msg_data_pb2 as ciot_dot_proto_dot_v2_dot_msg__data__pb2
from ciot.proto.v2 import errors_pb2 as ciot_dot_proto_dot_v2_dot_errors__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17\x63iot/proto/v2/msg.proto\x12\x04\x43iot\x1a\x19\x63iot/proto/v2/iface.proto\x1a\x1c\x63iot/proto/v2/msg_data.proto\x1a\x1a\x63iot/proto/v2/errors.proto\"V\n\x05Proxy\x12\x1e\n\x05iface\x18\x01 \x01(\x0b\x32\x0f.Ciot.IfaceInfo\x12\x1f\n\x05state\x18\x02 \x01(\x0e\x32\x10.Ciot.ProxyState\x12\x0c\n\x04save\x18\x03 \x01(\x08\"\xb0\x01\n\x03Msg\x12\n\n\x02id\x18\x01 \x01(\r\x12\x1e\n\x05iface\x18\x02 \x01(\x0b\x32\x0f.Ciot.IfaceInfo\x12\x18\n\x05\x65rror\x18\x03 \x01(\x0e\x32\t.Ciot.Err\x12\x1b\n\x04\x64\x61ta\x18\x04 \x01(\x0b\x32\r.Ciot.MsgData\x12\x1b\n\x04type\x18\x05 \x01(\x0e\x32\r.Ciot.MsgType\x12\x1f\n\x05proxy\x18\x06 \x01(\x0b\x32\x0b.Ciot.ProxyH\x00\x88\x01\x01\x42\x08\n\x06_proxy*Q\n\x07MsgType\x12\x14\n\x10MSG_TYPE_REQUEST\x10\x00\x12\x15\n\x11MSG_TYPE_RESPONSE\x10\x01\x12\x19\n\x15MSG_TYPE_NOTIFICATION\x10\x02*]\n\nProxyState\x12\x17\n\x13PROXY_STATE_PENDING\x10\x00\x12 \n\x1cPROXY_STATE_READY_TO_PROCESS\x10\x01\x12\x14\n\x10PROXY_STATE_SENT\x10\x02\x42\x11\xaa\x02\x0e\x43iot.Protos.V2b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ciot.proto.v2.msg_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002\016Ciot.Protos.V2'
  _globals['_MSGTYPE']._serialized_start=385
  _globals['_MSGTYPE']._serialized_end=466
  _globals['_PROXYSTATE']._serialized_start=468
  _globals['_PROXYSTATE']._serialized_end=561
  _globals['_PROXY']._serialized_start=118
  _globals['_PROXY']._serialized_end=204
  _globals['_MSG']._serialized_start=207
  _globals['_MSG']._serialized_end=383
# @@protoc_insertion_point(module_scope)
