"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import google.protobuf.descriptor
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _NtpState:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _NtpStateEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_NtpState.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    NTP_STATE_RESET: _NtpState.ValueType  # 0
    """NTP state: reset."""
    NTP_STATE_COMPLETED: _NtpState.ValueType  # 1
    """NTP state: completed."""
    NTP_STATE_IN_PROGRESS: _NtpState.ValueType  # 2
    """NTP state: in progress."""

class NtpState(_NtpState, metaclass=_NtpStateEnumTypeWrapper):
    """Enum representing the state of the NTP module."""

NTP_STATE_RESET: NtpState.ValueType  # 0
"""NTP state: reset."""
NTP_STATE_COMPLETED: NtpState.ValueType  # 1
"""NTP state: completed."""
NTP_STATE_IN_PROGRESS: NtpState.ValueType  # 2
"""NTP state: in progress."""
global___NtpState = NtpState

@typing.final
class NtpStop(google.protobuf.message.Message):
    """Message used to stop NTP client"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___NtpStop = NtpStop

@typing.final
class NtpCfg(google.protobuf.message.Message):
    """Message representing configuration for the NTP module."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    OP_MODE_FIELD_NUMBER: builtins.int
    SYNC_MODE_FIELD_NUMBER: builtins.int
    SYNC_INTERVAL_FIELD_NUMBER: builtins.int
    TIMEZONE_FIELD_NUMBER: builtins.int
    SERVER1_FIELD_NUMBER: builtins.int
    SERVER2_FIELD_NUMBER: builtins.int
    SERVER3_FIELD_NUMBER: builtins.int
    op_mode: builtins.int
    """Operation mode for NTP."""
    sync_mode: builtins.int
    """Synchronization mode for NTP."""
    sync_interval: builtins.int
    """Synchronization interval for NTP."""
    timezone: builtins.str
    """Timezone for NTP."""
    server1: builtins.str
    """NTP server 1."""
    server2: builtins.str
    """NTP server 2."""
    server3: builtins.str
    """NTP server 3."""
    def __init__(
        self,
        *,
        op_mode: builtins.int = ...,
        sync_mode: builtins.int = ...,
        sync_interval: builtins.int = ...,
        timezone: builtins.str = ...,
        server1: builtins.str = ...,
        server2: builtins.str = ...,
        server3: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["op_mode", b"op_mode", "server1", b"server1", "server2", b"server2", "server3", b"server3", "sync_interval", b"sync_interval", "sync_mode", b"sync_mode", "timezone", b"timezone"]) -> None: ...

global___NtpCfg = NtpCfg

@typing.final
class NtpStatus(google.protobuf.message.Message):
    """Message representing status for the NTP module."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    STATE_FIELD_NUMBER: builtins.int
    LAST_SYNC_FIELD_NUMBER: builtins.int
    SYNC_COUNT_FIELD_NUMBER: builtins.int
    INIT_FIELD_NUMBER: builtins.int
    SYNC_FIELD_NUMBER: builtins.int
    state: global___NtpState.ValueType
    """State of the NTP module."""
    last_sync: builtins.int
    """Timestamp of the last synchronization."""
    sync_count: builtins.int
    """Number of synchronizations."""
    init: builtins.bool
    """Initialization status."""
    sync: builtins.bool
    """Synchronization status."""
    def __init__(
        self,
        *,
        state: global___NtpState.ValueType = ...,
        last_sync: builtins.int = ...,
        sync_count: builtins.int = ...,
        init: builtins.bool = ...,
        sync: builtins.bool = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["init", b"init", "last_sync", b"last_sync", "state", b"state", "sync", b"sync", "sync_count", b"sync_count"]) -> None: ...

global___NtpStatus = NtpStatus

@typing.final
class NtpReq(google.protobuf.message.Message):
    """Message representing an NTP request."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___NtpReq = NtpReq

@typing.final
class NtpData(google.protobuf.message.Message):
    """Message representing data for the NTP module."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    STOP_FIELD_NUMBER: builtins.int
    CONFIG_FIELD_NUMBER: builtins.int
    STATUS_FIELD_NUMBER: builtins.int
    REQUEST_FIELD_NUMBER: builtins.int
    @property
    def stop(self) -> global___NtpStop:
        """Stop NTP client."""

    @property
    def config(self) -> global___NtpCfg:
        """Configuration for the NTP module."""

    @property
    def status(self) -> global___NtpStatus:
        """Status of the NTP module."""

    @property
    def request(self) -> global___NtpReq:
        """NTP request data."""

    def __init__(
        self,
        *,
        stop: global___NtpStop | None = ...,
        config: global___NtpCfg | None = ...,
        status: global___NtpStatus | None = ...,
        request: global___NtpReq | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["config", b"config", "request", b"request", "status", b"status", "stop", b"stop", "type", b"type"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["config", b"config", "request", b"request", "status", b"status", "stop", b"stop", "type", b"type"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["type", b"type"]) -> typing.Literal["stop", "config", "status", "request"] | None: ...

global___NtpData = NtpData
