# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ciot/proto/v2/ntp.proto
# Protobuf Python Version: 6.30.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    0,
    '',
    'ciot/proto/v2/ntp.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17\x63iot/proto/v2/ntp.proto\x12\x04\x43iot\"\t\n\x07NtpStop\"\x88\x01\n\x06NtpCfg\x12\x0f\n\x07op_mode\x18\x01 \x01(\r\x12\x11\n\tsync_mode\x18\x02 \x01(\r\x12\x15\n\rsync_interval\x18\x03 \x01(\r\x12\x10\n\x08timezone\x18\x04 \x01(\t\x12\x0f\n\x07server1\x18\x05 \x01(\t\x12\x0f\n\x07server2\x18\x06 \x01(\t\x12\x0f\n\x07server3\x18\x07 \x01(\t\"m\n\tNtpStatus\x12\x1d\n\x05state\x18\x01 \x01(\x0e\x32\x0e.Ciot.NtpState\x12\x11\n\tlast_sync\x18\x02 \x01(\x04\x12\x12\n\nsync_count\x18\x03 \x01(\r\x12\x0c\n\x04init\x18\x04 \x01(\x08\x12\x0c\n\x04sync\x18\x05 \x01(\x08\"\x08\n\x06NtpReq\"\x94\x01\n\x07NtpData\x12\x1d\n\x04stop\x18\x01 \x01(\x0b\x32\r.Ciot.NtpStopH\x00\x12\x1e\n\x06\x63onfig\x18\x02 \x01(\x0b\x32\x0c.Ciot.NtpCfgH\x00\x12!\n\x06status\x18\x03 \x01(\x0b\x32\x0f.Ciot.NtpStatusH\x00\x12\x1f\n\x07request\x18\x04 \x01(\x0b\x32\x0c.Ciot.NtpReqH\x00\x42\x06\n\x04type*S\n\x08NtpState\x12\x13\n\x0fNTP_STATE_RESET\x10\x00\x12\x17\n\x13NTP_STATE_COMPLETED\x10\x01\x12\x19\n\x15NTP_STATE_IN_PROGRESS\x10\x02\x42\x11\xaa\x02\x0e\x43iot.Protos.V2b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ciot.proto.v2.ntp_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002\016Ciot.Protos.V2'
  _globals['_NTPSTATE']._serialized_start=455
  _globals['_NTPSTATE']._serialized_end=538
  _globals['_NTPSTOP']._serialized_start=33
  _globals['_NTPSTOP']._serialized_end=42
  _globals['_NTPCFG']._serialized_start=45
  _globals['_NTPCFG']._serialized_end=181
  _globals['_NTPSTATUS']._serialized_start=183
  _globals['_NTPSTATUS']._serialized_end=292
  _globals['_NTPREQ']._serialized_start=294
  _globals['_NTPREQ']._serialized_end=302
  _globals['_NTPDATA']._serialized_start=305
  _globals['_NTPDATA']._serialized_end=453
# @@protoc_insertion_point(module_scope)
