"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Define the package for the CIOT protocol."""

import builtins
import google.protobuf.descriptor
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _OtaType:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _OtaTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_OtaType.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    OTA_TYPE_DEFAULT: _OtaType.ValueType  # 0
    """Default OTA type used do update firmware"""
    OTA_TYPE_DATA_SPIFFS: _OtaType.ValueType  # 1
    """Data SPIFFS OTA type used to update data spiffs partition"""

class OtaType(_OtaType, metaclass=_OtaTypeEnumTypeWrapper):
    """Enum representing the different OTA types"""

OTA_TYPE_DEFAULT: OtaType.ValueType  # 0
"""Default OTA type used do update firmware"""
OTA_TYPE_DATA_SPIFFS: OtaType.ValueType  # 1
"""Data SPIFFS OTA type used to update data spiffs partition"""
global___OtaType = OtaType

class _OtaState:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _OtaStateEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_OtaState.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    OTA_STATE_IDLE: _OtaState.ValueType  # 0
    """OTA process is idle."""
    OTA_STATE_INIT: _OtaState.ValueType  # 1
    """OTA process is initialized."""
    OTA_STATE_IN_PROGRESS: _OtaState.ValueType  # 2
    """OTA process is in progress."""
    OTA_STATE_START: _OtaState.ValueType  # 3
    """OTA process is starting."""
    OTA_STATE_CONNECTED: _OtaState.ValueType  # 4
    """OTA process is connected."""
    OTA_STATE_CHECKING_DATA: _OtaState.ValueType  # 5
    """OTA process is checking data."""
    OTA_STATE_DECRYPTING: _OtaState.ValueType  # 6
    """OTA process is decrypting data."""
    OTA_STATE_FLASHING: _OtaState.ValueType  # 7
    """OTA process is flashing data."""
    OTA_STATE_UPDATE_BOOT_PARTITION: _OtaState.ValueType  # 8
    """OTA process is updating boot partition."""
    OTA_STATE_STATE_DONE: _OtaState.ValueType  # 9
    """OTA process is done."""
    OTA_STATE_ERROR: _OtaState.ValueType  # 10
    """OTA process encountered an error."""

class OtaState(_OtaState, metaclass=_OtaStateEnumTypeWrapper):
    """Enum representing the state of the OTA (Over-the-Air) update process."""

OTA_STATE_IDLE: OtaState.ValueType  # 0
"""OTA process is idle."""
OTA_STATE_INIT: OtaState.ValueType  # 1
"""OTA process is initialized."""
OTA_STATE_IN_PROGRESS: OtaState.ValueType  # 2
"""OTA process is in progress."""
OTA_STATE_START: OtaState.ValueType  # 3
"""OTA process is starting."""
OTA_STATE_CONNECTED: OtaState.ValueType  # 4
"""OTA process is connected."""
OTA_STATE_CHECKING_DATA: OtaState.ValueType  # 5
"""OTA process is checking data."""
OTA_STATE_DECRYPTING: OtaState.ValueType  # 6
"""OTA process is decrypting data."""
OTA_STATE_FLASHING: OtaState.ValueType  # 7
"""OTA process is flashing data."""
OTA_STATE_UPDATE_BOOT_PARTITION: OtaState.ValueType  # 8
"""OTA process is updating boot partition."""
OTA_STATE_STATE_DONE: OtaState.ValueType  # 9
"""OTA process is done."""
OTA_STATE_ERROR: OtaState.ValueType  # 10
"""OTA process encountered an error."""
global___OtaState = OtaState

class _OtaCmd:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _OtaCmdEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_OtaCmd.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    OTA_CMD_NONE: _OtaCmd.ValueType  # 0
    """No command."""
    OTA_CMD_ROLLBACK: _OtaCmd.ValueType  # 1
    """Rollback command."""

class OtaCmd(_OtaCmd, metaclass=_OtaCmdEnumTypeWrapper): ...

OTA_CMD_NONE: OtaCmd.ValueType  # 0
"""No command."""
OTA_CMD_ROLLBACK: OtaCmd.ValueType  # 1
"""Rollback command."""
global___OtaCmd = OtaCmd

@typing.final
class OtaStop(google.protobuf.message.Message):
    """Ota stop message"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___OtaStop = OtaStop

@typing.final
class OtaCfg(google.protobuf.message.Message):
    """Message representing configuration for the OTA process."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    URL_FIELD_NUMBER: builtins.int
    FORCE_FIELD_NUMBER: builtins.int
    RESTART_FIELD_NUMBER: builtins.int
    TYPE_FIELD_NUMBER: builtins.int
    url: builtins.str
    """URL for the OTA update."""
    force: builtins.bool
    """Force OTA update."""
    restart: builtins.bool
    """Restart device after OTA update."""
    type: global___OtaType.ValueType
    """OTA type"""
    def __init__(
        self,
        *,
        url: builtins.str = ...,
        force: builtins.bool = ...,
        restart: builtins.bool = ...,
        type: global___OtaType.ValueType = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["force", b"force", "restart", b"restart", "type", b"type", "url", b"url"]) -> None: ...

global___OtaCfg = OtaCfg

@typing.final
class OtaStatus(google.protobuf.message.Message):
    """Message representing status for the OTA process."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    STATE_FIELD_NUMBER: builtins.int
    ERROR_FIELD_NUMBER: builtins.int
    IMAGE_SIZE_FIELD_NUMBER: builtins.int
    IMAGE_WRITTEN_FIELD_NUMBER: builtins.int
    state: global___OtaState.ValueType
    """State of the OTA process."""
    error: builtins.int
    """Error code, if any."""
    image_size: builtins.int
    """Size of the OTA image."""
    image_written: builtins.int
    """Size of the OTA image already read."""
    def __init__(
        self,
        *,
        state: global___OtaState.ValueType = ...,
        error: builtins.int = ...,
        image_size: builtins.int = ...,
        image_written: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["error", b"error", "image_size", b"image_size", "image_written", b"image_written", "state", b"state"]) -> None: ...

global___OtaStatus = OtaStatus

@typing.final
class OtaReq(google.protobuf.message.Message):
    """Message representing an OTA request."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CMD_FIELD_NUMBER: builtins.int
    cmd: global___OtaCmd.ValueType
    """OTA command."""
    def __init__(
        self,
        *,
        cmd: global___OtaCmd.ValueType = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["cmd", b"cmd", "type", b"type"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["cmd", b"cmd", "type", b"type"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["type", b"type"]) -> typing.Literal["cmd"] | None: ...

global___OtaReq = OtaReq

@typing.final
class OtaData(google.protobuf.message.Message):
    """Message representing data for the OTA process."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    STOP_FIELD_NUMBER: builtins.int
    CONFIG_FIELD_NUMBER: builtins.int
    STATUS_FIELD_NUMBER: builtins.int
    REQUEST_FIELD_NUMBER: builtins.int
    @property
    def stop(self) -> global___OtaStop:
        """Stop ota interface."""

    @property
    def config(self) -> global___OtaCfg:
        """Configuration for the OTA process."""

    @property
    def status(self) -> global___OtaStatus:
        """Status of the OTA process."""

    @property
    def request(self) -> global___OtaReq:
        """OTA request data."""

    def __init__(
        self,
        *,
        stop: global___OtaStop | None = ...,
        config: global___OtaCfg | None = ...,
        status: global___OtaStatus | None = ...,
        request: global___OtaReq | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["config", b"config", "request", b"request", "status", b"status", "stop", b"stop", "type", b"type"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["config", b"config", "request", b"request", "status", b"status", "stop", b"stop", "type", b"type"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["type", b"type"]) -> typing.Literal["stop", "config", "status", "request"] | None: ...

global___OtaData = OtaData
