# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ciot/proto/v2/ota.proto
# Protobuf Python Version: 6.30.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    0,
    '',
    'ciot/proto/v2/ota.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17\x63iot/proto/v2/ota.proto\x12\x04\x43iot\"\t\n\x07OtaStop\"R\n\x06OtaCfg\x12\x0b\n\x03url\x18\x01 \x01(\t\x12\r\n\x05\x66orce\x18\x02 \x01(\x08\x12\x0f\n\x07restart\x18\x04 \x01(\x08\x12\x1b\n\x04type\x18\x05 \x01(\x0e\x32\r.Ciot.OtaType\"d\n\tOtaStatus\x12\x1d\n\x05state\x18\x01 \x01(\x0e\x32\x0e.Ciot.OtaState\x12\r\n\x05\x65rror\x18\x02 \x01(\x05\x12\x12\n\nimage_size\x18\x03 \x01(\r\x12\x15\n\rimage_written\x18\x04 \x01(\r\"-\n\x06OtaReq\x12\x1b\n\x03\x63md\x18\x01 \x01(\x0e\x32\x0c.Ciot.OtaCmdH\x00\x42\x06\n\x04type\"\x94\x01\n\x07OtaData\x12\x1d\n\x04stop\x18\x01 \x01(\x0b\x32\r.Ciot.OtaStopH\x00\x12\x1e\n\x06\x63onfig\x18\x02 \x01(\x0b\x32\x0c.Ciot.OtaCfgH\x00\x12!\n\x06status\x18\x03 \x01(\x0b\x32\x0f.Ciot.OtaStatusH\x00\x12\x1f\n\x07request\x18\x04 \x01(\x0b\x32\x0c.Ciot.OtaReqH\x00\x42\x06\n\x04type*9\n\x07OtaType\x12\x14\n\x10OTA_TYPE_DEFAULT\x10\x00\x12\x18\n\x14OTA_TYPE_DATA_SPIFFS\x10\x01*\x9e\x02\n\x08OtaState\x12\x12\n\x0eOTA_STATE_IDLE\x10\x00\x12\x12\n\x0eOTA_STATE_INIT\x10\x01\x12\x19\n\x15OTA_STATE_IN_PROGRESS\x10\x02\x12\x13\n\x0fOTA_STATE_START\x10\x03\x12\x17\n\x13OTA_STATE_CONNECTED\x10\x04\x12\x1b\n\x17OTA_STATE_CHECKING_DATA\x10\x05\x12\x18\n\x14OTA_STATE_DECRYPTING\x10\x06\x12\x16\n\x12OTA_STATE_FLASHING\x10\x07\x12#\n\x1fOTA_STATE_UPDATE_BOOT_PARTITION\x10\x08\x12\x18\n\x14OTA_STATE_STATE_DONE\x10\t\x12\x13\n\x0fOTA_STATE_ERROR\x10\n*0\n\x06OtaCmd\x12\x10\n\x0cOTA_CMD_NONE\x10\x00\x12\x14\n\x10OTA_CMD_ROLLBACK\x10\x01\x42\x11\xaa\x02\x0e\x43iot.Protos.V2b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ciot.proto.v2.ota_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002\016Ciot.Protos.V2'
  _globals['_OTATYPE']._serialized_start=428
  _globals['_OTATYPE']._serialized_end=485
  _globals['_OTASTATE']._serialized_start=488
  _globals['_OTASTATE']._serialized_end=774
  _globals['_OTACMD']._serialized_start=776
  _globals['_OTACMD']._serialized_end=824
  _globals['_OTASTOP']._serialized_start=33
  _globals['_OTASTOP']._serialized_end=42
  _globals['_OTACFG']._serialized_start=44
  _globals['_OTACFG']._serialized_end=126
  _globals['_OTASTATUS']._serialized_start=128
  _globals['_OTASTATUS']._serialized_end=228
  _globals['_OTAREQ']._serialized_start=230
  _globals['_OTAREQ']._serialized_end=275
  _globals['_OTADATA']._serialized_start=278
  _globals['_OTADATA']._serialized_end=426
# @@protoc_insertion_point(module_scope)
