# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ciot/proto/v2/storage.proto
# Protobuf Python Version: 6.30.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    0,
    '',
    'ciot/proto/v2/storage.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1b\x63iot/proto/v2/storage.proto\x12\x04\x43iot\"\r\n\x0bStorageStop\"-\n\nStorageCfg\x12\x1f\n\x04type\x18\x01 \x01(\x0e\x32\x11.Ciot.StorageType\"F\n\rStorageStatus\x12!\n\x05state\x18\x01 \x01(\x0e\x32\x12.Ciot.StorageState\x12\x12\n\nfree_space\x18\x02 \x01(\r\"!\n\x0bStorageInfo\x12\x12\n\ntotal_size\x18\x01 \x01(\r\")\n\x0bStorageFile\x12\x0c\n\x04path\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\" \n\x10StorageReqDelete\x12\x0c\n\x04path\x18\x01 \x01(\t\"\x12\n\x10StorageReqFormat\"\xa9\x01\n\nStorageReq\x12!\n\x04save\x18\x01 \x01(\x0b\x32\x11.Ciot.StorageFileH\x00\x12!\n\x04load\x18\x02 \x01(\x0b\x32\x11.Ciot.StorageFileH\x00\x12#\n\x06remove\x18\x03 \x01(\x0b\x32\x11.Ciot.StorageFileH\x00\x12(\n\x06\x66ormat\x18\x04 \x01(\x0b\x32\x16.Ciot.StorageReqFormatH\x00\x42\x06\n\x04type\"\xcb\x01\n\x0bStorageData\x12!\n\x04stop\x18\x01 \x01(\x0b\x32\x11.Ciot.StorageStopH\x00\x12\"\n\x06\x63onfig\x18\x02 \x01(\x0b\x32\x10.Ciot.StorageCfgH\x00\x12%\n\x06status\x18\x03 \x01(\x0b\x32\x13.Ciot.StorageStatusH\x00\x12#\n\x07request\x18\x04 \x01(\x0b\x32\x10.Ciot.StorageReqH\x00\x12!\n\x04info\x18\x06 \x01(\x0b\x32\x11.Ciot.StorageInfoH\x00\x42\x06\n\x04type*&\n\x0cStorageState\x12\x16\n\x12STORAGE_STATE_IDLE\x10\x00*m\n\x0bStorageType\x12\x18\n\x14STORAGE_TYPE_UNKNOWN\x10\x00\x12\x17\n\x13STORAGE_TYPE_EEPROM\x10\x01\x12\x16\n\x12STORAGE_TYPE_FLASH\x10\x02\x12\x13\n\x0fSTORAGE_TYPE_FS\x10\x03\x42\x11\xaa\x02\x0e\x43iot.Protos.V2b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ciot.proto.v2.storage_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002\016Ciot.Protos.V2'
  _globals['_STORAGESTATE']._serialized_start=681
  _globals['_STORAGESTATE']._serialized_end=719
  _globals['_STORAGETYPE']._serialized_start=721
  _globals['_STORAGETYPE']._serialized_end=830
  _globals['_STORAGESTOP']._serialized_start=37
  _globals['_STORAGESTOP']._serialized_end=50
  _globals['_STORAGECFG']._serialized_start=52
  _globals['_STORAGECFG']._serialized_end=97
  _globals['_STORAGESTATUS']._serialized_start=99
  _globals['_STORAGESTATUS']._serialized_end=169
  _globals['_STORAGEINFO']._serialized_start=171
  _globals['_STORAGEINFO']._serialized_end=204
  _globals['_STORAGEFILE']._serialized_start=206
  _globals['_STORAGEFILE']._serialized_end=247
  _globals['_STORAGEREQDELETE']._serialized_start=249
  _globals['_STORAGEREQDELETE']._serialized_end=281
  _globals['_STORAGEREQFORMAT']._serialized_start=283
  _globals['_STORAGEREQFORMAT']._serialized_end=301
  _globals['_STORAGEREQ']._serialized_start=304
  _globals['_STORAGEREQ']._serialized_end=473
  _globals['_STORAGEDATA']._serialized_start=476
  _globals['_STORAGEDATA']._serialized_end=679
# @@protoc_insertion_point(module_scope)
