"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import google.protobuf.descriptor
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _StorageState:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _StorageStateEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_StorageState.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    STORAGE_STATE_IDLE: _StorageState.ValueType  # 0
    """Storage module is idle."""

class StorageState(_StorageState, metaclass=_StorageStateEnumTypeWrapper):
    """Enum representing the state of the storage module."""

STORAGE_STATE_IDLE: StorageState.ValueType  # 0
"""Storage module is idle."""
global___StorageState = StorageState

class _StorageType:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _StorageTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_StorageType.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    STORAGE_TYPE_UNKNOWN: _StorageType.ValueType  # 0
    """Unknown storage type."""
    STORAGE_TYPE_EEPROM: _StorageType.ValueType  # 1
    """EEPROM storage type."""
    STORAGE_TYPE_FLASH: _StorageType.ValueType  # 2
    """Flash storage type."""
    STORAGE_TYPE_FS: _StorageType.ValueType  # 3
    """File system storage type."""

class StorageType(_StorageType, metaclass=_StorageTypeEnumTypeWrapper):
    """Enum representing different types of storage."""

STORAGE_TYPE_UNKNOWN: StorageType.ValueType  # 0
"""Unknown storage type."""
STORAGE_TYPE_EEPROM: StorageType.ValueType  # 1
"""EEPROM storage type."""
STORAGE_TYPE_FLASH: StorageType.ValueType  # 2
"""Flash storage type."""
STORAGE_TYPE_FS: StorageType.ValueType  # 3
"""File system storage type."""
global___StorageType = StorageType

@typing.final
class StorageStop(google.protobuf.message.Message):
    """Stop storage interface"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___StorageStop = StorageStop

@typing.final
class StorageCfg(google.protobuf.message.Message):
    """Message representing configuration for the storage module."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TYPE_FIELD_NUMBER: builtins.int
    type: global___StorageType.ValueType
    """Type of storage."""
    def __init__(
        self,
        *,
        type: global___StorageType.ValueType = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["type", b"type"]) -> None: ...

global___StorageCfg = StorageCfg

@typing.final
class StorageStatus(google.protobuf.message.Message):
    """Message representing status for the storage module."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    STATE_FIELD_NUMBER: builtins.int
    FREE_SPACE_FIELD_NUMBER: builtins.int
    state: global___StorageState.ValueType
    """State of the storage module."""
    free_space: builtins.int
    """Storage module free space"""
    def __init__(
        self,
        *,
        state: global___StorageState.ValueType = ...,
        free_space: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["free_space", b"free_space", "state", b"state"]) -> None: ...

global___StorageStatus = StorageStatus

@typing.final
class StorageInfo(google.protobuf.message.Message):
    """Message representing storage module information."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TOTAL_SIZE_FIELD_NUMBER: builtins.int
    total_size: builtins.int
    def __init__(
        self,
        *,
        total_size: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["total_size", b"total_size"]) -> None: ...

global___StorageInfo = StorageInfo

@typing.final
class StorageFile(google.protobuf.message.Message):
    """Message representing data for a storage request."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PATH_FIELD_NUMBER: builtins.int
    DATA_FIELD_NUMBER: builtins.int
    path: builtins.str
    """Path for the storage operation."""
    data: builtins.bytes
    """Data for the storage operation."""
    def __init__(
        self,
        *,
        path: builtins.str = ...,
        data: builtins.bytes = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["data", b"data", "path", b"path"]) -> None: ...

global___StorageFile = StorageFile

@typing.final
class StorageReqDelete(google.protobuf.message.Message):
    """Message representing a request to delete a file."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PATH_FIELD_NUMBER: builtins.int
    path: builtins.str
    """Path for the storage operation."""
    def __init__(
        self,
        *,
        path: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["path", b"path"]) -> None: ...

global___StorageReqDelete = StorageReqDelete

@typing.final
class StorageReqFormat(google.protobuf.message.Message):
    """Message representing a request to format the storage interface."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___StorageReqFormat = StorageReqFormat

@typing.final
class StorageReq(google.protobuf.message.Message):
    """Message representing a storage request."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SAVE_FIELD_NUMBER: builtins.int
    LOAD_FIELD_NUMBER: builtins.int
    REMOVE_FIELD_NUMBER: builtins.int
    FORMAT_FIELD_NUMBER: builtins.int
    @property
    def save(self) -> global___StorageFile: ...
    @property
    def load(self) -> global___StorageFile: ...
    @property
    def remove(self) -> global___StorageFile: ...
    @property
    def format(self) -> global___StorageReqFormat: ...
    def __init__(
        self,
        *,
        save: global___StorageFile | None = ...,
        load: global___StorageFile | None = ...,
        remove: global___StorageFile | None = ...,
        format: global___StorageReqFormat | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["format", b"format", "load", b"load", "remove", b"remove", "save", b"save", "type", b"type"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["format", b"format", "load", b"load", "remove", b"remove", "save", b"save", "type", b"type"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["type", b"type"]) -> typing.Literal["save", "load", "remove", "format"] | None: ...

global___StorageReq = StorageReq

@typing.final
class StorageData(google.protobuf.message.Message):
    """Message representing data for the storage module."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    STOP_FIELD_NUMBER: builtins.int
    CONFIG_FIELD_NUMBER: builtins.int
    STATUS_FIELD_NUMBER: builtins.int
    REQUEST_FIELD_NUMBER: builtins.int
    INFO_FIELD_NUMBER: builtins.int
    @property
    def stop(self) -> global___StorageStop:
        """Stop storage interface"""

    @property
    def config(self) -> global___StorageCfg:
        """Configuration for the storage module."""

    @property
    def status(self) -> global___StorageStatus:
        """Status of the storage module."""

    @property
    def request(self) -> global___StorageReq:
        """Storage request data."""

    @property
    def info(self) -> global___StorageInfo:
        """Storage information data."""

    def __init__(
        self,
        *,
        stop: global___StorageStop | None = ...,
        config: global___StorageCfg | None = ...,
        status: global___StorageStatus | None = ...,
        request: global___StorageReq | None = ...,
        info: global___StorageInfo | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["config", b"config", "info", b"info", "request", b"request", "status", b"status", "stop", b"stop", "type", b"type"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["config", b"config", "info", b"info", "request", b"request", "status", b"status", "stop", b"stop", "type", b"type"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["type", b"type"]) -> typing.Literal["stop", "config", "status", "request", "info"] | None: ...

global___StorageData = StorageData
