"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import google.protobuf.descriptor
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _SysReqCmd:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _SysReqCmdEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_SysReqCmd.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    SYS_REQ_CMD_UNKOWN: _SysReqCmd.ValueType  # 0
    """Unknown system request type."""
    SYS_REQ_CMD_RESTART: _SysReqCmd.ValueType  # 1
    """System restart request."""
    SYS_REQ_CMD_INIT_DFU: _SysReqCmd.ValueType  # 2
    """System init DFU bootloader"""

class SysReqCmd(_SysReqCmd, metaclass=_SysReqCmdEnumTypeWrapper):
    """Enum representing different types of system requests."""

SYS_REQ_CMD_UNKOWN: SysReqCmd.ValueType  # 0
"""Unknown system request type."""
SYS_REQ_CMD_RESTART: SysReqCmd.ValueType  # 1
"""System restart request."""
SYS_REQ_CMD_INIT_DFU: SysReqCmd.ValueType  # 2
"""System init DFU bootloader"""
global___SysReqCmd = SysReqCmd

class _SysHw:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _SysHwEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_SysHw.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    SYS_HW_UNKNOWN: _SysHw.ValueType  # 0
    """Unknown hardware"""
    SYS_HW_ESP8266: _SysHw.ValueType  # 1
    """ESP8266"""
    SYS_HW_ARDUINO: _SysHw.ValueType  # 2
    """Arduino Board"""
    SYS_HW_ESP32: _SysHw.ValueType  # 3
    """ESP32"""
    SYS_HW_NRF51: _SysHw.ValueType  # 4
    """NRF51"""
    SYS_HW_NRF52: _SysHw.ValueType  # 5
    """NRF52"""
    SYS_HW_LINUX: _SysHw.ValueType  # 6
    """Linux device"""
    SYS_HW_WIN32: _SysHw.ValueType  # 7
    """Windows device"""

class SysHw(_SysHw, metaclass=_SysHwEnumTypeWrapper):
    """Enum representing hardware version"""

SYS_HW_UNKNOWN: SysHw.ValueType  # 0
"""Unknown hardware"""
SYS_HW_ESP8266: SysHw.ValueType  # 1
"""ESP8266"""
SYS_HW_ARDUINO: SysHw.ValueType  # 2
"""Arduino Board"""
SYS_HW_ESP32: SysHw.ValueType  # 3
"""ESP32"""
SYS_HW_NRF51: SysHw.ValueType  # 4
"""NRF51"""
SYS_HW_NRF52: SysHw.ValueType  # 5
"""NRF52"""
SYS_HW_LINUX: SysHw.ValueType  # 6
"""Linux device"""
SYS_HW_WIN32: SysHw.ValueType  # 7
"""Windows device"""
global___SysHw = SysHw

@typing.final
class SysStop(google.protobuf.message.Message):
    """Message used to stop system interface"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___SysStop = SysStop

@typing.final
class SysCfg(google.protobuf.message.Message):
    """Message representing configuration for the system."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___SysCfg = SysCfg

@typing.final
class SysFeatures(google.protobuf.message.Message):
    """Message representing system features."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    BLE_ADV_FIELD_NUMBER: builtins.int
    BLE_SCN_FIELD_NUMBER: builtins.int
    BLE_FIELD_NUMBER: builtins.int
    ETH_FIELD_NUMBER: builtins.int
    GPIO_FIELD_NUMBER: builtins.int
    HTTP_CLIENT_FIELD_NUMBER: builtins.int
    HTTP_SERVER_FIELD_NUMBER: builtins.int
    MBUS_CLIENT_FIELD_NUMBER: builtins.int
    MBUS_SERVER_FIELD_NUMBER: builtins.int
    MQTT_CLIENT_FIELD_NUMBER: builtins.int
    NTP_FIELD_NUMBER: builtins.int
    OTA_FIELD_NUMBER: builtins.int
    PWM_FIELD_NUMBER: builtins.int
    SYS_FIELD_NUMBER: builtins.int
    TCP_FIELD_NUMBER: builtins.int
    TIMER_FIELD_NUMBER: builtins.int
    UART_FIELD_NUMBER: builtins.int
    USB_FIELD_NUMBER: builtins.int
    WIFI_FIELD_NUMBER: builtins.int
    STORAGE_FIELD_NUMBER: builtins.int
    SERIALIZER_FIELD_NUMBER: builtins.int
    CRYPT_FIELD_NUMBER: builtins.int
    DFU_FIELD_NUMBER: builtins.int
    ble_adv: builtins.bool
    """Bluetooth Low Energy advertising."""
    ble_scn: builtins.bool
    """Bluetooth Low Energy scanning."""
    ble: builtins.bool
    """Bluetooth Low Energy support."""
    eth: builtins.bool
    """Ethernet support."""
    gpio: builtins.bool
    """General Purpose Input/Output support."""
    http_client: builtins.bool
    """HTTP client support."""
    http_server: builtins.bool
    """HTTP server support."""
    mbus_client: builtins.bool
    """Modbus client support."""
    mbus_server: builtins.bool
    """Modbus server support."""
    mqtt_client: builtins.bool
    """Mqtt client support."""
    ntp: builtins.bool
    """Network Time Protocol support."""
    ota: builtins.bool
    """Over-the-Air update support."""
    pwm: builtins.bool
    """Pulse Width Modulation support."""
    sys: builtins.bool
    """System support."""
    tcp: builtins.bool
    """Transmission Control Protocol support."""
    timer: builtins.bool
    """Timer support."""
    uart: builtins.bool
    """Universal Asynchronous Receiver-Transmitter support."""
    usb: builtins.bool
    """Universal Serial Bus support."""
    wifi: builtins.bool
    """Wireless Fidelity support."""
    storage: builtins.bool
    """Storage support."""
    serializer: builtins.bool
    """Serializer support."""
    crypt: builtins.bool
    """Cryptography support."""
    dfu: builtins.bool
    """Device Firmware Update support."""
    def __init__(
        self,
        *,
        ble_adv: builtins.bool = ...,
        ble_scn: builtins.bool = ...,
        ble: builtins.bool = ...,
        eth: builtins.bool = ...,
        gpio: builtins.bool = ...,
        http_client: builtins.bool = ...,
        http_server: builtins.bool = ...,
        mbus_client: builtins.bool = ...,
        mbus_server: builtins.bool = ...,
        mqtt_client: builtins.bool = ...,
        ntp: builtins.bool = ...,
        ota: builtins.bool = ...,
        pwm: builtins.bool = ...,
        sys: builtins.bool = ...,
        tcp: builtins.bool = ...,
        timer: builtins.bool = ...,
        uart: builtins.bool = ...,
        usb: builtins.bool = ...,
        wifi: builtins.bool = ...,
        storage: builtins.bool = ...,
        serializer: builtins.bool = ...,
        crypt: builtins.bool = ...,
        dfu: builtins.bool = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["ble", b"ble", "ble_adv", b"ble_adv", "ble_scn", b"ble_scn", "crypt", b"crypt", "dfu", b"dfu", "eth", b"eth", "gpio", b"gpio", "http_client", b"http_client", "http_server", b"http_server", "mbus_client", b"mbus_client", "mbus_server", b"mbus_server", "mqtt_client", b"mqtt_client", "ntp", b"ntp", "ota", b"ota", "pwm", b"pwm", "serializer", b"serializer", "storage", b"storage", "sys", b"sys", "tcp", b"tcp", "timer", b"timer", "uart", b"uart", "usb", b"usb", "wifi", b"wifi"]) -> None: ...

global___SysFeatures = SysFeatures

@typing.final
class SysInfo(google.protobuf.message.Message):
    """Message representing system information."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    APP_VER_FIELD_NUMBER: builtins.int
    HW_NAME_FIELD_NUMBER: builtins.int
    HW_TYPE_FIELD_NUMBER: builtins.int
    FEATURES_FIELD_NUMBER: builtins.int
    app_ver: builtins.bytes
    """Application version."""
    hw_name: builtins.str
    """Hardware name."""
    hw_type: global___SysHw.ValueType
    """Hardware type."""
    @property
    def features(self) -> global___SysFeatures:
        """System features."""

    def __init__(
        self,
        *,
        app_ver: builtins.bytes = ...,
        hw_name: builtins.str = ...,
        hw_type: global___SysHw.ValueType = ...,
        features: global___SysFeatures | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["features", b"features"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["app_ver", b"app_ver", "features", b"features", "hw_name", b"hw_name", "hw_type", b"hw_type"]) -> None: ...

global___SysInfo = SysInfo

@typing.final
class SysStatus(google.protobuf.message.Message):
    """Message representing system status."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    RESET_REASON_FIELD_NUMBER: builtins.int
    RESET_COUNT_FIELD_NUMBER: builtins.int
    FREE_MEMORY_FIELD_NUMBER: builtins.int
    LIFETIME_FIELD_NUMBER: builtins.int
    reset_reason: builtins.int
    """Reason for the last reset."""
    reset_count: builtins.int
    """Number of resets."""
    free_memory: builtins.int
    """Amount of free memory."""
    lifetime: builtins.int
    """Lifetime of the system."""
    def __init__(
        self,
        *,
        reset_reason: builtins.int = ...,
        reset_count: builtins.int = ...,
        free_memory: builtins.int = ...,
        lifetime: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["free_memory", b"free_memory", "lifetime", b"lifetime", "reset_count", b"reset_count", "reset_reason", b"reset_reason"]) -> None: ...

global___SysStatus = SysStatus

@typing.final
class SysReq(google.protobuf.message.Message):
    """Message representing a system request."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CMD_FIELD_NUMBER: builtins.int
    cmd: global___SysReqCmd.ValueType
    """System command"""
    def __init__(
        self,
        *,
        cmd: global___SysReqCmd.ValueType = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["cmd", b"cmd", "type", b"type"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["cmd", b"cmd", "type", b"type"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["type", b"type"]) -> typing.Literal["cmd"] | None: ...

global___SysReq = SysReq

@typing.final
class SysData(google.protobuf.message.Message):
    """Message representing data for the system."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    STOP_FIELD_NUMBER: builtins.int
    CONFIG_FIELD_NUMBER: builtins.int
    STATUS_FIELD_NUMBER: builtins.int
    REQUEST_FIELD_NUMBER: builtins.int
    INFO_FIELD_NUMBER: builtins.int
    @property
    def stop(self) -> global___SysStop: ...
    @property
    def config(self) -> global___SysCfg:
        """Configuration for the system."""

    @property
    def status(self) -> global___SysStatus:
        """Status of the system."""

    @property
    def request(self) -> global___SysReq:
        """System request data."""

    @property
    def info(self) -> global___SysInfo:
        """System info."""

    def __init__(
        self,
        *,
        stop: global___SysStop | None = ...,
        config: global___SysCfg | None = ...,
        status: global___SysStatus | None = ...,
        request: global___SysReq | None = ...,
        info: global___SysInfo | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["config", b"config", "info", b"info", "request", b"request", "status", b"status", "stop", b"stop", "type", b"type"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["config", b"config", "info", b"info", "request", b"request", "status", b"status", "stop", b"stop", "type", b"type"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["type", b"type"]) -> typing.Literal["stop", "config", "status", "request", "info"] | None: ...

global___SysData = SysData
