"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import google.protobuf.descriptor
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _TcpState:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _TcpStateEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_TcpState.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    TCP_STATE_STOPPED: _TcpState.ValueType  # 0
    """TCP module is stopped."""
    TCP_STATE_STARTED: _TcpState.ValueType  # 1
    """TCP module is started."""
    TCP_STATE_DISCONNECTING: _TcpState.ValueType  # 2
    """TCP module is disconnecting."""
    TCP_STATE_DISCONNECTED: _TcpState.ValueType  # 3
    """TCP module is disconnected."""
    TCP_STATE_CONNECTING: _TcpState.ValueType  # 4
    """TCP module is connecting."""
    TCP_STATE_CONNECTED: _TcpState.ValueType  # 5
    """TCP module is connected."""
    TCP_STATE_ERROR: _TcpState.ValueType  # 6
    """TCP module encountered an error."""

class TcpState(_TcpState, metaclass=_TcpStateEnumTypeWrapper):
    """Enum representing the state of the TCP module."""

TCP_STATE_STOPPED: TcpState.ValueType  # 0
"""TCP module is stopped."""
TCP_STATE_STARTED: TcpState.ValueType  # 1
"""TCP module is started."""
TCP_STATE_DISCONNECTING: TcpState.ValueType  # 2
"""TCP module is disconnecting."""
TCP_STATE_DISCONNECTED: TcpState.ValueType  # 3
"""TCP module is disconnected."""
TCP_STATE_CONNECTING: TcpState.ValueType  # 4
"""TCP module is connecting."""
TCP_STATE_CONNECTED: TcpState.ValueType  # 5
"""TCP module is connected."""
TCP_STATE_ERROR: TcpState.ValueType  # 6
"""TCP module encountered an error."""
global___TcpState = TcpState

class _TcpDhcpState:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _TcpDhcpStateEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_TcpDhcpState.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    TCP_DHCP_STATE_IDLE: _TcpDhcpState.ValueType  # 0
    """TCP DHCP is idle."""
    TCP_DHCP_STATE_STARTED: _TcpDhcpState.ValueType  # 1
    """TCP DHCP is started."""
    TCP_DHCP_STATE_STOPPED: _TcpDhcpState.ValueType  # 2
    """TCP DHCP is stopped."""

class TcpDhcpState(_TcpDhcpState, metaclass=_TcpDhcpStateEnumTypeWrapper):
    """Enum representing the state of the TCP DHCP (Dynamic Host Configuration
    Protocol).
    """

TCP_DHCP_STATE_IDLE: TcpDhcpState.ValueType  # 0
"""TCP DHCP is idle."""
TCP_DHCP_STATE_STARTED: TcpDhcpState.ValueType  # 1
"""TCP DHCP is started."""
TCP_DHCP_STATE_STOPPED: TcpDhcpState.ValueType  # 2
"""TCP DHCP is stopped."""
global___TcpDhcpState = TcpDhcpState

class _TcpDhcpCfg:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _TcpDhcpCfgEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_TcpDhcpCfg.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    TCP_DHCP_CFG_NO_CHANGE: _TcpDhcpCfg.ValueType  # 0
    """No change in DHCP configuration."""
    TCP_DHCP_CFG_CLIENT: _TcpDhcpCfg.ValueType  # 1
    """Configure as DHCP client."""
    TCP_DHCP_CFG_SERVER: _TcpDhcpCfg.ValueType  # 2
    """Configure as DHCP server."""
    TCP_DHCP_CFG_DISABLED: _TcpDhcpCfg.ValueType  # 3
    """Disable DHCP."""

class TcpDhcpCfg(_TcpDhcpCfg, metaclass=_TcpDhcpCfgEnumTypeWrapper):
    """Enum representing different TCP DHCP configurations."""

TCP_DHCP_CFG_NO_CHANGE: TcpDhcpCfg.ValueType  # 0
"""No change in DHCP configuration."""
TCP_DHCP_CFG_CLIENT: TcpDhcpCfg.ValueType  # 1
"""Configure as DHCP client."""
TCP_DHCP_CFG_SERVER: TcpDhcpCfg.ValueType  # 2
"""Configure as DHCP server."""
TCP_DHCP_CFG_DISABLED: TcpDhcpCfg.ValueType  # 3
"""Disable DHCP."""
global___TcpDhcpCfg = TcpDhcpCfg

@typing.final
class TcpStop(google.protobuf.message.Message):
    """Stop TCP interface"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___TcpStop = TcpStop

@typing.final
class TcpCfg(google.protobuf.message.Message):
    """Message representing configuration for the TCP module."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    DISABLED_FIELD_NUMBER: builtins.int
    DHCP_FIELD_NUMBER: builtins.int
    IP_FIELD_NUMBER: builtins.int
    GATEWAY_FIELD_NUMBER: builtins.int
    MASK_FIELD_NUMBER: builtins.int
    DNS_FIELD_NUMBER: builtins.int
    disabled: builtins.bool
    """Disable TCP interface"""
    dhcp: global___TcpDhcpCfg.ValueType
    """DHCP configuration."""
    ip: builtins.bytes
    """IP address."""
    gateway: builtins.bytes
    """Gateway address."""
    mask: builtins.bytes
    """Subnet mask."""
    dns: builtins.bytes
    """DNS address."""
    def __init__(
        self,
        *,
        disabled: builtins.bool = ...,
        dhcp: global___TcpDhcpCfg.ValueType = ...,
        ip: builtins.bytes = ...,
        gateway: builtins.bytes = ...,
        mask: builtins.bytes = ...,
        dns: builtins.bytes = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["dhcp", b"dhcp", "disabled", b"disabled", "dns", b"dns", "gateway", b"gateway", "ip", b"ip", "mask", b"mask"]) -> None: ...

global___TcpCfg = TcpCfg

@typing.final
class TcpDhcpStatus(google.protobuf.message.Message):
    """Message representing DHCP status for the TCP module."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CLIENT_FIELD_NUMBER: builtins.int
    SERVER_FIELD_NUMBER: builtins.int
    client: global___TcpDhcpState.ValueType
    """DHCP client status."""
    server: global___TcpDhcpState.ValueType
    """DHCP server status."""
    def __init__(
        self,
        *,
        client: global___TcpDhcpState.ValueType = ...,
        server: global___TcpDhcpState.ValueType = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["client", b"client", "server", b"server"]) -> None: ...

global___TcpDhcpStatus = TcpDhcpStatus

@typing.final
class TcpInfo(google.protobuf.message.Message):
    """Message representing TCP information."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    MAC_FIELD_NUMBER: builtins.int
    IP_FIELD_NUMBER: builtins.int
    mac: builtins.bytes
    """MAC address."""
    ip: builtins.bytes
    """IP address."""
    def __init__(
        self,
        *,
        mac: builtins.bytes = ...,
        ip: builtins.bytes = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["ip", b"ip", "mac", b"mac"]) -> None: ...

global___TcpInfo = TcpInfo

@typing.final
class TcpStatus(google.protobuf.message.Message):
    """Message representing status for the TCP module."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    STATE_FIELD_NUMBER: builtins.int
    CONN_COUNT_FIELD_NUMBER: builtins.int
    DHCP_FIELD_NUMBER: builtins.int
    state: global___TcpState.ValueType
    """State of the TCP module."""
    conn_count: builtins.int
    """Connection count."""
    @property
    def dhcp(self) -> global___TcpDhcpStatus:
        """DHCP status."""

    def __init__(
        self,
        *,
        state: global___TcpState.ValueType = ...,
        conn_count: builtins.int = ...,
        dhcp: global___TcpDhcpStatus | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["dhcp", b"dhcp"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["conn_count", b"conn_count", "dhcp", b"dhcp", "state", b"state"]) -> None: ...

global___TcpStatus = TcpStatus

@typing.final
class TcpReq(google.protobuf.message.Message):
    """Message representing a TCP request."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___TcpReq = TcpReq

@typing.final
class TcpData(google.protobuf.message.Message):
    """Message representing data for the TCP module."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    STOP_FIELD_NUMBER: builtins.int
    CONFIG_FIELD_NUMBER: builtins.int
    STATUS_FIELD_NUMBER: builtins.int
    REQUEST_FIELD_NUMBER: builtins.int
    INFO_FIELD_NUMBER: builtins.int
    @property
    def stop(self) -> global___TcpStop: ...
    @property
    def config(self) -> global___TcpCfg:
        """Configuration for the TCP module."""

    @property
    def status(self) -> global___TcpStatus:
        """Status of the TCP module."""

    @property
    def request(self) -> global___TcpReq:
        """TCP request data."""

    @property
    def info(self) -> global___TcpInfo:
        """TCP information."""

    def __init__(
        self,
        *,
        stop: global___TcpStop | None = ...,
        config: global___TcpCfg | None = ...,
        status: global___TcpStatus | None = ...,
        request: global___TcpReq | None = ...,
        info: global___TcpInfo | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["config", b"config", "info", b"info", "request", b"request", "status", b"status", "stop", b"stop", "type", b"type"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["config", b"config", "info", b"info", "request", b"request", "status", b"status", "stop", b"stop", "type", b"type"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["type", b"type"]) -> typing.Literal["stop", "config", "status", "request", "info"] | None: ...

global___TcpData = TcpData
