# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ciot/proto/v2/tcp.proto
# Protobuf Python Version: 6.30.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    0,
    '',
    'ciot/proto/v2/tcp.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17\x63iot/proto/v2/tcp.proto\x12\x04\x43iot\"\t\n\x07TcpStop\"r\n\x06TcpCfg\x12\x10\n\x08\x64isabled\x18\x01 \x01(\x08\x12\x1e\n\x04\x64hcp\x18\x02 \x01(\x0e\x32\x10.Ciot.TcpDhcpCfg\x12\n\n\x02ip\x18\x03 \x01(\x0c\x12\x0f\n\x07gateway\x18\x04 \x01(\x0c\x12\x0c\n\x04mask\x18\x05 \x01(\x0c\x12\x0b\n\x03\x64ns\x18\x06 \x01(\x0c\"W\n\rTcpDhcpStatus\x12\"\n\x06\x63lient\x18\x01 \x01(\x0e\x32\x12.Ciot.TcpDhcpState\x12\"\n\x06server\x18\x02 \x01(\x0e\x32\x12.Ciot.TcpDhcpState\"\"\n\x07TcpInfo\x12\x0b\n\x03mac\x18\x01 \x01(\x0c\x12\n\n\x02ip\x18\x02 \x01(\x0c\"a\n\tTcpStatus\x12\x1d\n\x05state\x18\x01 \x01(\x0e\x32\x0e.Ciot.TcpState\x12\x12\n\nconn_count\x18\x02 \x01(\r\x12!\n\x04\x64hcp\x18\x03 \x01(\x0b\x32\x13.Ciot.TcpDhcpStatus\"\x08\n\x06TcpReq\"\xb3\x01\n\x07TcpData\x12\x1d\n\x04stop\x18\x01 \x01(\x0b\x32\r.Ciot.TcpStopH\x00\x12\x1e\n\x06\x63onfig\x18\x02 \x01(\x0b\x32\x0c.Ciot.TcpCfgH\x00\x12!\n\x06status\x18\x03 \x01(\x0b\x32\x0f.Ciot.TcpStatusH\x00\x12\x1f\n\x07request\x18\x04 \x01(\x0b\x32\x0c.Ciot.TcpReqH\x00\x12\x1d\n\x04info\x18\x06 \x01(\x0b\x32\r.Ciot.TcpInfoH\x00\x42\x06\n\x04type*\xb9\x01\n\x08TcpState\x12\x15\n\x11TCP_STATE_STOPPED\x10\x00\x12\x15\n\x11TCP_STATE_STARTED\x10\x01\x12\x1b\n\x17TCP_STATE_DISCONNECTING\x10\x02\x12\x1a\n\x16TCP_STATE_DISCONNECTED\x10\x03\x12\x18\n\x14TCP_STATE_CONNECTING\x10\x04\x12\x17\n\x13TCP_STATE_CONNECTED\x10\x05\x12\x13\n\x0fTCP_STATE_ERROR\x10\x06*_\n\x0cTcpDhcpState\x12\x17\n\x13TCP_DHCP_STATE_IDLE\x10\x00\x12\x1a\n\x16TCP_DHCP_STATE_STARTED\x10\x01\x12\x1a\n\x16TCP_DHCP_STATE_STOPPED\x10\x02*u\n\nTcpDhcpCfg\x12\x1a\n\x16TCP_DHCP_CFG_NO_CHANGE\x10\x00\x12\x17\n\x13TCP_DHCP_CFG_CLIENT\x10\x01\x12\x17\n\x13TCP_DHCP_CFG_SERVER\x10\x02\x12\x19\n\x15TCP_DHCP_CFG_DISABLED\x10\x03\x42\x11\xaa\x02\x0e\x43iot.Protos.V2b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ciot.proto.v2.tcp_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002\016Ciot.Protos.V2'
  _globals['_TCPSTATE']._serialized_start=577
  _globals['_TCPSTATE']._serialized_end=762
  _globals['_TCPDHCPSTATE']._serialized_start=764
  _globals['_TCPDHCPSTATE']._serialized_end=859
  _globals['_TCPDHCPCFG']._serialized_start=861
  _globals['_TCPDHCPCFG']._serialized_end=978
  _globals['_TCPSTOP']._serialized_start=33
  _globals['_TCPSTOP']._serialized_end=42
  _globals['_TCPCFG']._serialized_start=44
  _globals['_TCPCFG']._serialized_end=158
  _globals['_TCPDHCPSTATUS']._serialized_start=160
  _globals['_TCPDHCPSTATUS']._serialized_end=247
  _globals['_TCPINFO']._serialized_start=249
  _globals['_TCPINFO']._serialized_end=283
  _globals['_TCPSTATUS']._serialized_start=285
  _globals['_TCPSTATUS']._serialized_end=382
  _globals['_TCPREQ']._serialized_start=384
  _globals['_TCPREQ']._serialized_end=392
  _globals['_TCPDATA']._serialized_start=395
  _globals['_TCPDATA']._serialized_end=574
# @@protoc_insertion_point(module_scope)
