"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import google.protobuf.descriptor
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _UartState:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _UartStateEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_UartState.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    UART_STATE_CLOSED: _UartState.ValueType  # 0
    """UART is closed."""
    UART_STATE_STARTED: _UartState.ValueType  # 1
    """UART is started."""
    UART_STATE_INTERNAL_ERROR: _UartState.ValueType  # 2
    """UART encountered an internal error."""
    UART_STATE_CIOT_S_ERROR: _UartState.ValueType  # 3
    """UART encountered a CIOT-S (Custom IoT System) error."""

class UartState(_UartState, metaclass=_UartStateEnumTypeWrapper):
    """Enum representing the state of the UART module."""

UART_STATE_CLOSED: UartState.ValueType  # 0
"""UART is closed."""
UART_STATE_STARTED: UartState.ValueType  # 1
"""UART is started."""
UART_STATE_INTERNAL_ERROR: UartState.ValueType  # 2
"""UART encountered an internal error."""
UART_STATE_CIOT_S_ERROR: UartState.ValueType  # 3
"""UART encountered a CIOT-S (Custom IoT System) error."""
global___UartState = UartState

class _UartReqType:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _UartReqTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_UartReqType.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    UART_REQ_TYPE_UNKOWN: _UartReqType.ValueType  # 0
    """Unknown UART request type."""
    UART_REQ_TYPE_SEND_DATA: _UartReqType.ValueType  # 1
    """Request to send data via UART."""
    UART_REQ_TYPE_SEND_BYTES: _UartReqType.ValueType  # 2
    """Request to send bytes via UART."""

class UartReqType(_UartReqType, metaclass=_UartReqTypeEnumTypeWrapper):
    """Enum representing different types of UART requests."""

UART_REQ_TYPE_UNKOWN: UartReqType.ValueType  # 0
"""Unknown UART request type."""
UART_REQ_TYPE_SEND_DATA: UartReqType.ValueType  # 1
"""Request to send data via UART."""
UART_REQ_TYPE_SEND_BYTES: UartReqType.ValueType  # 2
"""Request to send bytes via UART."""
global___UartReqType = UartReqType

class _UartError:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _UartErrorEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_UartError.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    UART_ERROR_NONE: _UartError.ValueType  # 0
    """No UART error."""
    UART_ERROR_BREAK: _UartError.ValueType  # 1
    """UART break error."""
    UART_ERROR_BUFFER_FULL: _UartError.ValueType  # 2
    """UART buffer full error."""
    UART_ERROR_FIFO_OVERFLOW: _UartError.ValueType  # 3
    """UART FIFO overflow error."""
    UART_ERROR_FRAME: _UartError.ValueType  # 4
    """UART frame error."""
    UART_ERROR_PARITY: _UartError.ValueType  # 5
    """UART parity error."""
    UART_ERROR_DATA_BREAK: _UartError.ValueType  # 6
    """UART data break error."""
    UART_ERROR_OPEN: _UartError.ValueType  # 8
    """UART open error."""
    UART_ERROR_UNKNOWN: _UartError.ValueType  # 9
    """Unknown UART event error."""

class UartError(_UartError, metaclass=_UartErrorEnumTypeWrapper):
    """Enum representing different UART error types."""

UART_ERROR_NONE: UartError.ValueType  # 0
"""No UART error."""
UART_ERROR_BREAK: UartError.ValueType  # 1
"""UART break error."""
UART_ERROR_BUFFER_FULL: UartError.ValueType  # 2
"""UART buffer full error."""
UART_ERROR_FIFO_OVERFLOW: UartError.ValueType  # 3
"""UART FIFO overflow error."""
UART_ERROR_FRAME: UartError.ValueType  # 4
"""UART frame error."""
UART_ERROR_PARITY: UartError.ValueType  # 5
"""UART parity error."""
UART_ERROR_DATA_BREAK: UartError.ValueType  # 6
"""UART data break error."""
UART_ERROR_OPEN: UartError.ValueType  # 8
"""UART open error."""
UART_ERROR_UNKNOWN: UartError.ValueType  # 9
"""Unknown UART event error."""
global___UartError = UartError

@typing.final
class UartStop(google.protobuf.message.Message):
    """Message used to stop uart interface"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___UartStop = UartStop

@typing.final
class UartGpioCfg(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    RX_FIELD_NUMBER: builtins.int
    TX_FIELD_NUMBER: builtins.int
    RTS_FIELD_NUMBER: builtins.int
    CTS_FIELD_NUMBER: builtins.int
    rx: builtins.int
    """RX pin number."""
    tx: builtins.int
    """TX pin number."""
    rts: builtins.int
    """RTS pin number."""
    cts: builtins.int
    """CTS pin number."""
    def __init__(
        self,
        *,
        rx: builtins.int = ...,
        tx: builtins.int = ...,
        rts: builtins.int = ...,
        cts: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["cts", b"cts", "rts", b"rts", "rx", b"rx", "tx", b"tx"]) -> None: ...

global___UartGpioCfg = UartGpioCfg

@typing.final
class UartCfg(google.protobuf.message.Message):
    """Message representing configuration for the UART module."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    BAUD_RATE_FIELD_NUMBER: builtins.int
    NUM_FIELD_NUMBER: builtins.int
    GPIO_FIELD_NUMBER: builtins.int
    PARITY_FIELD_NUMBER: builtins.int
    FLOW_CONTROL_FIELD_NUMBER: builtins.int
    DTR_FIELD_NUMBER: builtins.int
    MODE_FIELD_NUMBER: builtins.int
    READ_TIMEOUT_FIELD_NUMBER: builtins.int
    WRITE_TIMEOUT_FIELD_NUMBER: builtins.int
    baud_rate: builtins.int
    """Baud rate for UART."""
    num: builtins.int
    """UART number."""
    parity: builtins.int
    """Parity for UART."""
    flow_control: builtins.bool
    """Flow control for UART."""
    dtr: builtins.bool
    """DTR (Data Terminal Ready) signal."""
    mode: builtins.int
    """UART mode (used to enable rs485 mode on some mcus)."""
    read_timeout: builtins.int
    """UART read timeout"""
    write_timeout: builtins.int
    """UART write timeout"""
    @property
    def gpio(self) -> global___UartGpioCfg:
        """GPIO configuration for UART."""

    def __init__(
        self,
        *,
        baud_rate: builtins.int = ...,
        num: builtins.int = ...,
        gpio: global___UartGpioCfg | None = ...,
        parity: builtins.int = ...,
        flow_control: builtins.bool = ...,
        dtr: builtins.bool = ...,
        mode: builtins.int = ...,
        read_timeout: builtins.int = ...,
        write_timeout: builtins.int = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["gpio", b"gpio"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["baud_rate", b"baud_rate", "dtr", b"dtr", "flow_control", b"flow_control", "gpio", b"gpio", "mode", b"mode", "num", b"num", "parity", b"parity", "read_timeout", b"read_timeout", "write_timeout", b"write_timeout"]) -> None: ...

global___UartCfg = UartCfg

@typing.final
class UartStatus(google.protobuf.message.Message):
    """Message representing status for the UART module."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    STATE_FIELD_NUMBER: builtins.int
    ERROR_FIELD_NUMBER: builtins.int
    state: global___UartState.ValueType
    """State of the UART module."""
    error: global___UartError.ValueType
    """Error encountered by the UART module."""
    def __init__(
        self,
        *,
        state: global___UartState.ValueType = ...,
        error: global___UartError.ValueType = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["error", b"error", "state", b"state"]) -> None: ...

global___UartStatus = UartStatus

@typing.final
class UartReq(google.protobuf.message.Message):
    """Message representing a UART request."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SEND_DATA_FIELD_NUMBER: builtins.int
    send_data: builtins.bytes
    def __init__(
        self,
        *,
        send_data: builtins.bytes = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["send_data", b"send_data", "type", b"type"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["send_data", b"send_data", "type", b"type"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["type", b"type"]) -> typing.Literal["send_data"] | None: ...

global___UartReq = UartReq

@typing.final
class UartData(google.protobuf.message.Message):
    """Message representing data for the UART interface."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    STOP_FIELD_NUMBER: builtins.int
    CONFIG_FIELD_NUMBER: builtins.int
    STATUS_FIELD_NUMBER: builtins.int
    REQUEST_FIELD_NUMBER: builtins.int
    @property
    def stop(self) -> global___UartStop:
        """Stop UART interface."""

    @property
    def config(self) -> global___UartCfg:
        """Configuration for the UART interface."""

    @property
    def status(self) -> global___UartStatus:
        """Status of the UART interface."""

    @property
    def request(self) -> global___UartReq:
        """UART request data."""

    def __init__(
        self,
        *,
        stop: global___UartStop | None = ...,
        config: global___UartCfg | None = ...,
        status: global___UartStatus | None = ...,
        request: global___UartReq | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["config", b"config", "request", b"request", "status", b"status", "stop", b"stop", "type", b"type"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["config", b"config", "request", b"request", "status", b"status", "stop", b"stop", "type", b"type"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["type", b"type"]) -> typing.Literal["stop", "config", "status", "request"] | None: ...

global___UartData = UartData
