# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ciot/proto/v2/uart.proto
# Protobuf Python Version: 6.30.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    0,
    '',
    'ciot/proto/v2/uart.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18\x63iot/proto/v2/uart.proto\x12\x04\x43iot\"\n\n\x08UartStop\"?\n\x0bUartGpioCfg\x12\n\n\x02rx\x18\x01 \x01(\x11\x12\n\n\x02tx\x18\x02 \x01(\x11\x12\x0b\n\x03rts\x18\x03 \x01(\x11\x12\x0b\n\x03\x63ts\x18\x04 \x01(\x11\"\xb8\x01\n\x07UartCfg\x12\x11\n\tbaud_rate\x18\x01 \x01(\r\x12\x0b\n\x03num\x18\x02 \x01(\r\x12\x1f\n\x04gpio\x18\x03 \x01(\x0b\x32\x11.Ciot.UartGpioCfg\x12\x0e\n\x06parity\x18\x04 \x01(\r\x12\x14\n\x0c\x66low_control\x18\x05 \x01(\x08\x12\x0b\n\x03\x64tr\x18\x06 \x01(\x08\x12\x0c\n\x04mode\x18\x07 \x01(\r\x12\x14\n\x0cread_timeout\x18\x08 \x01(\r\x12\x15\n\rwrite_timeout\x18\t \x01(\r\"L\n\nUartStatus\x12\x1e\n\x05state\x18\x01 \x01(\x0e\x32\x0f.Ciot.UartState\x12\x1e\n\x05\x65rror\x18\x02 \x01(\x0e\x32\x0f.Ciot.UartError\"&\n\x07UartReq\x12\x13\n\tsend_data\x18\x01 \x01(\x0cH\x00\x42\x06\n\x04type\"\x99\x01\n\x08UartData\x12\x1e\n\x04stop\x18\x01 \x01(\x0b\x32\x0e.Ciot.UartStopH\x00\x12\x1f\n\x06\x63onfig\x18\x02 \x01(\x0b\x32\r.Ciot.UartCfgH\x00\x12\"\n\x06status\x18\x03 \x01(\x0b\x32\x10.Ciot.UartStatusH\x00\x12 \n\x07request\x18\x04 \x01(\x0b\x32\r.Ciot.UartReqH\x00\x42\x06\n\x04type*v\n\tUartState\x12\x15\n\x11UART_STATE_CLOSED\x10\x00\x12\x16\n\x12UART_STATE_STARTED\x10\x01\x12\x1d\n\x19UART_STATE_INTERNAL_ERROR\x10\x02\x12\x1b\n\x17UART_STATE_CIOT_S_ERROR\x10\x03*b\n\x0bUartReqType\x12\x18\n\x14UART_REQ_TYPE_UNKOWN\x10\x00\x12\x1b\n\x17UART_REQ_TYPE_SEND_DATA\x10\x01\x12\x1c\n\x18UART_REQ_TYPE_SEND_BYTES\x10\x02*\xe5\x01\n\tUartError\x12\x13\n\x0fUART_ERROR_NONE\x10\x00\x12\x14\n\x10UART_ERROR_BREAK\x10\x01\x12\x1a\n\x16UART_ERROR_BUFFER_FULL\x10\x02\x12\x1c\n\x18UART_ERROR_FIFO_OVERFLOW\x10\x03\x12\x14\n\x10UART_ERROR_FRAME\x10\x04\x12\x15\n\x11UART_ERROR_PARITY\x10\x05\x12\x19\n\x15UART_ERROR_DATA_BREAK\x10\x06\x12\x13\n\x0fUART_ERROR_OPEN\x10\x08\x12\x16\n\x12UART_ERROR_UNKNOWN\x10\tB\x11\xaa\x02\x0e\x43iot.Protos.V2b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ciot.proto.v2.uart_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002\016Ciot.Protos.V2'
  _globals['_UARTSTATE']._serialized_start=572
  _globals['_UARTSTATE']._serialized_end=690
  _globals['_UARTREQTYPE']._serialized_start=692
  _globals['_UARTREQTYPE']._serialized_end=790
  _globals['_UARTERROR']._serialized_start=793
  _globals['_UARTERROR']._serialized_end=1022
  _globals['_UARTSTOP']._serialized_start=34
  _globals['_UARTSTOP']._serialized_end=44
  _globals['_UARTGPIOCFG']._serialized_start=46
  _globals['_UARTGPIOCFG']._serialized_end=109
  _globals['_UARTCFG']._serialized_start=112
  _globals['_UARTCFG']._serialized_end=296
  _globals['_UARTSTATUS']._serialized_start=298
  _globals['_UARTSTATUS']._serialized_end=374
  _globals['_UARTREQ']._serialized_start=376
  _globals['_UARTREQ']._serialized_end=414
  _globals['_UARTDATA']._serialized_start=417
  _globals['_UARTDATA']._serialized_end=570
# @@protoc_insertion_point(module_scope)
