"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import google.protobuf.descriptor
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _UsbState:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _UsbStateEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_UsbState.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    USB_STATE_STOPPED: _UsbState.ValueType  # 0
    """USB module is stopped."""
    USB_STATE_STARTED: _UsbState.ValueType  # 1
    """USB module is started."""
    USB_STATE_CIOT_S_ERROR: _UsbState.ValueType  # 3
    """USB module encountered CIOT-S error."""

class UsbState(_UsbState, metaclass=_UsbStateEnumTypeWrapper):
    """Enum representing the state of the USB module."""

USB_STATE_STOPPED: UsbState.ValueType  # 0
"""USB module is stopped."""
USB_STATE_STARTED: UsbState.ValueType  # 1
"""USB module is started."""
USB_STATE_CIOT_S_ERROR: UsbState.ValueType  # 3
"""USB module encountered CIOT-S error."""
global___UsbState = UsbState

@typing.final
class UsbStop(google.protobuf.message.Message):
    """Enum representing different types of USB requests.
    enum UsbReqType {
      USB_REQ_TYPE_UNKOWN = 0;             // Unknown USB request type.
      USB_REQ_TYPE_SEND_DATA = 1;          // Send data over USB.
      USB_REQ_TYPE_SEND_BYTES = 2;         // Send bytes over USB.
    }

    Stop USB interface
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___UsbStop = UsbStop

@typing.final
class UsbCfg(google.protobuf.message.Message):
    """Message representing configuration for the USB module."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    BRIDGE_MODE_FIELD_NUMBER: builtins.int
    bridge_mode: builtins.bool
    """Flag indicating whether bridge mode is enabled."""
    def __init__(
        self,
        *,
        bridge_mode: builtins.bool = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["bridge_mode", b"bridge_mode"]) -> None: ...

global___UsbCfg = UsbCfg

@typing.final
class UsbStatus(google.protobuf.message.Message):
    """Message representing status for the USB module."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    STATE_FIELD_NUMBER: builtins.int
    state: global___UsbState.ValueType
    """State of the USB module."""
    def __init__(
        self,
        *,
        state: global___UsbState.ValueType = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["state", b"state"]) -> None: ...

global___UsbStatus = UsbStatus

@typing.final
class UsbReq(google.protobuf.message.Message):
    """Message representing data for a USB request."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SEND_DATA_FIELD_NUMBER: builtins.int
    SEND_BYTES_FIELD_NUMBER: builtins.int
    send_data: builtins.bytes
    """Send data over USB."""
    send_bytes: builtins.bytes
    """Send bytes over USB."""
    def __init__(
        self,
        *,
        send_data: builtins.bytes = ...,
        send_bytes: builtins.bytes = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["send_bytes", b"send_bytes", "send_data", b"send_data", "type", b"type"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["send_bytes", b"send_bytes", "send_data", b"send_data", "type", b"type"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["type", b"type"]) -> typing.Literal["send_data", "send_bytes"] | None: ...

global___UsbReq = UsbReq

@typing.final
class UsbData(google.protobuf.message.Message):
    """Message representing data for the USB module."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    STOP_FIELD_NUMBER: builtins.int
    CONFIG_FIELD_NUMBER: builtins.int
    STATUS_FIELD_NUMBER: builtins.int
    REQUEST_FIELD_NUMBER: builtins.int
    @property
    def stop(self) -> global___UsbStop:
        """Stop USB interface"""

    @property
    def config(self) -> global___UsbCfg:
        """Configuration for the USB module."""

    @property
    def status(self) -> global___UsbStatus:
        """Status of the USB module."""

    @property
    def request(self) -> global___UsbReq:
        """USB request data."""

    def __init__(
        self,
        *,
        stop: global___UsbStop | None = ...,
        config: global___UsbCfg | None = ...,
        status: global___UsbStatus | None = ...,
        request: global___UsbReq | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["config", b"config", "request", b"request", "status", b"status", "stop", b"stop", "type", b"type"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["config", b"config", "request", b"request", "status", b"status", "stop", b"stop", "type", b"type"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["type", b"type"]) -> typing.Literal["stop", "config", "status", "request"] | None: ...

global___UsbData = UsbData
