# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ciot/proto/v2/usb.proto
# Protobuf Python Version: 6.30.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    0,
    '',
    'ciot/proto/v2/usb.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17\x63iot/proto/v2/usb.proto\x12\x04\x43iot\"\t\n\x07UsbStop\"\x1d\n\x06UsbCfg\x12\x13\n\x0b\x62ridge_mode\x18\x01 \x01(\x08\"*\n\tUsbStatus\x12\x1d\n\x05state\x18\x01 \x01(\x0e\x32\x0e.Ciot.UsbState\";\n\x06UsbReq\x12\x13\n\tsend_data\x18\x01 \x01(\x0cH\x00\x12\x14\n\nsend_bytes\x18\x02 \x01(\x0cH\x00\x42\x06\n\x04type\"\x94\x01\n\x07UsbData\x12\x1d\n\x04stop\x18\x01 \x01(\x0b\x32\r.Ciot.UsbStopH\x00\x12\x1e\n\x06\x63onfig\x18\x02 \x01(\x0b\x32\x0c.Ciot.UsbCfgH\x00\x12!\n\x06status\x18\x03 \x01(\x0b\x32\x0f.Ciot.UsbStatusH\x00\x12\x1f\n\x07request\x18\x04 \x01(\x0b\x32\x0c.Ciot.UsbReqH\x00\x42\x06\n\x04type*T\n\x08UsbState\x12\x15\n\x11USB_STATE_STOPPED\x10\x00\x12\x15\n\x11USB_STATE_STARTED\x10\x01\x12\x1a\n\x16USB_STATE_CIOT_S_ERROR\x10\x03\x42\x11\xaa\x02\x0e\x43iot.Protos.V2b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ciot.proto.v2.usb_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002\016Ciot.Protos.V2'
  _globals['_USBSTATE']._serialized_start=331
  _globals['_USBSTATE']._serialized_end=415
  _globals['_USBSTOP']._serialized_start=33
  _globals['_USBSTOP']._serialized_end=42
  _globals['_USBCFG']._serialized_start=44
  _globals['_USBCFG']._serialized_end=73
  _globals['_USBSTATUS']._serialized_start=75
  _globals['_USBSTATUS']._serialized_end=117
  _globals['_USBREQ']._serialized_start=119
  _globals['_USBREQ']._serialized_end=178
  _globals['_USBDATA']._serialized_start=181
  _globals['_USBDATA']._serialized_end=329
# @@protoc_insertion_point(module_scope)
