"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import ciot.proto.v2.tcp_pb2
import google.protobuf.descriptor
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _WifiType:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _WifiTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_WifiType.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    WIFI_TYPE_STA: _WifiType.ValueType  # 0
    """Wi-Fi station mode."""
    WIFI_TYPE_AP: _WifiType.ValueType  # 1
    """Wi-Fi access point mode."""

class WifiType(_WifiType, metaclass=_WifiTypeEnumTypeWrapper):
    """Enum representing the type of Wi-Fi connection."""

WIFI_TYPE_STA: WifiType.ValueType  # 0
"""Wi-Fi station mode."""
WIFI_TYPE_AP: WifiType.ValueType  # 1
"""Wi-Fi access point mode."""
global___WifiType = WifiType

class _WifiScanState:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _WifiScanStateEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_WifiScanState.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    WIFI_SCAN_STATE_IDLE: _WifiScanState.ValueType  # 0
    """Wi-Fi scan is idle."""
    WIFI_SCAN_STATE_SCANNING: _WifiScanState.ValueType  # 1
    """Wi-Fi scan is in progress."""
    WIFI_SCAN_STATE_DONE: _WifiScanState.ValueType  # 2
    """Wi-Fi scan completed successfully."""
    WIFI_SCAN_STATE_ERROR: _WifiScanState.ValueType  # 3
    """Error occurred during Wi-Fi scan."""

class WifiScanState(_WifiScanState, metaclass=_WifiScanStateEnumTypeWrapper):
    """Enum representing the state of Wi-Fi scanning."""

WIFI_SCAN_STATE_IDLE: WifiScanState.ValueType  # 0
"""Wi-Fi scan is idle."""
WIFI_SCAN_STATE_SCANNING: WifiScanState.ValueType  # 1
"""Wi-Fi scan is in progress."""
WIFI_SCAN_STATE_DONE: WifiScanState.ValueType  # 2
"""Wi-Fi scan completed successfully."""
WIFI_SCAN_STATE_ERROR: WifiScanState.ValueType  # 3
"""Error occurred during Wi-Fi scan."""
global___WifiScanState = WifiScanState

@typing.final
class WifiApInfo(google.protobuf.message.Message):
    """Message representing information about a Wi-Fi access point."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    BSSID_FIELD_NUMBER: builtins.int
    SSID_FIELD_NUMBER: builtins.int
    RSSI_FIELD_NUMBER: builtins.int
    AUTHMODE_FIELD_NUMBER: builtins.int
    bssid: builtins.bytes
    """BSSID (MAC address) of the access point."""
    ssid: builtins.str
    """SSID (network name) of the access point."""
    rssi: builtins.int
    """Received Signal Strength Indicator (RSSI) of the access point."""
    authmode: builtins.int
    """Authentication mode of the access point."""
    def __init__(
        self,
        *,
        bssid: builtins.bytes = ...,
        ssid: builtins.str = ...,
        rssi: builtins.int = ...,
        authmode: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["authmode", b"authmode", "bssid", b"bssid", "rssi", b"rssi", "ssid", b"ssid"]) -> None: ...

global___WifiApInfo = WifiApInfo

@typing.final
class WifiStop(google.protobuf.message.Message):
    """Stop Wi-Fi interface."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___WifiStop = WifiStop

@typing.final
class WifiCfg(google.protobuf.message.Message):
    """Message representing configuration for the Wi-Fi interface."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    DISABLED_FIELD_NUMBER: builtins.int
    SSID_FIELD_NUMBER: builtins.int
    PASSWORD_FIELD_NUMBER: builtins.int
    TYPE_FIELD_NUMBER: builtins.int
    TCP_FIELD_NUMBER: builtins.int
    disabled: builtins.bool
    """Disable Wi-Fi interface"""
    ssid: builtins.str
    """SSID of the Wi-Fi network."""
    password: builtins.str
    """Password for the Wi-Fi network."""
    type: global___WifiType.ValueType
    """Type of Wi-Fi connection."""
    @property
    def tcp(self) -> ciot.proto.v2.tcp_pb2.TcpCfg:
        """TCP configuration for Wi-Fi communication."""

    def __init__(
        self,
        *,
        disabled: builtins.bool = ...,
        ssid: builtins.str = ...,
        password: builtins.str = ...,
        type: global___WifiType.ValueType = ...,
        tcp: ciot.proto.v2.tcp_pb2.TcpCfg | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["tcp", b"tcp"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["disabled", b"disabled", "password", b"password", "ssid", b"ssid", "tcp", b"tcp", "type", b"type"]) -> None: ...

global___WifiCfg = WifiCfg

@typing.final
class WifiStatus(google.protobuf.message.Message):
    """Message representing status for the Wi-Fi interface."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    DISCONNECT_REASON_FIELD_NUMBER: builtins.int
    TCP_FIELD_NUMBER: builtins.int
    SCAN_STATE_FIELD_NUMBER: builtins.int
    RSSI_FIELD_NUMBER: builtins.int
    disconnect_reason: builtins.int
    """Reason for Wi-Fi disconnection."""
    scan_state: global___WifiScanState.ValueType
    """Wi-Fi scan state"""
    rssi: builtins.int
    """Received Signal Strength Indicator (RSSI)"""
    @property
    def tcp(self) -> ciot.proto.v2.tcp_pb2.TcpStatus:
        """Status of the TCP connection over Wi-Fi."""

    def __init__(
        self,
        *,
        disconnect_reason: builtins.int = ...,
        tcp: ciot.proto.v2.tcp_pb2.TcpStatus | None = ...,
        scan_state: global___WifiScanState.ValueType = ...,
        rssi: builtins.int = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["tcp", b"tcp"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["disconnect_reason", b"disconnect_reason", "rssi", b"rssi", "scan_state", b"scan_state", "tcp", b"tcp"]) -> None: ...

global___WifiStatus = WifiStatus

@typing.final
class WifiInfo(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TCP_FIELD_NUMBER: builtins.int
    AP_FIELD_NUMBER: builtins.int
    @property
    def tcp(self) -> ciot.proto.v2.tcp_pb2.TcpInfo: ...
    @property
    def ap(self) -> global___WifiApInfo: ...
    def __init__(
        self,
        *,
        tcp: ciot.proto.v2.tcp_pb2.TcpInfo | None = ...,
        ap: global___WifiApInfo | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["ap", b"ap", "tcp", b"tcp"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["ap", b"ap", "tcp", b"tcp"]) -> None: ...

global___WifiInfo = WifiInfo

@typing.final
class WifiReqScan(google.protobuf.message.Message):
    """Message representing scan request"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___WifiReqScan = WifiReqScan

@typing.final
class WifiReqScanResult(google.protobuf.message.Message):
    """Wifi scan result"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    COUNT_FIELD_NUMBER: builtins.int
    count: builtins.int
    """Access point count found by scan request"""
    def __init__(
        self,
        *,
        count: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["count", b"count"]) -> None: ...

global___WifiReqScanResult = WifiReqScanResult

@typing.final
class WifiReqGetAp(google.protobuf.message.Message):
    """Wifi request to get the scanned access point information"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    id: builtins.int
    """Access point ID"""
    def __init__(
        self,
        *,
        id: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["id", b"id"]) -> None: ...

global___WifiReqGetAp = WifiReqGetAp

@typing.final
class WifiReq(google.protobuf.message.Message):
    """Message representing a Wi-Fi request."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SCAN_FIELD_NUMBER: builtins.int
    SCAN_RESULT_FIELD_NUMBER: builtins.int
    GET_AP_FIELD_NUMBER: builtins.int
    AP_INFO_FIELD_NUMBER: builtins.int
    @property
    def scan(self) -> global___WifiReqScan:
        """Start wifi scanner"""

    @property
    def scan_result(self) -> global___WifiReqScanResult:
        """Wifi scanner result"""

    @property
    def get_ap(self) -> global___WifiReqGetAp:
        """Get acess point information from wifi scanner queue"""

    @property
    def ap_info(self) -> global___WifiApInfo:
        """Get acess point result"""

    def __init__(
        self,
        *,
        scan: global___WifiReqScan | None = ...,
        scan_result: global___WifiReqScanResult | None = ...,
        get_ap: global___WifiReqGetAp | None = ...,
        ap_info: global___WifiApInfo | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["ap_info", b"ap_info", "get_ap", b"get_ap", "scan", b"scan", "scan_result", b"scan_result", "type", b"type"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["ap_info", b"ap_info", "get_ap", b"get_ap", "scan", b"scan", "scan_result", b"scan_result", "type", b"type"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["type", b"type"]) -> typing.Literal["scan", "scan_result", "get_ap", "ap_info"] | None: ...

global___WifiReq = WifiReq

@typing.final
class WifiData(google.protobuf.message.Message):
    """Message representing data for the Wi-Fi interface."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    STOP_FIELD_NUMBER: builtins.int
    CONFIG_FIELD_NUMBER: builtins.int
    STATUS_FIELD_NUMBER: builtins.int
    REQUEST_FIELD_NUMBER: builtins.int
    INFO_FIELD_NUMBER: builtins.int
    @property
    def stop(self) -> global___WifiStop:
        """Stop Wi-Fi interface."""

    @property
    def config(self) -> global___WifiCfg:
        """Configuration for the Wi-Fi interface."""

    @property
    def status(self) -> global___WifiStatus:
        """Status of the Wi-Fi interface."""

    @property
    def request(self) -> global___WifiReq:
        """Wi-Fi request data."""

    @property
    def info(self) -> global___WifiInfo:
        """TCP information."""

    def __init__(
        self,
        *,
        stop: global___WifiStop | None = ...,
        config: global___WifiCfg | None = ...,
        status: global___WifiStatus | None = ...,
        request: global___WifiReq | None = ...,
        info: global___WifiInfo | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["config", b"config", "info", b"info", "request", b"request", "status", b"status", "stop", b"stop", "type", b"type"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["config", b"config", "info", b"info", "request", b"request", "status", b"status", "stop", b"stop", "type", b"type"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["type", b"type"]) -> typing.Literal["stop", "config", "status", "request", "info"] | None: ...

global___WifiData = WifiData
